export const AttributesMetadata = {
  MaxHealth: {
    name: 'Max Health',
    icon: 'Icons/Attributes/statIcon_Health',
    multiplier: 1,
  },
  Resilience: {
    name: 'Resilience',
    icon: 'Icons/Attributes/statIcon_Resilience',
    multiplier: 2,
  },
  AttackPower: {
    name: 'Weapon Power',
    icon: 'Icons/Attributes/statIcon_WeaponPower',
    multiplier: 10,
  },
  AbilityPower: {
    name: 'Ability Power',
    icon: 'Icons/Attributes/statIcon_AbilityPower',
    multiplier: 10,
  },
  CritRating: {
    name: 'Crit Rating',
    icon: 'Icons/Attributes/statIcon_CritRating',
    multiplier: 10,
  },
  CritPower: {
    name: 'Crit Power',
    icon: 'Icons/Attributes/statIcon_CritPower',
    multiplier: 10,
  },
  BreakPower: {
    name: 'Break Power',
    icon: 'Icons/Attributes/statIcon_BreakPower',
    multiplier: 10,
  },
  PhysicalDefense: {
    name: 'Phys Defense',
    icon: 'Icons/Attributes/statIcon_PhysDefense',
    multiplier: 10,
  },
  MagicalDefense: {
    name: 'Mag Defense',
    icon: 'Icons/Attributes/statIcon_MagDefense',
    multiplier: 10,
  },
  MaxStamina: {
    name: 'Max Stamina',
    icon: 'Icons/Status/Buff/buffIcon_MaxStamina',
    multiplier: 1,
  },
  HealthRegenPerSecond: { name: 'Health Regen', icon: 'None', multiplier: 1 },
  StaminaRegenPerSecond: { name: 'Stamina Regen', icon: 'None', multiplier: 1 },
  ImpactDecayPerSecond: { name: 'Impact Decay', icon: 'None', multiplier: 1 },
  OutgoingDuration: { name: 'Out Duration', icon: 'None', multiplier: 1 },
  CritDamage: { name: 'Crit Damage', icon: 'None', multiplier: 1 },
  Impact: { name: 'Impact', icon: 'None', multiplier: 1 },
  IncomingDuration: { name: 'In Duration', icon: 'None', multiplier: 1 },
  Focus: { name: 'Focus', icon: 'None', multiplier: 1 },
  MoveSpeedMultiplier: { name: 'Move Speed', icon: 'None', multiplier: 1 },
  GravityScaleMultiplier: {
    name: 'Gravity Scale',
    icon: 'None',
    multiplier: 1,
  },
  TurnRateMultiplier: { name: 'Turn Rate', icon: 'None', multiplier: 1 },
  IncomingDamageMultiplier: { name: 'In Damage', icon: 'None', multiplier: 1 },
  IncomingImpactMultiplier: {
    name: 'In Impact Damage',
    icon: 'None',
    multiplier: 1,
  },
  OutgoingDamageMultiplier: { name: 'Out Damage', icon: 'None', multiplier: 1 },
  CombatTensionValue: { name: 'Combat Tension', icon: 'None', multiplier: 1 },
  Health: {
    name: 'Health',
    icon: 'Icons/Attributes/statIcon_Health',
    multiplier: 1,
  },
  Stamina: { name: 'Stamina', icon: 'None', multiplier: 1 },
  PowerLevel: { name: 'Power Level', icon: 'None', multiplier: 1 },
  AspectMorath: { name: '', icon: 'None', multiplier: 1 },
  AspectArkyn: { name: '', icon: 'None', multiplier: 1 },
  AspectUrda: { name: '', icon: 'None', multiplier: 1 },
  ComboMod: { name: 'Combo Modifier', icon: 'None', multiplier: 1 },
  OutgoingImpactMultiplier: { name: 'Out Impact', icon: 'None', multiplier: 1 },
  ComboModMax: { name: 'Max Combo', icon: 'None', multiplier: 1 },
  ComboDecayPerSecond: { name: 'Combo Decay', icon: 'None', multiplier: 1 },
  ComboDecayCooldown: { name: '', icon: 'None', multiplier: 1 },
  ComboIncrease: { name: '', icon: 'None', multiplier: 1 },
  KnockbackResistance: {
    name: 'Knockback Resistance',
    icon: 'None',
    multiplier: 1,
  },
  CooldownDurationMultiplier: {
    name: 'Cooldown Multiplier',
    icon: 'None',
    multiplier: 1,
  },
  ComboCounter: { name: 'Combo Counter', icon: 'None', multiplier: 1 },
  TimeBetweenShots: { name: 'Rate of Fire', icon: 'None', multiplier: 1 },
  ClipSize: { name: 'Clip Size', icon: 'None', multiplier: 1 },
  CurrentClipAmmoCount: { name: 'Current Ammo', icon: 'None', multiplier: 1 },
  ShotsPerBurstFire: { name: 'Shots Per Burst', icon: 'None', multiplier: 1 },
  FiringMode: { name: 'Firing Mode', icon: 'None', multiplier: 1 },
  AccuracyBaseSpread: {
    name: 'Base Accuracy Spread',
    icon: 'None',
    multiplier: 1,
  },
  AccuracySpreadMax: { name: 'Max Spread', icon: 'None', multiplier: 1 },
  AimSpreadModifier: {
    name: 'Aiming Spread Modifier',
    icon: 'None',
    multiplier: 1,
  },
  AccuracySpreadIncreasePerShot: {
    name: 'Recoil Spread Increase',
    icon: 'None',
    multiplier: 1,
  },
  MaxHitsPerShot: { name: 'Max Hits Per Shot', icon: 'None', multiplier: 1 },
  ProjectilesPerShot: {
    name: 'Projectiles Per Shot',
    icon: 'None',
    multiplier: 1,
  },
  ReloadTime: { name: 'Reload Time', icon: 'None', multiplier: 1 },
  BaseCritChance: { name: 'Base Crit Chance', icon: 'None', multiplier: 1 },
  CritAvoidance: { name: 'Crit Avoidance', icon: 'None', multiplier: 1 },
  MultiplayerMultiplier: { name: '', icon: 'None', multiplier: 1 },
  CharStat1: { name: '', icon: 'None', multiplier: 1 },
  CharStat2: { name: '', icon: 'None', multiplier: 1 },
  CharStat3: { name: '', icon: 'None', multiplier: 1 },
  CharStat4: { name: '', icon: 'None', multiplier: 1 },
  WeapStat1: { name: '', icon: 'None', multiplier: 1 },
  WeapStat2: { name: '', icon: 'None', multiplier: 1 },
  WeapStat3: { name: '', icon: 'None', multiplier: 1 },
  WeapStat4: { name: '', icon: 'None', multiplier: 1 },
  EagleEyeGauge: { name: 'Eagle Eye', icon: 'None', multiplier: 1 },
  LockedAndLoadedCount: {
    name: 'Locked and Loaded',
    icon: 'None',
    multiplier: 1,
  },
  DamageShield: { name: 'Damage Shield', icon: 'None', multiplier: 1 },
  BlockStaminaDamageMultiplier: {
    name: 'Block Efficiency',
    icon: 'None',
    multiplier: 1,
  },
  CritBonus: { name: 'Crit Chance Bonus', icon: 'None', multiplier: 1 },
  Ability1Charges: { name: '', icon: 'None', multiplier: 1 },
  Ability1MaxCharges: { name: '', icon: 'None', multiplier: 1 },
  Ability1CurrentCooldown: { name: '', icon: 'None', multiplier: 1 },
  Ability1MaxCooldown: { name: '', icon: 'None', multiplier: 1 },
  Ability2Charges: { name: '', icon: 'None', multiplier: 1 },
  Ability2MaxCharges: { name: '', icon: 'None', multiplier: 1 },
  Ability2CurrentCooldown: { name: '', icon: 'None', multiplier: 1 },
  Ability2MaxCooldown: { name: '', icon: 'None', multiplier: 1 },
  Ability3Charges: { name: '', icon: 'None', multiplier: 1 },
  Ability3MaxCharges: { name: '', icon: 'None', multiplier: 1 },
  Ability3CurrentCooldown: { name: '', icon: 'None', multiplier: 1 },
  Ability3MaxCooldown: { name: '', icon: 'None', multiplier: 1 },
  GloomgraspReviveMeter: {
    name: 'Gloomgrasp Revive Meter',
    icon: 'None',
    multiplier: 1,
  },
  GloomgraspReviveMeterMax: {
    name: 'Gloomgrasp Revive Meter Max',
    icon: 'None',
    multiplier: 1,
  },
  InGloomgraspReviveMultiplier: {
    name: 'Incoming Revive Multiplier',
    icon: 'None',
    multiplier: 1,
  },
  GloomgraspMaxDuration: {
    name: 'Gloomgrasp Duration',
    icon: 'None',
    multiplier: 1,
  },
  GloomgraspHealthReturnPercent: {
    name: 'Gloomgrasp Health Recover Percent',
    icon: 'None',
    multiplier: 1,
  },
  GloomgraspCharges: {
    name: 'Gloomgrasp Charges',
    icon: 'None',
    multiplier: 1,
  },
  GloomgraspMaxCharges: {
    name: 'Gloomgrasp Max Charges',
    icon: 'None',
    multiplier: 1,
  },
  GloomgraspChargeRegenDuration: {
    name: 'Gloomgrasp Recharge Duration',
    icon: 'None',
    multiplier: 1,
  },
  OutGloomgraspReviveMultiplier: {
    name: 'Outgoing Revive Multiplier',
    icon: 'None',
    multiplier: 1,
  },
  GloomgraspCurrentDuration: {
    name: 'Gloomgrasp Current Duration',
    icon: 'None',
    multiplier: 1,
  },
  IncomingHealingMultiplier: {
    name: 'Incoming Healing Multiplier',
    icon: 'None',
    multiplier: 1,
  },
  OutgoingHealingMultiplier: {
    name: 'Outgoing Healing Multiplier',
    icon: 'None',
    multiplier: 1,
  },
  AbilityGlobalCooldownDuration: {
    name: 'Ability Global Cooldown',
    icon: 'None',
    multiplier: 1,
  },
  Ultimate: { name: 'Ultimate', icon: 'None', multiplier: 1 },
  UltimateMax: { name: 'Max Ultimate', icon: 'None', multiplier: 1 },
  UltimateCombatChargeRate: {
    name: 'Ultimate Combat Charge Rate',
    icon: 'None',
    multiplier: 1,
  },
  UltimateChargeMultiplier: {
    name: 'Ultimate Charge Multiplier',
    icon: 'None',
    multiplier: 1,
  },
  UltimateCombatChargeDuration: {
    name: 'Ultimate Combat Charge Duration',
    icon: 'None',
    multiplier: 1,
  },
  TrapDefense: { name: 'Trap Defense', icon: 'None', multiplier: 10 },
  ExperienceMultiplier: {
    name: 'Experience Multiplier',
    icon: 'None',
    multiplier: 1,
  },
  ArmorPiercingPercent: {
    name: 'Armor Piercing',
    icon: 'None',
    multiplier: 100,
  },
  ThreatMultiplier: { name: 'Threat Multiplier', icon: 'None', multiplier: 1 },
  BattlepassExperienceMultiplier: {
    name: 'Battlepass Experience Multiplier',
    icon: 'None',
    multiplier: 1,
  },
  TimeBetweenBurstShots: {
    name: 'Time between burst shots',
    icon: 'None',
    multiplier: 1,
  },
  ActiveReloadCenter: {
    name: 'Active Reload Center',
    icon: 'None',
    multiplier: 1,
  },
  ActiveReloadBounds: {
    name: 'Active Reload Bounds',
    icon: 'None',
    multiplier: 1,
  },
  DeathCount: { name: '', icon: 'None', multiplier: 1 },
  ArchetypeTreeLevelMaxFogSoulBudgetValue: {
    name: 'Additional Wayfinder Echo Capacity Per Slot',
    icon: 'Icons/T_UI_MissingTextureIcon',
    multiplier: 1,
  },
  ArchetypeTreeAdditionalFogSoulSlots: {
    name: 'Additional Wayfinder Echo Slots',
    icon: 'Icons/T_UI_MissingTextureIcon',
    multiplier: 1,
  },
  UltMeterGenerationPercentage: {
    name: 'Ultimate Generation Multiplier',
    icon: 'Icons/Talents/T_UI_Talent_UltGenerationUp1',
    multiplier: 1,
  },
  AbilityGlobalCooldownDurationReductionPercentage: {
    name: 'Additional Ability Cooldown Reduction',
    icon: 'Icons/Talents/T_UI_Talent_AbilityCooldownUp1',
    multiplier: 1,
  },
  ArmoryLevelMaxFogSoulBudgetValue: {
    name: 'Additional Weapon Echo Budget',
    icon: 'Icons/T_UI_MissingTextureIcon',
    multiplier: 1,
  },
  AccoladeLevelMaxFogSoulBudgetValue: {
    name: '',
    icon: 'Icons/T_UI_MissingTextureIcon',
    multiplier: 1,
  },
};

export type AttributesMetadataProps = keyof typeof AttributesMetadata;
