import { INVENTORY_ITEM } from '../structures/structures';

export const AWAKENING_STONES: INVENTORY_ITEM[] = [
  {
    key: 'AS_C_Kyros',
    localizedString: "Kyros' Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Kyros',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Kyros',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Wingrave',
    localizedString: "Wingrave's Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Wingrave',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Wingrave',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Niss',
    localizedString: "Niss' Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Niss',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Niss',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Silo',
    localizedString: "Silo's Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Silo',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Silo',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Senja',
    localizedString: "Senja's Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Senja',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Senja',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Venomess',
    localizedString: "Venomess' Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Venomess',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Venomess',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Grendel',
    localizedString: "Grendel's Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Grendel',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Grendel',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Lora',
    localizedString: "Lora's Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Lora',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Lora',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
