export const AWAKENING_STONES = [
  {
    key: 'AS_C_Kyros',
    localizedString: "Kyros' Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Kyros',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Kyros',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Wingrave',
    localizedString: "Wingrave's Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Wingrave',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Wingrave',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Niss',
    localizedString: "Niss' Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Niss',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Niss',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Silo',
    localizedString: "Silo's Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Silo',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Silo',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Senja',
    localizedString: "Senja's Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Senja',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Senja',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Venomess',
    localizedString: "Venomess' Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Venomess',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Venomess',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Grendel',
    localizedString: "Grendel's Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Grendel',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Grendel',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_C_Lora',
    localizedString: "Lora's Summoning Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/ResourceIcon_AwakeningStone_Lora',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_C_Lora',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_SnS_Starter',
    localizedString: 'Vanguard Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_SnS_015',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_SnS_Starter',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_SnS_003',
    localizedString: 'Grim Harvest Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_SnS_003',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_SnS_003',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_SnS_005',
    localizedString: 'Tooth and Claw Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_SnS_005',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_SnS_005',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_SnS_007',
    localizedString: 'Legacy Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_SnS_007',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_SnS_007',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_SnS_009',
    localizedString: 'Bastion Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_SnS_009',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_SnS_009',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_SnS_016',
    localizedString: 'Radiant Dawn Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_SnS_016',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_SnS_016',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_Axe_2H_001',
    localizedString: 'Typhoon Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2H_Axe_001',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_Axe_2H_001',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_Axe_2H_002',
    localizedString: 'Eclipse Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2H_Axe_002',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_Axe_2H_002',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2H_Mace_003',
    localizedString: 'Earth Shaker Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2H_Mace_003',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2H_Mace_003',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2H_Mace_006',
    localizedString: 'Juggernaut Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2H_Mace_006',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2H_Mace_006',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2HScythe_001',
    localizedString: 'Epitaph Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2H_Scythe_001',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2HScythe_001',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2HR_Starter',
    localizedString: 'Ransom Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2HR_008',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2HR_Starter',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2HR_003',
    localizedString: 'Arcstorm Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2HR_003',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2HR_003',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2HR_004',
    localizedString: 'Hellswarm Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2HR_004',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2HR_004',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2HR_006',
    localizedString: 'Longshot Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2HR_006',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2HR_006',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2HR_007',
    localizedString: 'Nightshade Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2HR_007',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2HR_007',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2HR_009',
    localizedString: 'Tempest Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2HR_009',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2HR_009',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2HR_012',
    localizedString: 'Duskbringer Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2HR_012',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2HR_012',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2H_Sword_001',
    localizedString: 'Colossus Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2H_Sword_001',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2H_Sword_001',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2H_Sword_007',
    localizedString: "Titan's Bane Awakening Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2H_Sword_007',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2H_Sword_007',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_DW_Starter',
    localizedString: 'Slicer & Dicer Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_Dagger_001',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_DW_Starter',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_DW_005',
    localizedString: 'Venom Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_Dagger_005',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_DW_005',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_DW_008',
    localizedString: 'Rose & Thorn Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_Dagger_008',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_DW_008',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_DW_012',
    localizedString: "Maiden's Rime Awakening Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_Dagger_012',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_DW_012',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_DW_013',
    localizedString: 'Harvest Moon Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_Dagger_013',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_DW_013',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_DW_015',
    localizedString: "Night's Edge Awakening Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_Dagger_015',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_DW_015',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2HR_013',
    localizedString: 'Voidbinder Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2HR_013',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2HR_013',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2H_Sword_009',
    localizedString: "Windmother's Fang Awakening Stone",
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2H_Sword_009',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2H_Sword_009',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_2HScythe_002',
    localizedString: 'Bloodsong Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2H_Scythe_002',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_2HScythe_002',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_DW_014',
    localizedString: 'Umbros Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_Dagger_014',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_DW_014',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_SnS_002',
    localizedString: 'Dryades Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_SnS_002',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_SnS_002',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AS_W_Axe_2H_003',
    localizedString: 'DrakenMaw Awakening Stone',
    type: 'AwakeningStone',
    icon: 'Icons/Resources/Awakening_Weapon/ResourceIcon_Awakening_2H_Axe_003',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/AwakeningStoneItems.AwakeningStoneItems'",
      rowName: 'AS_W_Axe_2H_003',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
