import { INVENTORY_ITEM } from '../structures/structures';

export const CRITICAL_PACK: INVENTORY_ITEM[] = [
  {
    key: 'DLC_VexPersona',
    localizedString: 'VenomessPersona Vex',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Venomess_CR_Vex_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
      rowName: 'DLC_VexPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
        rowName: 'DLC_VexBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_Trinket_Token',
    localizedString: 'Trinket Mount',
    type: 'Mount',
    icon: 'Icons/Mounts/CR_Trinket_Mount_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
      rowName: 'DLC_Trinket_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
        rowName: 'DLC_Trinket_Saddle_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_Trinket_Saddle_Item',
    localizedString: 'Trinket Saddle',
    type: 'Saddle',
    icon: 'Icons/Saddles/CR_Trinket_Saddle_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
      rowName: 'DLC_Trinket_Saddle_Item',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SADDLE_BEAR',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_KeylethPersona',
    localizedString: 'LoraPersona Keyleth',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_CR_Keyleth_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
      rowName: 'DLC_KeylethPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
        rowName: 'DLC_KeylethBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_VaxPersona',
    localizedString: 'NissPersona Vax',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_CR_Vax_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
      rowName: 'DLC_VaxPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
        rowName: 'DLC_VaxBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_GrogPersona',
    localizedString: 'GrendelPersona Grog',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_CR_Grog',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
      rowName: 'DLC_GrogPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_PersonaItems.DLC_CR_PersonaItems'",
        rowName: 'DLC_GrogBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_Character_Trinket_CR01',
    localizedString: 'Character Trinket 048',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_CR_Percy',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_Character_Trinkets.DLC_CR_Character_Trinkets'",
      rowName: 'DLC_Character_Trinket_CR01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_Character_Trinket_CR02',
    localizedString: 'Character Trinket 049',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_CR_Scanlan',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_Character_Trinkets.DLC_CR_Character_Trinkets'",
      rowName: 'DLC_Character_Trinket_CR02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_Character_Trinket_CR03',
    localizedString: 'Character Trinket 050',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_CR_Pike',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_Character_Trinkets.DLC_CR_Character_Trinkets'",
      rowName: 'DLC_Character_Trinket_CR03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_Character_Trinket_CR04',
    localizedString: 'Character Trinket 051',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_CR_Trinket',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_CR_Character_Trinkets.DLC_CR_Character_Trinkets'",
      rowName: 'DLC_Character_Trinket_CR04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_Spray_CR_001',
    localizedString: 'Name Spray 081',
    type: 'Spray',
    icon: 'Icons/Sprays_Textures/ItemIcons/CR_Spray_Banner_Icon_Light',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/DLC_PlayerActions_Sprays_CR.DLC_PlayerActions_Sprays_CR'",
      rowName: 'Emote_Spray_CR_001',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: true,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_Spray_CR_002',
    localizedString: 'Name Spray 075',
    type: 'Spray',
    icon: 'Icons/Sprays_Textures/ItemIcons/CR_Spray_Grog_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/DLC_PlayerActions_Sprays_CR.DLC_PlayerActions_Sprays_CR'",
      rowName: 'Emote_Spray_CR_002',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: true,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_Spray_CR_003',
    localizedString: 'Name Spray 079',
    type: 'Spray',
    icon: 'Icons/Sprays_Textures/ItemIcons/CR_Spray_Keyleth_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/DLC_PlayerActions_Sprays_CR.DLC_PlayerActions_Sprays_CR'",
      rowName: 'Emote_Spray_CR_003',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: true,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_Spray_CR_004',
    localizedString: 'Name Spray 082',
    type: 'Spray',
    icon: 'Icons/Sprays_Textures/ItemIcons/CR_Spray_Logo_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/DLC_PlayerActions_Sprays_CR.DLC_PlayerActions_Sprays_CR'",
      rowName: 'Emote_Spray_CR_004',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: true,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_Spray_CR_005',
    localizedString: 'Name Spray 080',
    type: 'Spray',
    icon: 'Icons/Sprays_Textures/ItemIcons/CR_Spray_Mercer_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/DLC_PlayerActions_Sprays_CR.DLC_PlayerActions_Sprays_CR'",
      rowName: 'Emote_Spray_CR_005',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: true,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_Spray_CR_006',
    localizedString: 'Name Spray 073',
    type: 'Spray',
    icon: 'Icons/Sprays_Textures/ItemIcons/CR_Spray_Percy_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/DLC_PlayerActions_Sprays_CR.DLC_PlayerActions_Sprays_CR'",
      rowName: 'Emote_Spray_CR_006',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: true,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_Spray_CR_007',
    localizedString: 'Name Spray 077',
    type: 'Spray',
    icon: 'Icons/Sprays_Textures/ItemIcons/CR_Spray_Pike_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/DLC_PlayerActions_Sprays_CR.DLC_PlayerActions_Sprays_CR'",
      rowName: 'Emote_Spray_CR_007',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: true,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_Spray_CR_008',
    localizedString: 'Name Spray 076',
    type: 'Spray',
    icon: 'Icons/Sprays_Textures/ItemIcons/CR_Spray_Scanlan_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/DLC_PlayerActions_Sprays_CR.DLC_PlayerActions_Sprays_CR'",
      rowName: 'Emote_Spray_CR_008',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: true,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_Spray_CR_009',
    localizedString: 'Name Spray 074',
    type: 'Spray',
    icon: 'Icons/Sprays_Textures/ItemIcons/CR_Spray_Terry_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/DLC_PlayerActions_Sprays_CR.DLC_PlayerActions_Sprays_CR'",
      rowName: 'Emote_Spray_CR_009',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: true,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_Spray_CR_010',
    localizedString: 'Name Spray 078',
    type: 'Spray',
    icon: 'Icons/Sprays_Textures/ItemIcons/CR_Spray_Twins_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/DLC_PlayerActions_Sprays_CR.DLC_PlayerActions_Sprays_CR'",
      rowName: 'Emote_Spray_CR_010',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: true,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
];

export const DLC_PACK: INVENTORY_ITEM[] = [
  {
    key: 'Bear_RK_Token',
    localizedString: 'WarBear ReaverKing',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_WarBear_ReaverKing_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Bear_RK_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
        rowName: 'Saddle_Warbear_RK_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Bear_Base_Token',
    localizedString: 'WarBear Mount 01',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_WarBear_001_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Bear_Base_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
        rowName: 'Saddle_Warbear_001_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Bear_Base_002_Token',
    localizedString: 'WarBear Mount 02',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_WarBear_002_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Bear_Base_002_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
        rowName: 'Saddle_Warbear_002_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Bear_Base_003_Token',
    localizedString: 'WarBear Mount 03',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_WarBear_003_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Bear_Base_003_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
        rowName: 'Saddle_Warbear_003_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Bear_Base_004_Token',
    localizedString: 'WarBear Mount 04',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_WarBear_004_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Bear_Base_004_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
        rowName: 'Saddle_Warbear_004_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Bear_Base_005_Token',
    localizedString: 'Panther Bobtail 04',
    type: 'Mount',
    icon: 'Icons/Mounts/Primeval_Bear_Mount_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Bear_Base_005_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
        rowName: 'Saddle_Warbear_005_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Saddle_Warbear_001_Item',
    localizedString: 'WarBear Mount Saddle01',
    type: 'Saddle',
    icon: 'Icons/Saddles/Saddle_WarBear_001_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Saddle_Warbear_001_Item',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SADDLE_BEAR',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Saddle_Warbear_002_Item',
    localizedString: 'WarBear Mount Saddle02',
    type: 'Saddle',
    icon: 'Icons/Saddles/Saddle_WarBear_002_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Saddle_Warbear_002_Item',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SADDLE_BEAR',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Saddle_Warbear_003_Item',
    localizedString: 'WarBear Mount Saddle03',
    type: 'Saddle',
    icon: 'Icons/Saddles/Saddle_WarBear_003_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Saddle_Warbear_003_Item',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SADDLE_BEAR',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Saddle_Warbear_004_Item',
    localizedString: 'Warbear Mount Saddle04',
    type: 'Saddle',
    icon: 'Icons/Saddles/Saddle_Warbear_04_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Saddle_Warbear_004_Item',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SADDLE_BEAR',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Saddle_Warbear_005_Item',
    localizedString: 'Panther Bobtail Saddle04',
    type: 'Saddle',
    icon: 'Icons/Saddles/Saddle_Warbear_05_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Saddle_Warbear_005_Item',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SADDLE_BEAR',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Saddle_Warbear_RK_Item',
    localizedString: 'WarBear ReaverKing Saddle',
    type: 'Saddle',
    icon: 'Icons/Saddles/Saddle_WarBear_ReaverKing_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/DLCMountItems.DLCMountItems'",
      rowName: 'Saddle_Warbear_RK_Item',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SADDLE_BEAR',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_WreckerPersona',
    localizedString: 'BanditWrecker',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_BanditWrecker_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
      rowName: 'DLC_WreckerPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
        rowName: 'DLC_WreckerBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_TeryssaPersona',
    localizedString: 'EldrenTeryssa',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_Teryssa_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
      rowName: 'DLC_TeryssaPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
        rowName: 'DLC_TeryssaBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_ReaverKingPersona',
    localizedString: 'ReaverKing',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_ReaverKing_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
      rowName: 'DLC_ReaverKingPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
        rowName: 'DLC_ReaverKingBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_GoblinChemistPersona',
    localizedString: 'GoblinChemist',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_GobChemist_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
      rowName: 'DLC_GoblinChemistPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
        rowName: 'DLC_GoblinChemistBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_GoblinShamanPersona',
    localizedString: 'GoblinShaman',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_GobShaman_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
      rowName: 'DLC_GoblinShamanPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
        rowName: 'DLC_GoblinShamanBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_GloomGeneralPersona',
    localizedString: 'GloomGeneral',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Wingrave_GloomGeneral_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
      rowName: 'DLC_GloomGeneralPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
        rowName: 'DLC_GloomGeneralBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_SniperPersona',
    localizedString: 'BanditRifleman',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Venomess_BanditRifleman_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
      rowName: 'DLC_SniperPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
        rowName: 'DLC_SniperBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_LordOfBladesPersona',
    localizedString: 'ReaverLordofBlades',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_LordOfBlades_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
      rowName: 'DLC_LordOfBladesPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_01_PersonaItems.DLC_01_PersonaItems'",
        rowName: 'DLC_LordOfBladesBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_TricksterPersona',
    localizedString: 'character npc trickster',
    type: 'Persona',
    icon: 'Icons/Bestiary/RenderedOfficial/WF_CreatureHeadshots_Trickster',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
      rowName: 'DLC_TricksterPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
        rowName: 'DLC_TricksterBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_SeekerAvalaPersona',
    localizedString: 'character npc fieldresearcher name',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/Npc_Portrait_SeekerAvala',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
      rowName: 'DLC_SeekerAvalaPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
        rowName: 'DLC_SeekerAvalaBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_AvarysPersona',
    localizedString: 'character npc avarys',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/Npc_Portrait_Avarys',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
      rowName: 'DLC_AvarysPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
        rowName: 'DLC_AvarysBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_ArsenalPersona',
    localizedString: 'character npc weaponmaster name',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/Npc_Portrait_Arsenal',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
      rowName: 'DLC_ArsenalPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
        rowName: 'DLC_ArsenalBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_GraymournPersona',
    localizedString: 'character npc mystic name',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/Npc_Portrait_Graymourn',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
      rowName: 'DLC_GraymournPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
        rowName: 'DLC_GraymournBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_EngineerPersona',
    localizedString: 'character npc engineer name',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/Chumps/Npc_Portrait_Engineer',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
      rowName: 'DLC_EngineerPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
        rowName: 'DLC_EngineerBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_WolfPersona',
    localizedString: 'character npc wolf name',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/Npc_Portrait_Wolf',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
      rowName: 'DLC_WolfPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
        rowName: 'DLC_WolfBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_OmenPersona',
    localizedString: 'character npc omen name',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/Npc_Portrait_Omen',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
      rowName: 'DLC_OmenPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_02_PersonaItems.DLC_02_PersonaItems'",
        rowName: 'DLC_OmenBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_GoblinPersona',
    localizedString: 'GoblinFighter',
    type: 'Persona',
    icon: 'Icons/Bestiary/UI_Icon_Bestiary_GoblinBasic_1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_GoblinPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_GoblinBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_WurmPersona',
    localizedString: 'Wurm',
    type: 'Persona',
    icon: 'Icons/Bestiary/UI_Icon_Bestiary_Wurm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_WurmPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_GoblinBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_WillowWitchPersona',
    localizedString: 'WillowWitch',
    type: 'Persona',
    icon: 'Icons/Bestiary/RenderedOfficial/WF_CreatureHeadshots_Hollow_Witch',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_WillowWitchPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_WillowWitchBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_StomperPersona',
    localizedString: 'StomperCave',
    type: 'Persona',
    icon: 'Icons/Bestiary/RenderedOfficial/WF_CreatureHeadshots_Stomper_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_StomperPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_StomperBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_HeartRipperPersona',
    localizedString: 'GloomSoldierVicar',
    type: 'Persona',
    icon: 'Icons/Bestiary/RenderedOfficial/icon_creature_gloom_HeartRipper_headshot',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_HeartRipperPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_HeartRipperBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_LurkerPersona',
    localizedString: 'LurkerGloomshadow',
    type: 'Persona',
    icon: 'Icons/Bestiary/RenderedOfficial/icon_creature_gloomshadow_Lurker_headshot',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_LurkerPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_LurkerBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_ElementalSnSPersona',
    localizedString: 'ElementalSnS',
    type: 'Persona',
    icon: 'Icons/Bestiary/RenderedOfficial/icon_creature_elemental_SnSMagma_headshot',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_ElementalSnSPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_ElementalSnSBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_OmenGloomPersona',
    localizedString: 'character npc thefirst name',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/NPC_Portrait_TheFirst',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_OmenGloomPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_OmenGloomBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_TofuPersona',
    localizedString: 'DLC TofuPersona',
    type: 'Persona',
    icon: '/Game/Environment/Materials/Ressources/T_White',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_TofuPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_TofuBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_GoblinArcherPersona',
    localizedString: 'GoblinArcher',
    type: 'Persona',
    icon: 'Icons/Bestiary/UI_Icon_Bestiary_GoblinArcher_1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_GoblinArcherPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_GoblinArcherBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_WardenHassPersona',
    localizedString: 'character npc warden name',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/Npc_Portrait_WardenHass',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_WardenHassPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_WardenHassBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_BrotherMaganPersona',
    localizedString: 'character npc formermonk name',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/Npc_Portrait_BrotherMagan',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_BrotherMaganPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_BrotherMaganBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_RangerDavynPersona',
    localizedString: 'character npc ruinsnpc name',
    type: 'Persona',
    icon: 'Icons/Characters/NPCPortrait/3D/Npc_Portrait_RangerDavyn',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_RangerDavynPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_RangerDavynBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_LancerGloomPersona',
    localizedString: 'DLC LancerGloomPersona',
    type: 'Persona',
    icon: 'Icons/LocationShards/Renders/UI_Icon_ShardRender_GloomLancer',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_LancerGloomPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_LancerGloomBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_HobgoblinPersona',
    localizedString: 'Hobgoblin',
    type: 'Persona',
    icon: 'Icons/Bestiary/RenderedOfficial/icon_creature_goblin_Hobgoblin_headshot',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_HobgoblinPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_HobgoblinBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_TravelerPersona',
    localizedString: 'character npc counterfeiter name',
    type: 'Persona',
    icon: 'Icons/Characters/SpeakerPortrait_NPCTraveler_small',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_TravelerPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_TravelerBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DLC_GoblinStackPersona',
    localizedString: 'GoblinStack',
    type: 'Persona',
    icon: 'Icons/Bestiary/UI_Icon_Bestiary_GoblinBasic_1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
      rowName: 'DLC_GoblinStackPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/DLC_03_PersonaItems.DLC_03_PersonaItems'",
        rowName: 'DLC_GoblinStackBase',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
