import { INVENTORY_ITEM } from '../structures/structures';

export const CURRENCIES: INVENTORY_ITEM[] = [
  {
    key: 'Coinage',
    localizedString: 'Gold',
    type: 'Currency',
    icon: 'Icons/Currency/WF_Icon_Item_GoldCoins_01',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'Coinage',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  // {
  //   key: 'DailyCaches',
  //   localizedString: 'Daily Caches',
  //   type: 'Currency',
  //   icon: 'Icons/MapPOI/Map_locationIcon_chest1',
  //   data: {
  //     dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
  //     rowName: 'DailyCaches',
  //   },
  //   addItemsWhenCreated: [],
  //   equipmentSlot: 'EEquipmentSlotType::INVALID',
  //   bIsArchetype: false,
  //   bIsCharacter: false,
  //   bIsCraftingMaterial: false,
  //   bIsCraftable: false,
  //   bIsEquipable: false,
  //   bIsFogSoul: false,
  //   bIsTalent: false,
  //   bIsHousingItem: false,
  //   bIsPlayerSpray: false,
  //   bIsConsumable: false,
  //   bIsFlask: false,
  //   bIsNone: false,
  //   bIsFungible: true,
  //   bIsQuestRestricted: false,
  //   bIsEventItem: false,
  //   bIsImbuementVessel: false,
  //   bIsImbuement: false,
  //   bIsPseudoItem: false,
  //   bIsIOUItem: false,
  //   bIsFungibleMultiplierItem: false,
  //   bIsDye: false,
  //   bIsPlayerAction: false,
  //   bIsPlayerBadgeCustomization: false,
  // },
  {
    key: 'Runesilver',
    localizedString: 'Runesilver',
    type: 'Currency',
    icon: 'Icons/Currency/icon_currency_runesilver_01B',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'Runesilver',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  // {
  //   key: 'XP',
  //   localizedString: 'Resonance',
  //   type: 'System',
  //   icon: 'Icons/Currency/icoon_currency_XP_01',
  //   data: {
  //     dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
  //     rowName: 'XP',
  //   },
  //   addItemsWhenCreated: [],
  //   equipmentSlot: 'EEquipmentSlotType::INVALID',
  //   bIsArchetype: false,
  //   bIsCharacter: false,
  //   bIsCraftingMaterial: false,
  //   bIsCraftable: false,
  //   bIsEquipable: false,
  //   bIsFogSoul: false,
  //   bIsTalent: false,
  //   bIsHousingItem: false,
  //   bIsPlayerSpray: false,
  //   bIsConsumable: false,
  //   bIsFlask: false,
  //   bIsNone: false,
  //   bIsFungible: true,
  //   bIsQuestRestricted: false,
  //   bIsEventItem: false,
  //   bIsImbuementVessel: false,
  //   bIsImbuement: false,
  //   bIsPseudoItem: true,
  //   bIsIOUItem: false,
  //   bIsFungibleMultiplierItem: false,
  //   bIsDye: false,
  //   bIsPlayerAction: false,
  //   bIsPlayerBadgeCustomization: false,
  // },
  {
    key: 'Mythral',
    localizedString: 'Mythral',
    type: 'Currency',
    icon: 'Icons/Currency/icon_currency_mythril_pile01B',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'Mythral',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WFRep',
    localizedString: 'Wayfinder Reputation',
    type: 'Currency',
    icon: 'Icons/Currency/WF_Icon_Item_RuneSilverCoins',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'WFRep',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'UpgradeSphere_Common',
    localizedString: 'Grey Gloomstone',
    type: 'Gloomstone',
    icon: 'Icons/Currency/icon_currency_gloomstone_grey01',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'UpgradeSphere_Common',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: true,
    bIsCraftable: true,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'UpgradeSphere_Uncommon',
    localizedString: 'Blue Gloomstone',
    type: 'Gloomstone',
    icon: 'Icons/Currency/icon_currency_gloomstone_blue01',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'UpgradeSphere_Uncommon',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: true,
    bIsCraftable: true,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'UpgradeSphere_Rare',
    localizedString: 'Red Gloomstone',
    type: 'Gloomstone',
    icon: 'Icons/Currency/icon_currency_gloomstone_red01',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'UpgradeSphere_Rare',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: true,
    bIsCraftable: true,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'UpgradeSphere_Epic',
    localizedString: 'Black Gloomstone',
    type: 'Gloomstone',
    icon: 'Icons/Currency/icon_currency_gloomstone_black01',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'UpgradeSphere_Epic',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: true,
    bIsCraftable: true,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'MemoryEcho',
    localizedString: 'Memory Fragment',
    type: 'Currency',
    icon: 'Icons/Resources/ResourceIcon_MemoryEcho',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'MemoryEcho',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: true,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  // {
  //   key: 'ScheduledQuestProgress',
  //   localizedString: 'Weekly Bonus Points',
  //   type: 'System',
  //   icon: '/Game/icon_currency_WeeklyBonusPoints',
  //   data: {
  //     dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
  //     rowName: 'ScheduledQuestProgress',
  //   },
  //   addItemsWhenCreated: [],
  //   equipmentSlot: 'EEquipmentSlotType::INVALID',
  //   bIsArchetype: false,
  //   bIsCharacter: false,
  //   bIsCraftingMaterial: false,
  //   bIsCraftable: false,
  //   bIsEquipable: false,
  //   bIsFogSoul: false,
  //   bIsTalent: false,
  //   bIsHousingItem: false,
  //   bIsPlayerSpray: false,
  //   bIsConsumable: false,
  //   bIsFlask: false,
  //   bIsNone: false,
  //   bIsFungible: true,
  //   bIsQuestRestricted: false,
  //   bIsEventItem: false,
  //   bIsImbuementVessel: false,
  //   bIsImbuement: false,
  //   bIsPseudoItem: true,
  //   bIsIOUItem: false,
  //   bIsFungibleMultiplierItem: false,
  //   bIsDye: false,
  //   bIsPlayerAction: false,
  //   bIsPlayerBadgeCustomization: false,
  // },
  {
    key: 'UpgradeSphere_Shard',
    localizedString: 'Gloomstone Shard',
    type: 'Gloomstone',
    icon: 'Icons/Currency/icon_currency_gloomstone_shard01',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'UpgradeSphere_Shard',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'HelperCoin',
    localizedString: 'Helper Coin',
    type: 'Currency',
    icon: 'Icons/Currency/icon_currency_helpercoin',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'HelperCoin',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WFToken',
    localizedString: 'WFToken',
    type: 'Currency',
    icon: 'Icons/Currency/icon_currency_wayfinderToken',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'WFToken',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  // {
  //   key: 'BattlePassXP',
  //   localizedString: 'Reward Tower XP',
  //   type: 'Currency',
  //   icon: 'Icons/Currency/icon_currency_towerxp',
  //   data: {
  //     dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
  //     rowName: 'BattlePassXP',
  //   },
  //   addItemsWhenCreated: [],
  //   equipmentSlot: 'EEquipmentSlotType::INVALID',
  //   bIsArchetype: false,
  //   bIsCharacter: false,
  //   bIsCraftingMaterial: false,
  //   bIsCraftable: false,
  //   bIsEquipable: false,
  //   bIsFogSoul: false,
  //   bIsTalent: false,
  //   bIsHousingItem: false,
  //   bIsPlayerSpray: false,
  //   bIsConsumable: false,
  //   bIsFlask: false,
  //   bIsNone: false,
  //   bIsFungible: true,
  //   bIsQuestRestricted: false,
  //   bIsEventItem: false,
  //   bIsImbuementVessel: false,
  //   bIsImbuement: false,
  //   bIsPseudoItem: true,
  //   bIsIOUItem: false,
  //   bIsFungibleMultiplierItem: false,
  //   bIsDye: false,
  //   bIsPlayerAction: false,
  //   bIsPlayerBadgeCustomization: false,
  // },
  // {
  //   key: 'FS1_TowerKey',
  //   localizedString: 'Gloom Break Tower Key',
  //   type: 'Currency',
  //   icon: 'Icons/Currency/icon_currency_BattlePassKey',
  //   data: {
  //     dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
  //     rowName: 'FS1_TowerKey',
  //   },
  //   addItemsWhenCreated: [],
  //   equipmentSlot: 'EEquipmentSlotType::INVALID',
  //   bIsArchetype: false,
  //   bIsCharacter: false,
  //   bIsCraftingMaterial: false,
  //   bIsCraftable: false,
  //   bIsEquipable: false,
  //   bIsFogSoul: false,
  //   bIsTalent: false,
  //   bIsHousingItem: false,
  //   bIsPlayerSpray: false,
  //   bIsConsumable: false,
  //   bIsFlask: false,
  //   bIsNone: false,
  //   bIsFungible: true,
  //   bIsQuestRestricted: false,
  //   bIsEventItem: false,
  //   bIsImbuementVessel: false,
  //   bIsImbuement: false,
  //   bIsPseudoItem: true,
  //   bIsIOUItem: false,
  //   bIsFungibleMultiplierItem: false,
  //   bIsDye: false,
  //   bIsPlayerAction: false,
  //   bIsPlayerBadgeCustomization: false,
  // },
  {
    key: 'TricksterKey',
    localizedString: 'Trickster Key',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_TrickstersKey_Event',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'TricksterKey',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SkeletonKey',
    localizedString: 'Skeleton Key',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_SkeletonKey_Event',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'SkeletonKey',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventCurrency_Eventide',
    localizedString: 'Revel Rubies',
    type: 'Currency',
    icon: 'Icons/Currency/icon_currency_RevelRubies',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'EventCurrency_Eventide',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventCurrency_LooseThreads',
    localizedString: 'Unraveled Resin',
    type: 'Currency',
    icon: 'Icons/Currency/icon_currency_UnraveledResin',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'EventCurrency_LooseThreads',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  // {
  //   key: 'CharacterXP',
  //   localizedString: 'Resonance',
  //   type: 'System',
  //   icon: 'Icons/Currency/icoon_currency_XP_01',
  //   data: {
  //     dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
  //     rowName: 'CharacterXP',
  //   },
  //   addItemsWhenCreated: [],
  //   equipmentSlot: 'EEquipmentSlotType::INVALID',
  //   bIsArchetype: false,
  //   bIsCharacter: false,
  //   bIsCraftingMaterial: false,
  //   bIsCraftable: false,
  //   bIsEquipable: false,
  //   bIsFogSoul: false,
  //   bIsTalent: false,
  //   bIsHousingItem: false,
  //   bIsPlayerSpray: false,
  //   bIsConsumable: false,
  //   bIsFlask: false,
  //   bIsNone: false,
  //   bIsFungible: true,
  //   bIsQuestRestricted: false,
  //   bIsEventItem: false,
  //   bIsImbuementVessel: false,
  //   bIsImbuement: false,
  //   bIsPseudoItem: true,
  //   bIsIOUItem: false,
  //   bIsFungibleMultiplierItem: false,
  //   bIsDye: false,
  //   bIsPlayerAction: false,
  //   bIsPlayerBadgeCustomization: false,
  // },
  // {
  //   key: 'WeaponXP',
  //   localizedString: 'Resonance',
  //   type: 'System',
  //   icon: 'Icons/Currency/icoon_currency_XP_01',
  //   data: {
  //     dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
  //     rowName: 'WeaponXP',
  //   },
  //   addItemsWhenCreated: [],
  //   equipmentSlot: 'EEquipmentSlotType::INVALID',
  //   bIsArchetype: false,
  //   bIsCharacter: false,
  //   bIsCraftingMaterial: false,
  //   bIsCraftable: false,
  //   bIsEquipable: false,
  //   bIsFogSoul: false,
  //   bIsTalent: false,
  //   bIsHousingItem: false,
  //   bIsPlayerSpray: false,
  //   bIsConsumable: false,
  //   bIsFlask: false,
  //   bIsNone: false,
  //   bIsFungible: true,
  //   bIsQuestRestricted: false,
  //   bIsEventItem: false,
  //   bIsImbuementVessel: false,
  //   bIsImbuement: false,
  //   bIsPseudoItem: true,
  //   bIsIOUItem: false,
  //   bIsFungibleMultiplierItem: false,
  //   bIsDye: false,
  //   bIsPlayerAction: false,
  //   bIsPlayerBadgeCustomization: false,
  // },
  {
    key: 'EchoDust',
    localizedString: 'Echo Dust',
    type: 'Currency',
    icon: 'EchoMenu/essenceIcon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'EchoDust',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'FoundersCoin',
    localizedString: 'Founder Coin',
    type: 'Currency',
    icon: 'Icons/Currency/icon_currency_runesilver_01B',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'FoundersCoin',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Frostmark',
    localizedString: 'Marks',
    type: 'Currency',
    icon: 'Icons/Currency/Frost_Marks',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'Frostmark',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'MythicMark',
    localizedString: 'Glory',
    type: 'Currency',
    icon: 'Icons/Currency/Mythic_Marks',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'MythicMark',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'GorgeMark',
    localizedString: 'Arc Shards',
    type: 'Currency',
    icon: 'Icons/Currency/gorge_currency',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/CurrencyItems.CurrencyItems'",
      rowName: 'GorgeMark',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
