import { INVENTORY_ITEM } from '../structures/structures';

export const EVENT_ITEMS: INVENTORY_ITEM[] = [
  {
    key: 'ArtifactShard',
    localizedString: 'Artifact Shard',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'ArtifactShard',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'RatHair',
    localizedString: 'RatHair',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'RatHair',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SmallPortrait',
    localizedString: 'SmallPortrait',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'SmallPortrait',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'TurtlesaurDroppings',
    localizedString: 'TurtlesaurDroppings',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'TurtlesaurDroppings',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'PetStick',
    localizedString: 'PetStick',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'PetStick',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SelfHelpBook',
    localizedString: 'SelfHelpBook',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'SelfHelpBook',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SummoningCircle_Crystal',
    localizedString: 'Crystal',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Jewel_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'SummoningCircle_Crystal',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::EVENT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ShriekRelic',
    localizedString: 'Shriek Relic',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_DataFragment_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'ShriekRelic',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::EVENT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'HiddenBell',
    localizedString: 'Bell',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'HiddenBell',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::EVENT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Betrayed',
    localizedString: 'Betrayer Helm',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'Betrayed',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'MysteryCubeItem',
    localizedString: 'Gold Duplicator',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'MysteryCubeItem',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ReverberationKey',
    localizedString: 'Reverberation Buff',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'ReverberationKey',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ArclightOverloadArcstone',
    localizedString: 'Arcstone',
    type: 'Event',
    icon: 'Icons/Resources/ResourceIcon_ElementalShellRadiant',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'ArclightOverloadArcstone',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'JailorKey',
    localizedString: 'Rusted Cell Key',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Key_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'JailorKey',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'CrownOfDecay',
    localizedString: 'Crown of Decay',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Chest_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'CrownOfDecay',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::EVENT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WurmBait',
    localizedString: 'Wurm Bait',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_PouchHerbs_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'WurmBait',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DataFragment_Spider',
    localizedString: 'Data Fragment: Broodspawn',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_DataFragment_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'DataFragment_Spider',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DataFragment_Slime',
    localizedString: 'Data Fragment: Ichor',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_DataFragment_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'DataFragment_Slime',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DataFragment_Goblin',
    localizedString: 'Data Fragment: Goblin',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_DataFragment_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'DataFragment_Goblin',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DataFragment_Warbear',
    localizedString: 'Data Fragment: Warbear',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_DataFragment_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'DataFragment_Warbear',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DataFragment_Turtlesaur',
    localizedString: 'Data Fragment: Turtlesaur',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_DataFragment_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'DataFragment_Turtlesaur',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EncodedTracer',
    localizedString: 'Encoded Tracer',
    type: 'Event',
    icon: 'Icons/Resources/ResourceIcon_DecoderTracer',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'EncodedTracer',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'FuelCanister',
    localizedString: 'Fuel Canister',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Potion_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'FuelCanister',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::EVENT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'MachineValve',
    localizedString: 'Machine Valve',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Cog_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'MachineValve',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::EVENT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Piston',
    localizedString: 'Piston',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Cog_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'Piston',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::EVENT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DrillFuel',
    localizedString: 'Drill Fuel',
    type: 'Event',
    icon: 'Icons/EventItems/EventIcon_DrillFuel',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'DrillFuel',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SupplyRaid_Charge',
    localizedString: 'Charge',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Cog_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'SupplyRaid_Charge',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'VultureBait',
    localizedString: 'Vulture Bait',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_MeatSlab_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'VultureBait',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AMatterOfTime_Hourglass',
    localizedString: 'Hourglass',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Chest_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'AMatterOfTime_Hourglass',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Godsblood',
    localizedString: 'Godsblood',
    type: 'Event',
    icon: 'Icons/EventItems/EventItem_Godsblood',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'Godsblood',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Mutator-GloomCollapse_Torch',
    localizedString: 'Torch of Radiance',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Torch_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'Mutator-GloomCollapse_Torch',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::EVENT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'RelicPillar',
    localizedString: 'Relic Pillar',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Stone_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'RelicPillar',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Eventide_Present',
    localizedString: 'Eventide Gift',
    type: 'Event',
    icon: 'Icons/EventItems/QuestItem_Present_NoBacker',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'Eventide_Present',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideExchange_GoblinGift',
    localizedString: "Plunderfool's Cache",
    type: 'Event',
    icon: 'Icons/EventItems/QuestItem_Present_NoBacker',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'EventideExchange_GoblinGift',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideExchange_YetiGift',
    localizedString: 'Pelt of Abominus ',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Tooth_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'EventideExchange_YetiGift',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideExchange_SpiderQueenGift',
    localizedString: "Winter Queen's Eye",
    type: 'Event',
    icon: 'Icons/EventItems/EventItem_WinterQueensEye',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'EventideExchange_SpiderQueenGift',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideExchange_QuestGift_1',
    localizedString: 'Eventide Cuisine Exchange Gift',
    type: 'Event',
    icon: 'Icons/EventItems/EventItemIcon_EventideDelight',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'EventideExchange_QuestGift_1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideExchange_QuestGift_2',
    localizedString: 'Wistful Breeze Exchange Gift',
    type: 'Event',
    icon: 'Icons/EventItems/EventItemIcon_WistfulBreeze',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'EventideExchange_QuestGift_2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventItem_HeartOfGold',
    localizedString: 'Heart of Gold',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'EventItem_HeartOfGold',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventItem_LooseThreadsResource',
    localizedString: 'Unraveled Resin',
    type: 'Event',
    icon: 'Icons/Currency/icon_currency_UnraveledResin',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'EventItem_LooseThreadsResource',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Eventide_Overland_GoblinItem',
    localizedString: 'Plunderfool Lure',
    type: 'Event',
    icon: 'Icons/Resources/ResourceIcon_PlunderfoolLure',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'Eventide_Overland_GoblinItem',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Event_Consumable_FriedDelight',
    localizedString: 'Dubious Deep-Fried Delight',
    type: 'Event',
    icon: 'Icons/EventItems/EventItemIcon_EventideDelight_NoBacker',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'Event_Consumable_FriedDelight',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Event_Consumable_WistfulBreeze',
    localizedString: 'Wistful Breeze',
    type: 'Event',
    icon: 'Icons/EventItems/EventItemIcon_WistfulBreeze_NoBacker',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'Event_Consumable_WistfulBreeze',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'LE_Imposter_Infuser_Minor',
    localizedString: 'Minor Greed Infuser',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Pouch_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'LE_Imposter_Infuser_Minor',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'LE_Imposter_Infuser_Major',
    localizedString: 'Major Greed Infuser',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Pouch_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'LE_Imposter_Infuser_Major',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'LE_Imposter_Infuser_Grand',
    localizedString: 'Grand Greed Infuser',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Pouch_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'LE_Imposter_Infuser_Grand',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'AstralAscension_StarShard',
    localizedString: 'Star Shard',
    type: 'Event',
    icon: 'Icons/Resources/WF_Icon_Item_StarShard',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'AstralAscension_StarShard',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SpectralKey',
    localizedString: 'Spectral Key',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Key_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'SpectralKey',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ElementalSummoning_IceShard',
    localizedString: 'Ice Shard',
    type: 'Event',
    icon: 'Icons/EventItems/Generic/QuestItem_Key_Event',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'ElementalSummoning_IceShard',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'FireLord_PrimalFragment',
    localizedString: 'Primal Fragment',
    type: 'Event',
    icon: 'Icons/Resources/Spectra/ResourceIcon_Spectra_Solar_R_H2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'FireLord_PrimalFragment',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'InfusedWurmBait',
    localizedString: 'Dark Star Wurm Bait',
    type: 'Event',
    icon: 'Icons/EventItems/DarkStarWurmBait',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'InfusedWurmBait',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: true,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ElementalOverload_Shadow',
    localizedString: 'DNT - Shadow Imbued Battery',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'ElementalOverload_Shadow',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ElementalOverload_Chaos',
    localizedString: 'DNT - Chaos Imbued Battery',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'ElementalOverload_Chaos',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ElementalOverload_Flora',
    localizedString: 'DNT - Flora Imbued Battery',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'ElementalOverload_Flora',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ElementalOverload_Greed',
    localizedString: 'DNT - Greed Imbued Battery',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'ElementalOverload_Greed',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ElementalOverload_Solar',
    localizedString: 'DNT - Solar Imbued Battery',
    type: 'Event',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Events/EventItemData.EventItemData'",
      rowName: 'ElementalOverload_Solar',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
