import { INVENTORY_ITEM } from '@/src/renderer/structures/structures';

export const XP_SCROLL_ITEMS: INVENTORY_ITEM[] = [
  {
    key: 'XPScroll_C_SM',
    localizedString: 'Small Wayfinder Resonance Cache',
    type: 'XPScroll',
    icon: 'Icons/Currency/icon_XP_Cache_CharSmall',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/XPScrollItems.XPScrollItems'",
      rowName: 'XPScroll_C_SM',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'XPScroll_C_MD',
    localizedString: 'Medium Wayfinder Resonance Cache',
    type: 'XPScroll',
    icon: 'Icons/Currency/icon_XP_Cache_CharMedium',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/XPScrollItems.XPScrollItems'",
      rowName: 'XPScroll_C_MD',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'XPScroll_C_LG',
    localizedString: 'Large Wayfinder Resonance Cache',
    type: 'XPScroll',
    icon: 'Icons/Currency/icon_XP_Cache_CharLarge',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/XPScrollItems.XPScrollItems'",
      rowName: 'XPScroll_C_LG',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
