export const FOUNDER_ITEMS = [
  {
    key: 'VenomessHelm02',
    localizedString: 'Operation Eminence Head',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style02/Ven_Helmet_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
      rowName: 'VenomessHelm02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_007_Item',
    localizedString: 'Nightshade',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/007',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_007_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_007',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileTitle_Founder01',
    localizedString: 'Wayfounder',
    type: 'Title',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_TitleGeneric1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_TitleItems.PlayerBadge_TitleItems'",
      rowName: 'ProfileTitle_Founder01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_31',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileTitle_Founder02',
    localizedString: 'Original',
    type: 'Title',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_TitleGeneric1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_TitleItems.PlayerBadge_TitleItems'",
      rowName: 'ProfileTitle_Founder02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_31',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileTitle_Founder03',
    localizedString: 'Crewmember',
    type: 'Title',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_TitleGeneric1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_TitleItems.PlayerBadge_TitleItems'",
      rowName: 'ProfileTitle_Founder03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_31',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileTitle_Founder04',
    localizedString: 'Precursor',
    type: 'Title',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_TitleGeneric1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_TitleItems.PlayerBadge_TitleItems'",
      rowName: 'ProfileTitle_Founder04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_31',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileBackground_Founders_01',
    type: 'ProfileBackground',
    localizedString: "Founder's Background",
    icon: 'ProfileBackgrounds/T_ProfileBackground_Founders_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_BackgroundItems.PlayerBadge_BackgroundItems'",
      rowName: 'ProfileBackground_Founders_01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_25',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileGlyph_FounderPack_01',
    localizedString: 'Fierce Windhowler',
    type: 'Glyph',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_GlyphFounderBundle1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_GlyphItems.PlayerBadge_GlyphItems'",
      rowName: 'ProfileGlyph_FounderPack_01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_28',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileGlyph_FounderPack_02',
    localizedString: 'Proud Strider',
    type: 'Glyph',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_GlyphFounderBundle2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_GlyphItems.PlayerBadge_GlyphItems'",
      rowName: 'ProfileGlyph_FounderPack_02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_28',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileGlyph_FounderPack_03',
    localizedString: "Protector's Crest",
    type: 'Glyph',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_GlyphFounderBundle3',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_GlyphItems.PlayerBadge_GlyphItems'",
      rowName: 'ProfileGlyph_FounderPack_03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_28',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileGlyph_FounderCrest_01',
    localizedString: 'Wayfounder Crest',
    type: 'Glyph',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_GlyphFounderTier1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_GlyphItems.PlayerBadge_GlyphItems'",
      rowName: 'ProfileGlyph_FounderCrest_01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_28',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileGlyph_FounderCrest_02',
    localizedString: 'Original Crest',
    type: 'Glyph',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_GlyphFounderTier2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_GlyphItems.PlayerBadge_GlyphItems'",
      rowName: 'ProfileGlyph_FounderCrest_02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_28',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileGlyph_FounderCrest_03',
    localizedString: 'Crewmember Crest',
    type: 'Glyph',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_GlyphFounderTier3',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_GlyphItems.PlayerBadge_GlyphItems'",
      rowName: 'ProfileGlyph_FounderCrest_03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_28',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ProfileGlyph_FounderCrest_04',
    localizedString: 'Precursor Crest',
    type: 'Glyph',
    icon: 'Icons/Glyphs/FS1/UI_BadgeCustomization_GlyphFounderTier4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_GlyphItems.PlayerBadge_GlyphItems'",
      rowName: 'ProfileGlyph_FounderCrest_04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_28',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Booster_BPXP',
    localizedString: 'Enchanted Tower Compass',
    type: 'None',
    icon: 'Icons/Currency/icon_currency_EXPEnhancer',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/BoosterInventoryItems.BoosterInventoryItems'",
      rowName: 'Booster_BPXP',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: true,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: true,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Dye_Founders_01',
    localizedString: "Founder's Blue",
    type: 'Dye',
    icon: 'Icons/Dyes/curatedOfficial/icon_dyeCurated_founderBlue',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Crafting/DyeInventoryItems.DyeInventoryItems'",
      rowName: 'Dye_Founders_01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: true,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Dye_Founders_02',
    localizedString: "Founder's Gold",
    type: 'Dye',
    icon: 'Icons/Dyes/curatedOfficial/icon_dyeCurated_founderGold',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Crafting/DyeInventoryItems.DyeInventoryItems'",
      rowName: 'Dye_Founders_02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: true,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Dye_Founders_03',
    localizedString: "Founder's White",
    type: 'Dye',
    icon: 'Icons/Dyes/curatedOfficial/icon_dyeCurated_founderWhite',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Crafting/DyeInventoryItems.DyeInventoryItems'",
      rowName: 'Dye_Founders_03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: true,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'HeroicKyrosModifier',
    localizedString: 'Heroic Kyros',
    type: 'None',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/HeroicKyros_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/HeroicModifiers.HeroicModifiers'",
      rowName: 'HeroicKyrosModifier',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'HeroicKyrosBase01',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'HeroicKyrosBelt01',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'HeroicKyrosGloves01',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'HeroicKyrosHelm01',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'HeroicKyrosShoulder01',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Crafting/DyeInventoryItems.DyeInventoryItems'",
        rowName: 'Dye_HeroicKyros_01',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Crafting/DyeInventoryItems.DyeInventoryItems'",
        rowName: 'Dye_HeroicKyros_02',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Crafting/DyeInventoryItems.DyeInventoryItems'",
        rowName: 'Dye_HeroicKyros_03',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_TitleItems.PlayerBadge_TitleItems'",
        rowName: 'ProfileTitle_037',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/UI_Customization/WallpaperItems.WallpaperItems'",
        rowName: 'Wallpaper0038',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::HEROIC_MODIFIER',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BattleMageCharacter',
    localizedString: 'Kyros',
    type: 'Character',
    icon: 'Icons/Characters/WF_BattleMage',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/CharacterInventoryItems.CharacterInventoryItems'",
      rowName: 'BattleMageCharacter',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'ArcanistPersona',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/PlayerBadge_TitleItems.PlayerBadge_TitleItems'",
        rowName: 'ProfileTitle_034',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/UI_Customization/WallpaperItems.WallpaperItems'",
        rowName: 'Wallpaper0038',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Crafting/DyeInventoryItems.DyeInventoryItems'",
        rowName: 'Dye_BlueViolet_11',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Crafting/DyeInventoryItems.DyeInventoryItems'",
        rowName: 'Dye_Kyros_04',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Base_Head05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Base_Head02',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Base_Head03',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Base_Head04',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosHead01',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Crafting/EmissiveDyeInventoryItems.EmissiveDyeInventoryItems'",
        rowName: 'Dye_Emissive_01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::CHARACTER',
    bIsArchetype: false,
    bIsCharacter: true,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Niss_FC_Helm',
    localizedString: 'Shadow Nation Headpiece',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style05/Niss_05_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/NissArmorItems.NissArmorItems'",
      rowName: 'Armor_Niss_FC_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'NissHelm05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Niss_FC_Body',
    localizedString: 'Shadow Nation Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_FC_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/NissArmorItems.NissArmorItems'",
      rowName: 'Armor_Niss_FC_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'Niss_FC_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Niss_FC_Signature',
    localizedString: 'Shadow Nation Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style05/Niss_05_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/NissArmorItems.NissArmorItems'",
      rowName: 'Armor_Niss_FC_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'NissBelt05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Niss_FC_Gear1',
    localizedString: 'Shadow Nation Gear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style05/Niss_05_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/NissArmorItems.NissArmorItems'",
      rowName: 'Armor_Niss_FC_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'NissGear05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Niss_FC_Gear2',
    localizedString: 'Shadow Nation Pants',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style05/Niss_05_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/NissArmorItems.NissArmorItems'",
      rowName: 'Armor_Niss_FC_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'NissPants05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_FC_Helm',
    localizedString: 'Firestarter Hood',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style_05_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_FC_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloHelm05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_FC_Body',
    localizedString: 'Firestarter Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_FC_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_FC_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_FC_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_FC_Signature',
    localizedString: 'Firestarter Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style_05_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_FC_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloGear05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_FC_Gear1',
    localizedString: 'Firestarter Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style05_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_FC_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloChest05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_FC_Gear2',
    localizedString: 'Firestarter Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style_05_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_FC_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloBackPack05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_FC_Body',
    localizedString: 'Knight of the Throne Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_FC_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_FC_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WingraveBase05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_FC_Signature',
    localizedString: 'Knight of the Throne Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Shoulder_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_FC_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterShoulders05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_FC_Gear1',
    localizedString: 'Knight of the Throne Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Gloves_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_FC_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGloves05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_FC_Gear2',
    localizedString: 'Knight of the Throne Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Belt_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_FC_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGear05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_FC_Helm',
    localizedString: 'Knight of the Throne Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Helmet_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_FC_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterHelmet05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Strider_002_Token',
    localizedString: 'Highlands Strider',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Horse_FoundersHorse_NoSaddle_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Strider_002_Token',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_005B',
    localizedString: 'Arcbolt',
    type: 'Persona',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/005B',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
      rowName: '2HR_005B',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::WEAPON_PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_009B',
    localizedString: 'Stormsong',
    type: 'Persona',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/009B',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
      rowName: 'DW_009B',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::WEAPON_PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_017B',
    localizedString: "Charger's Sickle",
    type: 'Persona',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/0017B',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
      rowName: 'SnS_017B',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::WEAPON_PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Housing_Pets_PantherCub',
    localizedString: 'Rimehunter Cub',
    type: 'Housing',
    icon: 'Icons/Housing/HousingPets/Icon_Housing_Pets_PantherCub_Idle_Quarter__1_',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Housing/HousingInventoryItems.HousingInventoryItems'",
      rowName: 'Housing_Pets_PantherCub',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::HOUSING',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: true,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Housing_Deco_FoundersPackGoblet',
    localizedString: 'Founders Pack Goblet',
    type: 'Housing',
    icon: 'Icons/Housing/HousingDecorations/Icon_HS_Founder_Goblet_Front',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Housing/HousingInventoryItems.HousingInventoryItems'",
      rowName: 'Housing_Deco_FoundersPackGoblet',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::HOUSING',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: true,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Housing_Deco_FoundersPackStatue',
    localizedString: 'Founders Pack Statue',
    type: 'Housing',
    icon: 'Icons/Housing/HousingDecorations/Icon_Housing_Deco_FoundersPackStatue',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Housing/HousingInventoryItems.HousingInventoryItems'",
      rowName: 'Housing_Deco_FoundersPackStatue',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::HOUSING',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: true,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Housing_Deco_FoundersPackGloomDaggerCase',
    localizedString: 'Founders Pack Gloom Dagger Case',
    type: 'Housing',
    icon: 'Icons/Housing/HousingDecorations/Icon_HS_DaggerCase_Quarter_Open_Dagger',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Housing/HousingInventoryItems.HousingInventoryItems'",
      rowName: 'Housing_Deco_FoundersPackGloomDaggerCase',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::HOUSING',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: true,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Housing_Deco_FoundersPackCrest',
    localizedString: 'Founders Pack Wall Crest',
    type: 'Housing',
    icon: 'Icons/Housing/HousingDecorations/Icon_Housing_Deco_FoundersPackCrest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Housing/HousingInventoryItems.HousingInventoryItems'",
      rowName: 'Housing_Deco_FoundersPackCrest',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::HOUSING',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: true,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'VenomessBackpack02',
    localizedString: 'Operation Eminence Backpack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style02/Ven_BackGear_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
      rowName: 'VenomessBackpack02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'VenomessGear02',
    localizedString: 'Operation Eminence Garb',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style02/Ven_Waist_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
      rowName: 'VenomessGear02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'VenomessGloves02',
    localizedString: 'Operation Eminence Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style02/Ven_Gloves_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
      rowName: 'VenomessGloves02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HScythe_001_Item',
    localizedString: 'Epitaph',
    type: 'TwoHandedScythe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Scythe/ui_icon_rendered_weapon_2HScythe_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HScytheItems.2HScytheItems'",
      rowName: '2HScythe_001_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HScythePersonas.2HScythePersonas'",
        rowName: '2HScythe_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Saddle_002_Item',
    localizedString: "Founder's Saddle",
    type: 'Saddle',
    icon: 'Icons/Saddles/Saddle_002_Icon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Mounts/SaddleItems.SaddleItems'",
      rowName: 'Saddle_002_Item',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SADDLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Venomess_UC01_Body',
    localizedString: 'Operation Eminence Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_UC01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
      rowName: 'Venomess_UC01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Emote_HeroicKyros01',
    localizedString: 'Portal',
    type: 'Emote',
    icon: 'Icons/Emotes/WF_Emote_HeroicKyros_Portal',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/PlayerActions/PlayerActions_Emotes.PlayerActions_Emotes'",
      rowName: 'Emote_HeroicKyros01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::SOCIAL_ACTION',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
];
