export const IMBUEMENTS = [
  {
    key: 'Imbuement_Mutator_Shadow',
    localizedString: 'Shadow Imbuement',
    type: 'Crafting',
    icon: 'Icons/Imbuements/T_Imbuement_Shadow',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Crafting/ImbuementItems/MutatorImbuementItems.MutatorImbuementItems'",
      rowName: 'Imbuement_Mutator_Shadow',
    },
    addItemsWhenCreated: [],
    equipmentSolt: 'EEquipmentSlotType::INVALID',
    bIsArchetype: true,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: true,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: true,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Imbuement_Mutator_Solar',
    localizedString: 'Solar Imbuement',
    type: 'Crafting',
    icon: 'Icons/Imbuements/T_Imbuement_Solar',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Crafting/ImbuementItems/MutatorImbuementItems.MutatorImbuementItems'",
      rowName: 'Imbuement_Mutator_Solar',
    },
    addItemsWhenCreated: [],
    equipmentSolt: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: true,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: true,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: true,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Imbuement_Mutator_Chaos',
    localizedString: 'Chaos Imbuement',
    type: 'Crafting',
    icon: 'Icons/Imbuements/T_Imbuement_Chaos',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Crafting/ImbuementItems/MutatorImbuementItems.MutatorImbuementItems'",
      rowName: 'Imbuement_Mutator_Chaos',
    },
    addItemsWhenCreated: [],
    equipmentSolt: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: true,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: true,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Imbuement_Mutator_Flora',
    localizedString: 'Flora Imbuement',
    type: 'Crafting',
    icon: 'Icons/Imbuements/T_Imbuement_Flora',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Crafting/ImbuementItems/MutatorImbuementItems.MutatorImbuementItems'",
      rowName: 'Imbuement_Mutator_Flora',
    },
    addItemsWhenCreated: [],
    equipmentSolt: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: true,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: true,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Imbuement_Mutator_Greed',
    localizedString: 'Greed Imbuement',
    type: 'Crafting',
    icon: 'Icons/Imbuements/T_Imbuement_Greed',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Crafting/ImbuementItems/MutatorImbuementItems.MutatorImbuementItems'",
      rowName: 'Imbuement_Mutator_Greed',
    },
    addItemsWhenCreated: [],
    equipmentSolt: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: true,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: true,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Imbuement_Mutator_EverfrostBombs',
    localizedString: 'Everfrost Bombs',
    type: 'Crafting',
    icon: 'Icons/Imbuements/LiveEvents/T_Imbuement_Everfrost',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Crafting/ImbuementItems/MutatorImbuementItems.MutatorImbuementItems'",
      rowName: 'Imbuement_Mutator_EverfrostBombs',
    },
    addItemsWhenCreated: [],
    equipmentSolt: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: true,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: true,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Imbuement_Mutator_GloomStorm',
    localizedString: 'Gloom Storm',
    type: 'Crafting',
    icon: 'Icons/Imbuements/LiveEvents/T_Imbuement_GloomStorm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Crafting/ImbuementItems/MutatorImbuementItems.MutatorImbuementItems'",
      rowName: 'Imbuement_Mutator_GloomStorm',
    },
    addItemsWhenCreated: [],
    equipmentSolt: 'EEquipmentSlotType::INVALID',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: true,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: true,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
