export const MOUNTS = [
  {
    key: 'Strider_001_Token',
    localizedString: 'Strider',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Strider_001_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Strider_001_Token',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Strider_002_Token',
    localizedString: 'Highlands Strider',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Horse_FoundersHorse_NoSaddle_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Strider_002_Token',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Strider_003_Token',
    localizedString: 'Twilight Charger',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Strider_003_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Strider_003_Token',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Cresthorn_001_Token',
    localizedString: 'Cresthorn',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Cresthorn_001_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Cresthorn_001_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/SaddleItems.SaddleItems'",
        rowName: 'Saddle_Cresthorn_001_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Cresthorn_002_Token',
    localizedString: 'Whitemarsh Charger',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Cresthorn_002_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Cresthorn_002_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/SaddleItems.SaddleItems'",
        rowName: 'Saddle_Cresthorn_002_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Cresthorn_003_Token',
    localizedString: 'Lunos Beast',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Cresthorn_003_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Cresthorn_003_Token',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Panther_001_Token',
    localizedString: 'Duskhunter',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Panther_001_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Panther_001_Token',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Panther_002_Token',
    localizedString: 'Rimehunter',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Panther_002_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Panther_002_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/SaddleItems.SaddleItems'",
        rowName: 'Saddle_Bobtail_002_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Panther_003_Token',
    localizedString: 'Dreadfang',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Panther_003_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Panther_003_Token',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Gorehound_001_Token',
    localizedString: 'Gorehound',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Gorehound_001_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Gorehound_001_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/SaddleItems.SaddleItems'",
        rowName: 'Saddle_Gorehound_001_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Gorehound_002_Token',
    localizedString: 'Voidhound',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Gorehound_002_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Gorehound_002_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/SaddleItems.SaddleItems'",
        rowName: 'None',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Gorehound_003_Token',
    localizedString: 'Rage Beast',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Gorehound_003_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Gorehound_003_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/SaddleItems.SaddleItems'",
        rowName: 'None',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'GloomPanther_Token',
    localizedString: 'Deathbringer',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Panther_004_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'GloomPanther_Token',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Astral_001_Token',
    localizedString: 'Astral Strider',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Astral_001_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Astral_001_Token',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Strider_Variant_002_Token',
    localizedString: 'Hoarfrost Strider',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Strider_Variant_002_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Strider_Variant_002_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/SaddleItems.SaddleItems'",
        rowName: 'Saddle_Base02_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Strider_Variant_003_Token',
    localizedString: 'Storm Strider',
    type: 'Mount',
    icon: 'Icons/Mounts/Mount_Strider_Variant_003_Icon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/Mounts/MountItems.MountItems'",
      rowName: 'Strider_Variant_003_Token',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Mounts/SaddleItems.SaddleItems'",
        rowName: 'Saddle_Base03_Item',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::MOUNT',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: true,
    bIsPlayerBadgeCustomization: false,
  },
];
