import { INVENTORY_ITEM } from '../structures/structures';

export const POTIONS: INVENTORY_ITEM[] = [
  {
    key: 'Potion_PhysicalDefense_Basic_T2',
    localizedString: 'Basic Broodcrystal Ichor',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_PhysicalDefense_Basic_T2',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_PhysicalDefense_Basic_T2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_PhysicalDefense_Basic_T3',
    localizedString: 'Basic Broodcrystal Ichor 2',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_PhysicalDefense_Basic_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_PhysicalDefense_Basic_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_PhysicalDefense_Greater_T3',
    localizedString: 'Greater Broodcrystal Ichor',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_PhysicalDefense_Greater_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_PhysicalDefense_Greater_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_Resilience_Basic_T2',
    localizedString: 'Basic Phoenix Ashbrew',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_Resilience_Basic_T2',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_Resilience_Basic_T2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_Resilience_Basic_T3',
    localizedString: 'Basic Phoenix Ashbrew 2',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_Resilience_Basic_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_Resilience_Basic_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_Resilience_Greater_T3',
    localizedString: 'Greater Phoenix Ashbrew',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_Resilience_Greater_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_Resilience_Greater_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_BreakPower_Basic_T2',
    localizedString: 'Basic Chimeric Bloodbrew',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_BreakPower_Basic_T2',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_BreakPower_Basic_T2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_BreakPower_Basic_T3',
    localizedString: 'Basic Chimeric Bloodbrew 2',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_BreakPower_Basic_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_BreakPower_Basic_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_BreakPower_Greater_T3',
    localizedString: 'Greater Chimeric Bloodbrew',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_BreakPowerr_Greater_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_BreakPower_Greater_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_CritPower_Basic_T2',
    localizedString: 'Basic Stomper Bloodbrew',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_CritPower_Basic_T2',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_CritPower_Basic_T2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_CritPower_Basic_T3',
    localizedString: 'Basic Stomper Bloodbrew 2',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_CritPower_Basic_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_CritPower_Basic_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_CritPower_Greater_T3',
    localizedString: 'Greater Stomper Bloodbrew',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_CritPowerr_Greater_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_CritPower_Greater_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_MaxStamina_Basic_T2',
    localizedString: 'Basic Turtlesaur Bloodbrew',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_MaxStamina_Basic_T2',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_MaxStamina_Basic_T2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_MaxStamina_Basic_T3',
    localizedString: 'Basic Turtlesaur Bloodbrew 2',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_MaxStamina_Basic_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_MaxStamina_Basic_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_PhysicalDamage_Basic_T2',
    localizedString: 'Unfiltered Dragonkin Blood',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_PhysicalDamage_Basic_T2',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_PhysicalDamage_Basic_T2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_PhysicalDamage_Basic_T3',
    localizedString: 'Filtered Dragonkin Blood',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_PhysicalDamage_Basic_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_PhysicalDamage_Basic_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_PhysicalDamage_Greater_T3',
    localizedString: 'Purified Dragonkin Blood',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_PhysicalDamage_Basic_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_PhysicalDamage_Greater_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_MagicalDamage_Basic_T2',
    localizedString: "Unstable Ancient's Tear ",
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_MagicalDamage_Basic_T2',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_MagicalDamage_Basic_T2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_MagicalDamage_Basic_T3',
    localizedString: "Stabilized Ancient's Tear ",
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_MagicalDamage_Basic_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_MagicalDamage_Basic_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_MagicalDamage_GreaterT3',
    localizedString: "Empowered Ancient's Tear ",
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_MagicalDamage_Basic_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_MagicalDamage_GreaterT3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_UltMeter_Basic_T2',
    localizedString: 'Unfiltered Arcblessed Draught',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_Basic_UltMeterGeneration_T2',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_UltMeter_Basic_T2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_UltMeter_Basic_T3',
    localizedString: 'Purified Arcblessed Draught',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_Basic_UltMeterGeneration_T3',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_UltMeter_Basic_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_SelfRevive_T2',
    localizedString: 'Phoenix Oil',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_SelfRevive',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_SelfRevive_T2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_SelfRevive_T3',
    localizedString: 'Golden Phoenix Oil',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_SelfRevive_2',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_SelfRevive_T3',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Potion_GoGoJuice',
    localizedString: 'GoGo Juice',
    type: 'Potion',
    icon: 'Icons/Flasks/FlaskIcon_GoGoJuice',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/PotionItems.PotionItems'",
      rowName: 'Potion_GoGoJuice',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::CONSUMABLE',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: true,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: true,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
