import { INVENTORY_ITEM } from '../../structures/structures';

export const GRENDEL_ARMOR_SET: INVENTORY_ITEM[] = [
  {
    key: 'Armor_Grendel_Common_Helm',
    localizedString: 'Berserker Head',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Icon-Grendel_Style01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Common_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerHelm01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Common_Body',
    localizedString: 'Berserker Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Persona_Beserker_Icon_Grendel',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Common_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Common_Signature',
    localizedString: 'Berserker Shoulders',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Icon-Grendel_Style01_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Common_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerShoulders01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Common_Gear1',
    localizedString: 'Berserker Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Icon-Grendel_Style01_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Common_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGloves01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Common_Gear2',
    localizedString: 'Berserker Chest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Icon-Grendel_Style01_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Common_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGear01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_FC_Helm',
    localizedString: 'Grendel_UC01_Helm',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_FC_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerHelm01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_FC_Body',
    localizedString: 'Grendel_UC01_Body',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_FC_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_FC_Signature',
    localizedString: 'Grendel_UC01_Signature',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_FC_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerShoulders01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_FC_Gear1',
    localizedString: 'Grendel_UC01_Gear1',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_FC_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGloves01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_FC_Gear2',
    localizedString: 'Grendel_UC01_Gear2',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_FC_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGear01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_UC01_Helm',
    localizedString: 'Reckoner Mask',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/UC01/Grendel_UC01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_UC01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_UC01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_UC01_Body',
    localizedString: 'Reckoner Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_UC01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_UC01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_UC01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_UC01_Signature',
    localizedString: 'Reckoner Shoulders',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/UC01/Grendel_UC01_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_UC01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_UC01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_UC01_Gear1',
    localizedString: 'Reckoner Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/UC01/Grendel_UC01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_UC01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_UC01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_UC01_Gear2',
    localizedString: 'Reckoner Chest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/UC01/Grendel_UC01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_UC01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_UC01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_UC02_Helm',
    localizedString: "Red Wolf's Helm",
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_05/Icon-Grendel_Style05_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_UC02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerHelm05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_UC02_Body',
    localizedString: "Red Wolf's Base",
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_UC02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_UC02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerBase05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_UC02_Signature',
    localizedString: "Red Wolf's Shoulders",
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_05/Icon-Grendel_Style05_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_UC02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerShoulders05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_UC02_Gear1',
    localizedString: "Red Wolf's Gloves",
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_05/Icon-Grendel_Style05_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_UC02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGloves05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_UC02_Gear2',
    localizedString: "Red Wolf's Chest",
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_05/Icon-Grendel_Style05_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_UC02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGear05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare01_Helm',
    localizedString: 'Shaelen Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_04/Icon-Grendel_Style04_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerHelm04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare01_Body',
    localizedString: 'Shaelen Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Rare01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerBase04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare01_Signature',
    localizedString: 'Shaelen Shoulders',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_04/Icon-Grendel_Style04_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerShoulders04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare01_Gear1',
    localizedString: 'Shaelen Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_04/Icon-Grendel_Style_04_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGloves04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare01_Gear2',
    localizedString: 'Shaelen Chest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_04/Icon-Grendel_Style04_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGear04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare02_Helm',
    localizedString: 'Bloodshorn Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_02/Icon-Grendel_Style02_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerHelm02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare02_Body',
    localizedString: 'Bloodshorn Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Rare02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerBase02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare02_Signature',
    localizedString: 'Bloodshorn Shoulders',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_02/Icon-Grendel_Style02_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerShoulders02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare02_Gear1',
    localizedString: 'Bloodshorn Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_02/Icon-Grendel_Style02_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGloves02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare02_Gear2',
    localizedString: 'Bloodshorn Chest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_02/Icon-Grendel_Style02_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGear02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare03_Helm',
    localizedString: 'Winterwar Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_03/Icon-Grendel_Style03_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerHelm03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare03_Body',
    localizedString: 'Winterwar Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Rare03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerBase03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare03_Signature',
    localizedString: 'Winterwar Shoulders',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_03/Icon-Grendel_Style03_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerShoulders03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare03_Gear1',
    localizedString: 'Winterwar Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_03/Icon-Grendel_Style03_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGloves03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Rare03_Gear2',
    localizedString: 'Winterwar Chest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_03/Icon-Grendel_Style03_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Rare03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'BerserkerGear03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic01_Helm',
    localizedString: 'Dauntless Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic01/Grendel_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic01_Body',
    localizedString: 'Dauntless Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Epic01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic01_Signature',
    localizedString: 'Dauntless Shoulders',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic01/Grendel_Epic01_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic01_Gear1',
    localizedString: 'Dauntless Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic01/Grendel_Epic01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic01_Gear2',
    localizedString: 'Dauntless Chest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic01/Grendel_Epic01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic02_Helm',
    localizedString: 'Mazewar Veteran Patch',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic02/Grendel_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic02_Body',
    localizedString: 'Mazewar Veteran Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Epic02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic02_Signature',
    localizedString: 'Mazewar Veteran Shoulders',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic02/Grendel_Epic02_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic02_Gear1',
    localizedString: 'Mazewar Veteran Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic02/Grendel_Epic02_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic02_Gear2',
    localizedString: 'Mazewar Veteran Chest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic02/Grendel_Epic02_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic03_Helm',
    localizedString: 'Knightwar Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic03/Grendel_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic03_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic03_Body',
    localizedString: 'Knightwar Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Epic03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic03_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic03_Signature',
    localizedString: 'Knightwar Shoulders',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic03/Grendel_Epic03_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic03_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic03_Gear1',
    localizedString: 'Knightwar Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic03/Grendel_Epic03_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic03_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Epic03_Gear2',
    localizedString: 'Knightwar Chest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic03/Grendel_Epic03_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Epic03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Epic03_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Legendary01_Helm',
    localizedString: 'Bonesaw Mask',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Legendary01/Grendel_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Legendary01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Legendary01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Legendary01_Body',
    localizedString: 'Bonesaw Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Legendary01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Legendary01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Legendary01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Legendary01_Signature',
    localizedString: 'Bonesaw Shoulders',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Legendary01/Grendel_Legendary01_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Legendary01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Legendary01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Legendary01_Gear1',
    localizedString: 'Bonesaw Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Legendary01/Grendel_Legendary01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Legendary01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Legendary01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Legendary01_Gear2',
    localizedString: 'Bonesaw Chest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Legendary01/Grendel_Legendary01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Legendary01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Legendary01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Legendary02_Helm',
    localizedString: 'Bonesaw Mask',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Legendary02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Legendary02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Legendary02_Body',
    localizedString: 'Bonesaw Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Legendary02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Legendary02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Legendary02_Signature',
    localizedString: 'Bonesaw Shoulders',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Legendary02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Legendary02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Legendary02_Gear1',
    localizedString: 'Bonesaw Gloves',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Legendary02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Legendary02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Grendel_Legendary02_Gear2',
    localizedString: 'Bonesaw Chest',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
      rowName: 'Armor_Grendel_Legendary02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Legendary02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
