export const KYROS_ARMOR_SET = [
  {
    key: 'Armor_Kyros_Common_Helm',
    localizedString: 'Warmage Hood',
    type: 'Armor',
    icon: 'Icons/Personas/BattleMage/BattleMage_Helm_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Common_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosHelm01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Common_Body',
    localizedString: 'Warmage Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Persona_Core1_Icon_Kyros',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Common_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Common_Signature',
    localizedString: 'Warmage Field Belt',
    type: 'Armor',
    icon: 'Icons/Personas/BattleMage/BattleMage_Waist_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Common_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosBelt01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Common_Gear1',
    localizedString: 'Warmage Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/BattleMage/BattleMage_Gloves_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Common_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosGloves01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Common_Gear2',
    localizedString: 'Warmage Cover',
    type: 'Armor',
    icon: 'Icons/Personas/BattleMage/BattleMage_Shoulder_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Common_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosShoulder01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_FC_Helm',
    localizedString: 'Ashfall Wraps',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style03/Kyros03_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_FC_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosHelm03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_FC_Body',
    localizedString: 'Ashfall Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_FC',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_FC_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_FC_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_FC_Signature',
    localizedString: 'Ashfall Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style03/Kyros03_Belt2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_FC_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosBelt03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_FC_Gear1',
    localizedString: 'Ashfall Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style03/Kyros03_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_FC_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosGloves03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_FC_Gear2',
    localizedString: 'Ashfall Cowl',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style03/Kyros03_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_FC_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosShoulder03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_UC01_Helm',
    localizedString: 'Voidscribe Mask',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style02/Kyros02_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_UC01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosHelm02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_UC01_Body',
    localizedString: 'Voidscribe Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_UC01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_UC01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_UC01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_UC01_Signature',
    localizedString: 'Voidscribe Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style02/Kyros02_Belt2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_UC01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosBelt02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_UC01_Gear1',
    localizedString: 'Voidscribe Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style02/Kyros02_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_UC01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosGloves02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_UC01_Gear2',
    localizedString: 'Voidscribe Cover',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style02/Kyros02_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_UC01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosShoulder02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_UC02_Helm',
    localizedString: 'Enigmata Hood',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/UC02/Kyros_UC02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_UC02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_UC02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_UC02_Body',
    localizedString: 'Enigmata Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_UC02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_UC02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_UC02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_UC02_Signature',
    localizedString: 'Enigmata Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/UC02/Kyros_UC02_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_UC02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_UC02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_UC02_Gear1',
    localizedString: 'Enigmata Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/UC02/Kyros_UC02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_UC02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_UC02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_UC02_Gear2',
    localizedString: 'Enigmata Cover',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/UC02/Kyros_UC02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_UC02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_UC02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare01_Helm',
    localizedString: 'Stargazer Hood',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare01_Body',
    localizedString: 'Stargazer Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Rare01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare01_Signature',
    localizedString: 'Stargazer Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare01_Gear1',
    localizedString: 'Stargazer Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare01_Gear2',
    localizedString: 'Stargazer Cover',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare02_Helm',
    localizedString: 'Cursewrit Stare',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style05/Kyros_05_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare02_Body',
    localizedString: 'Cursewrit Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Rare02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare02_Signature',
    localizedString: 'Cursewrit Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style05/Kyros_05_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare02_Gear1',
    localizedString: 'Cursewrit Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style05/Kyros_05_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare02_Gear2',
    localizedString: 'Cursewrit Cowl',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style05/Kyros_05_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare03_Helm',
    localizedString: 'Emptiness Hood',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Rare03/Kyros_Rare03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare03_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare03_Body',
    localizedString: 'Emptiness Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Rare03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare03_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare03_Signature',
    localizedString: 'Emptiness Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Rare03/Kyros_Rare03_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare03_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare03_Gear1',
    localizedString: 'Emptiness Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Rare03/Kyros_Rare03_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare03_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Rare03_Gear2',
    localizedString: 'Emptiness Cover',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Rare03/Kyros_Rare03_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Rare03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Rare03_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic01_Helm',
    localizedString: 'Far Traveler Hat',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic01/Kyros_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic01_Body',
    localizedString: 'Far Traveler Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Epic01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic01_Signature',
    localizedString: 'Far Traveler Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic01/Kyros_Epic01_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic01_Gear1',
    localizedString: 'Far Traveler Bands',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic01/Kyros_Epic01_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic01_Gear2',
    localizedString: 'Far Traveler Cover',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic01/Kyros_Epic01_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic02_Helm',
    localizedString: 'Orphic Regalia Hood',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic02/Kyros_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic02_Body',
    localizedString: 'Orphic Regalia Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Epic02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic02_Signature',
    localizedString: 'Orphic Regalia Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic02/Kyros_Epic02_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic02_Gear1',
    localizedString: 'Orphic Regalia Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic02/Kyros_Epic02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic02_Gear2',
    localizedString: 'Orphic Regalia Cover',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic02/Kyros_Epic02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic03_Helm',
    localizedString: 'Anathema Head',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic03/Kyros_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic03_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic03_Body',
    localizedString: 'Anathema Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Epic03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic03_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic03_Signature',
    localizedString: 'Anathema Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic03/Kyros_Epic03_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic03_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic03_Gear1',
    localizedString: 'Anathema Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic03/Kyros_Epic03_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic03_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Epic03_Gear2',
    localizedString: 'Anathema Cover',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic03/Kyros_Epic03_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Epic03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Epic03_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Legendary01_Helm',
    localizedString: 'Fathomless Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Legendary01/Kyros_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Legendary01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Legendary01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Legendary01_Body',
    localizedString: 'Fathomless Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Legendary01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Legendary01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Legendary01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Legendary01_Signature',
    localizedString: 'Fathomless Belt',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Legendary01/Kyros_Legendary01_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Legendary01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Legendary01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Legendary01_Gear1',
    localizedString: 'Fathomless Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Legendary01/Kyros_Legendary01_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Legendary01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Legendary01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Legendary01_Gear2',
    localizedString: 'Fathomless Cover',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Legendary01/Kyros_Legendary01_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Legendary01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_Legendary01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Legendary02_Helm',
    localizedString: 'Fathomless Helm',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Legendary02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Legendary02_Body',
    localizedString: 'Fathomless Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Legendary02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Legendary02_Signature',
    localizedString: 'Fathomless Belt',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Legendary02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Legendary02_Gear1',
    localizedString: 'Fathomless Gloves',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Legendary02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Kyros_Legendary02_Gear2',
    localizedString: 'Fathomless Cover',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
      rowName: 'Armor_Kyros_Legendary02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
