export const LORA_ARMOR_SET = [
  {
    key: 'Armor_Lora_Common_Helm',
    localizedString: 'Scarlet Blade Collar',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Common_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Common_Body',
    localizedString: 'Scarlet Blade Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Common_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Common_Signature',
    localizedString: 'Scarlet Blade Belt',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Common_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Common_Gear1',
    localizedString: 'Scarlet Blade Gear',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Common_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Common_Gear2',
    localizedString: 'Scarlet Blade Pants',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Common_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_UC01_Helm',
    localizedString: 'Scarlet Blade Collar',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_UC01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_UC01_Body',
    localizedString: 'Scarlet Blade Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_UC01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_UC01_Signature',
    localizedString: 'Scarlet Blade Belt',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_UC01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_UC01_Gear1',
    localizedString: 'Scarlet Blade Gear',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_UC01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_UC01_Gear2',
    localizedString: 'Scarlet Blade Pants',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_UC01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare01_Helm',
    localizedString: 'Scarlet Blade Collar',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare01_Body',
    localizedString: 'Scarlet Blade Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare01_Signature',
    localizedString: 'Scarlet Blade Belt',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare01_Gear1',
    localizedString: 'Scarlet Blade Gear',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare01_Gear2',
    localizedString: 'Scarlet Blade Pants',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare02_Helm',
    localizedString: 'Scarlet Blade Collar',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare02_Body',
    localizedString: 'Scarlet Blade Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare02_Signature',
    localizedString: 'Scarlet Blade Belt',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare02_Gear1',
    localizedString: 'Scarlet Blade Gear',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare02_Gear2',
    localizedString: 'Scarlet Blade Pants',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic01_Helm',
    localizedString: 'Scarlet Blade Collar',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic01_Body',
    localizedString: 'Scarlet Blade Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic01_Signature',
    localizedString: 'Scarlet Blade Belt',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic01_Gear1',
    localizedString: 'Scarlet Blade Gear',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic01_Gear2',
    localizedString: 'Scarlet Blade Pants',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic02_Helm',
    localizedString: 'Scarlet Blade Collar',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic02_Body',
    localizedString: 'Scarlet Blade Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic02_Signature',
    localizedString: 'Scarlet Blade Belt',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic02_Gear1',
    localizedString: 'Scarlet Blade Gear',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic02_Gear2',
    localizedString: 'Scarlet Blade Pants',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic03_Helm',
    localizedString: 'Scarlet Blade Collar',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic03_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic03_Body',
    localizedString: 'Scarlet Blade Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic03_Signature',
    localizedString: 'Scarlet Blade Belt',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic03_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic03_Gear1',
    localizedString: 'Scarlet Blade Gear',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic03_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic03_Gear2',
    localizedString: 'Scarlet Blade Pants',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic03_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary01_Helm',
    localizedString: 'Scarlet Blade Collar',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary01_Body',
    localizedString: 'Scarlet Blade Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary01_Signature',
    localizedString: 'Scarlet Blade Belt',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary01_Gear1',
    localizedString: 'Scarlet Blade Gear',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary01_Gear2',
    localizedString: 'Scarlet Blade Pants',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary02_Helm',
    localizedString: 'Scarlet Blade Collar',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary02_Body',
    localizedString: 'Scarlet Blade Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary02_Signature',
    localizedString: 'Scarlet Blade Belt',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary02_Gear1',
    localizedString: 'Scarlet Blade Gear',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary02_Gear2',
    localizedString: 'Scarlet Blade Pants',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
