import { INVENTORY_ITEM } from '../../structures/structures';

export const LORA_ARMOR_SET: INVENTORY_ITEM[] = [
  {
    key: 'Armor_Lora_Common_Helm',
    localizedString: 'Vessel Headdress',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Common/Lora_Common_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Common_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraHelm01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Common_Body',
    localizedString: 'Vessel Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_Common_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Common_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Common_Signature',
    localizedString: 'Vessel Epauliers',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Common/Lora_Common_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Common_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraShoulders01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Common_Gear1',
    localizedString: 'Vessel Gear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Common/Lora_Common_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Common_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraGear01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Common_Gear2',
    localizedString: 'Vessel Pants',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Common/Lora_Common_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Common_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraPants01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_UC01_Helm',
    localizedString: 'Acolyte Headdress',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/UC01/Lora_UC01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_UC01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraHelm02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_UC01_Body',
    localizedString: 'Acolyte Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_UC01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_UC01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_UC01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_UC01_Signature',
    localizedString: 'Acolyte Epauliers',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/UC01/Lora_UC01_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_UC01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraShoulders02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_UC01_Gear1',
    localizedString: 'Acolyte Gear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/UC01/Lora_UC01_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_UC01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraGear02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_UC01_Gear2',
    localizedString: 'Acolyte Pants',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/UC01/Lora_UC01_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_UC01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraPants02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare01_Helm',
    localizedString: 'Vandal Fist Headdress',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Rare01/Lora_Rare01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraHelm04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare01_Body',
    localizedString: 'Vandal Fist Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_Rare01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Rare01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare01_Signature',
    localizedString: 'Vandal Fist Epauliers',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Rare01/Lora_Rare01_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraShoulders04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare01_Gear1',
    localizedString: 'Vandal Fist Gear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Rare01/Lora_Rare01_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraGear04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare01_Gear2',
    localizedString: 'Vandal Fist Pants',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Rare01/Lora_Rare01_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraPants04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare02_Helm',
    localizedString: 'Valiance Headdress',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Rare02/Lora_Rare02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraHelm03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare02_Body',
    localizedString: 'Valiance Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_Rare02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Rare02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare02_Signature',
    localizedString: 'Valiance Epauliers',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Rare02/Lora_Rare02_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraShoulders03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare02_Gear1',
    localizedString: 'Valiance Gear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Rare02/Lora_Rare02_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraGear03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Rare02_Gear2',
    localizedString: 'Valiance Pants',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Rare02/Lora_Rare02_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Rare02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'LoraPants03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic01_Helm',
    localizedString: 'Electra Heart Headdress',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic01/Lora_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic01_Body',
    localizedString: 'Electra Heart Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_Epic01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic01_Signature',
    localizedString: 'Electra Heart Epauliers',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic01/Lora_Epic01_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic01_Gear1',
    localizedString: 'Electra Heart Gear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic01/Lora_Epic01_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic01_Gear2',
    localizedString: 'Electra Heart Pants',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic01/Lora_Epic01_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic02_Helm',
    localizedString: 'Knightwire Headdress',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic02/Lora_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic02_Body',
    localizedString: 'Knightwire Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_Epic02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic02_Signature',
    localizedString: 'Knightwire Epauliers',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic02/Lora_Epic02_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic02_Gear1',
    localizedString: 'Knightwire Gear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic02/Lora_Epic02_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic02_Gear2',
    localizedString: 'Knightwire Pants',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic02/Lora_Epic02_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic03_Helm',
    localizedString: 'Tundra Stalker Headdress',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic03/Lora_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic03_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic03_Body',
    localizedString: 'Tundra Stalker Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_Epic03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic03_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic03_Signature',
    localizedString: 'Tundra Stalker Epauliers',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic03/Lora_Epic03_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic03_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic03_Gear1',
    localizedString: 'Tundra Stalker Gear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic03/Lora_Epic03_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic03_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Epic03_Gear2',
    localizedString: 'Tundra Stalker Pants',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Epic03/Lora_Epic03_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Epic03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Epic03_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary01_Helm',
    localizedString: 'Aerie Priest Headdress',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Legendary01/Lora_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Legendary01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary01_Body',
    localizedString: 'Aerie Priest Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_Legendary01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Legendary01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary01_Signature',
    localizedString: 'Aerie Priest Epauliers',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Legendary01/Lora_Legendary01_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Legendary01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary01_Gear1',
    localizedString: 'Aerie Priest Gear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Legendary01/Lora_Legendary01_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Legendary01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary01_Gear2',
    localizedString: 'Aerie Priest Pants',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Legendary01/Lora_Legendary01_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Legendary01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary02_Helm',
    localizedString: 'Duskcaller Headdress',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Legendary02/Lora_Legendary02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Legendary02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary02_Body',
    localizedString: 'Duskcaller Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Lora_Legendary02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Legendary02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary02_Signature',
    localizedString: 'Duskcaller Epauliers',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Legendary02/Lora_Legendary02_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Legendary02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary02_Gear1',
    localizedString: 'Duskcaller Gear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Legendary02/Lora_Legendary02_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Legendary02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Lora_Legendary02_Gear2',
    localizedString: 'Duskcaller Pants',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Lora/Legendary02/Lora_Legendary02_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/LoraArmorItems.LoraArmorItems'",
      rowName: 'Armor_Lora_Legendary02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/LoraPersonaItems.LoraPersonaItems'",
        rowName: 'Lora_Legendary02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
