export const SILO_ARMOR_SET = [
  {
    key: 'Armor_Silo_Common_Helm',
    localizedString: 'Tactician Mask',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Style_01_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Common_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloHelm01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Common_Body',
    localizedString: 'Tactician Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Persona_Core1_Icon_Silo',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Common_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Common_Signature',
    localizedString: 'Tactician Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Style_01_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Common_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloGear01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Common_Gear1',
    localizedString: 'Tactician Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Style01_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Common_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloChest01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Common_Gear2',
    localizedString: 'Tactician Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Style_01_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Common_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloBackPack01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_FC_Helm',
    localizedString: 'Firestarter Hood',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style_05_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_FC_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloHelm05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_FC_Body',
    localizedString: 'Firestarter Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_FC_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_FC_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_FC_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_FC_Signature',
    localizedString: 'Firestarter Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style_05_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_FC_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloGear05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_FC_Gear1',
    localizedString: 'Firestarter Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style05_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_FC_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloChest05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_FC_Gear2',
    localizedString: 'Firestarter Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style_05_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_FC_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloBackPack05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_UC01_Helm',
    localizedString: 'Smuggler Head',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo02/Silo_Style_02_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_UC01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloHelm02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_UC01_Body',
    localizedString: 'Smuggler Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_UC01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_UC01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_UC01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_UC01_Signature',
    localizedString: 'Smuggler Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo02/Silo_Style_02_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_UC01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloGear02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_UC01_Gear1',
    localizedString: 'Smuggler Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo02/Silo_Style02_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_UC01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloChest02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_UC01_Gear2',
    localizedString: 'Smuggler Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo02/Silo_Style_02_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_UC01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloBackPack02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_UC02_Helm',
    localizedString: 'Scavenge Runner Monoptics',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo03/Silo_Style_03_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_UC02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloHelm03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_UC02_Body',
    localizedString: 'Scavenge Runner Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_UC02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_UC02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_UC02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_UC02_Signature',
    localizedString: 'Scavenge Runner Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo03/Silo_Style_03_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_UC02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloGear03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_UC02_Gear1',
    localizedString: 'Scavenge Runner Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo03/Silo_Style03_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_UC02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloChest03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_UC02_Gear2',
    localizedString: 'Scavenge Runner Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo03/Silo_Style_03_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_UC02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloBackPack03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare01_Helm',
    localizedString: 'Scoundrel Headwraps',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo04/Silo_Style_04_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloHelm04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare01_Body',
    localizedString: 'Scoundrel Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Rare01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare01_Signature',
    localizedString: 'Scoundrel Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo04/Silo_Style_04_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloGear04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare01_Gear1',
    localizedString: 'Scoundrel Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo04/Silo_Style04_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloChest04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare01_Gear2',
    localizedString: 'Scoundrel Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo04/Silo_Style_04_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloBackPack04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare02_Helm',
    localizedString: 'Mayhem Mask',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare02/Silo_Rare02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare02_Body',
    localizedString: 'Mayhem Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Rare02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare02_Signature',
    localizedString: 'Mayhem Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare02/Silo_Rare02_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare02_Gear1',
    localizedString: 'Mayhem Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare02/Silo_Rare02_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare02_Gear2',
    localizedString: 'Mayhem Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare02/Silo_Rare02_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare03_Helm',
    localizedString: 'Streetwise Mask',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare03/Silo_Rare03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare03_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare03_Body',
    localizedString: 'Streetwise Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Rare03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare03_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare03_Signature',
    localizedString: 'Streetwise Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare03/Silo_Rare03_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare03_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare03_Gear1',
    localizedString: 'Streetwise Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare03/Silo_Rare03_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare03_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Rare03_Gear2',
    localizedString: 'Streetwise Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare03/Silo_Rare03_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Rare03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Rare03_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic01_Helm',
    localizedString: 'Bloodrunner Mask',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic01/Silo_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic01_Body',
    localizedString: 'Bloodrunner Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Epic01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic01_Signature',
    localizedString: 'Bloodrunner Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic01/Silo_Epic01_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic01_Gear1',
    localizedString: 'Bloodrunner Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic01/Silo_Epic01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic01_Gear2',
    localizedString: 'Bloodrunner Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic01/Silo_Epic01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic02_Helm',
    localizedString: 'Cindershot Headpiece',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic02/Silo_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic02_Body',
    localizedString: 'Cindershot Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Epic02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic02_Signature',
    localizedString: 'Cindershot Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic02/Silo_Epic02_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic02_Gear1',
    localizedString: 'Cindershot Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic02/Silo_Epic02_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic02_Gear2',
    localizedString: 'Cindershot Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic02/Silo_Epic02_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic03_Helm',
    localizedString: 'Hazard Pay Eyepatch',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic03/Silo_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic03_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic03_Body',
    localizedString: 'Hazard Pay Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Epic03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic03_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic03_Signature',
    localizedString: 'Hazard Pay Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic03/Silo_Epic03_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic03_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic03_Gear1',
    localizedString: 'Hazard Pay Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic03/Silo_Epic03_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic03_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Epic03_Gear2',
    localizedString: 'Hazard Pay Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic03/Silo_Epic03_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Epic03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Epic03_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Legendary01_Helm',
    localizedString: 'Malevolence Head',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Legendary01/Silo_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Legendary01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Legendary01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Legendary01_Body',
    localizedString: 'Malevolence Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Legendary01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Legendary01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Legendary01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Legendary01_Signature',
    localizedString: 'Malevolence Pack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Legendary01/Silo_Legendary01_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Legendary01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Legendary01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Legendary01_Gear1',
    localizedString: 'Malevolence Vest',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Legendary01/Silo_Legendary01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Legendary01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Legendary01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Legendary01_Gear2',
    localizedString: 'Malevolence Bag',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Legendary01/Silo_Legendary01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Legendary01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Legendary01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Legendary02_Helm',
    localizedString: 'Gloomhacker Mask',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Legendary02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Legendary02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Legendary02_Body',
    localizedString: 'Gloomhacker Base',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Legendary02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Legendary02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Legendary02_Signature',
    localizedString: 'Gloomhacker Pack',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Legendary02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Legendary02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Legendary02_Gear1',
    localizedString: 'Gloomhacker Vest',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Legendary02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Legendary02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Silo_Legendary02_Gear2',
    localizedString: 'Gloomhacker Bag',
    type: 'Armor',
    icon: 'Icons/Accessories/AccessoryIcon_missing',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
      rowName: 'Armor_Silo_Legendary02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_Legendary02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
