export const VENOMESS_ARMOR_SET = [
  {
    key: 'Armor_Venomess_Common_Helm',
    localizedString: 'Alchemist Head',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style01/Ven_head_S1_New',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Common_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessHelm01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Common_Body',
    localizedString: 'Alchemist Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Persona_Core1_Icon_Venomess',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Common_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Common_Signature',
    localizedString: 'Alchemist Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style01/Ven_BackGear_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Common_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessBackpack01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Common_Gear1',
    localizedString: 'Alchemist Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style01/Ven_Gloves_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Common_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGloves01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Common_Gear2',
    localizedString: 'Alchemist Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style01/Ven_Waist_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Common_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGear01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_FC_Helm',
    localizedString: 'Poisonproof Head',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style03/Venomess03_Head_Helmet',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_FC_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessHelm03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_FC_Body',
    localizedString: 'Poisonproof Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_FC_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_FC_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_FC_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_FC_Signature',
    localizedString: 'Poisonproof Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style03/Venomess03_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_FC_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessBackpack03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_FC_Gear1',
    localizedString: 'Poisonproof Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style03/Venomess03_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_FC_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGloves03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_FC_Gear2',
    localizedString: 'Poisonproof Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style03/Venomess03_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_FC_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGear03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_UC01_Helm',
    localizedString: 'Operation Eminence Head',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style02/Ven_Helmet_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_UC01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessHelm02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_UC01_Body',
    localizedString: 'Operation Eminence Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_UC01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_UC01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_UC01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_UC01_Signature',
    localizedString: 'Operation Eminence Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style02/Ven_BackGear_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_UC01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessBackpack02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_UC01_Gear1',
    localizedString: 'Operation Eminence Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style02/Ven_Gloves_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_UC01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGloves02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_UC01_Gear2',
    localizedString: 'Operation Eminence Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style02/Ven_Waist_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_UC01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGear02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_UC02_Helm',
    localizedString: 'Dissonance Mask',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/UC02/Ven_UC02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_UC02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_UC02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_UC02_Body',
    localizedString: 'Dissonance Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_UC02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_UC02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_UC02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_UC02_Signature',
    localizedString: 'Dissonance Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/UC02/Ven_UC02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_UC02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_UC02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_UC02_Gear1',
    localizedString: 'Dissonance Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/UC02/Ven_UC02_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_UC02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_UC02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_UC02_Gear2',
    localizedString: 'Dissonance Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/UC02/Ven_UC02_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_UC02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_UC02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare01_Helm',
    localizedString: 'Mazepunk Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style05/Ven-Head_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessHelm05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare01_Body',
    localizedString: 'Mazepunk Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_Rare01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Rare01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare01_Signature',
    localizedString: 'Mazepunk Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style05/Ven-BackGear_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessBackpack05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare01_Gear1',
    localizedString: 'Mazepunk Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style05/Ven_Gloves_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGloves05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare01_Gear2',
    localizedString: 'Mazepunk Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style05/Ven-Waist_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGear05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare02_Helm',
    localizedString: 'Hand of Tox Head',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style04/Ven-Head_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessHelm04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare02_Body',
    localizedString: 'Hand of Tox Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_Rare02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Rare02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare02_Signature',
    localizedString: 'Hand of Tox Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style04/Ven-Backpack_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessBackpack04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare02_Gear1',
    localizedString: 'Hand of Tox Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style04/Ven-Gloves_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGloves04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare02_Gear2',
    localizedString: 'Hand of Tox Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style04/Ven-Waist_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGear04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare03_Helm',
    localizedString: 'Sky Havoc Headgear',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Rare03/Ven_Rare03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Rare03_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare03_Body',
    localizedString: 'Sky Havoc Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_Rare03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Rare03_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare03_Signature',
    localizedString: 'Sky Havoc Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Rare03/Ven_Rare03_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Rare03_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare03_Gear1',
    localizedString: 'Sky Havoc Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Rare03/Ven_Rare03_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Rare03_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Rare03_Gear2',
    localizedString: 'Sky Havoc Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Rare03/Ven_Rare03_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Rare03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Rare03_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic01_Helm',
    localizedString: 'Vagabond Hat',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic01/Ven_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic01_Body',
    localizedString: 'Vagabond Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_Epic01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic01_Signature',
    localizedString: 'Vagabond Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic01/Ven_Epic01_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic01_Gear1',
    localizedString: 'Vagabond Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic01/Ven_Epic01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic01_Gear2',
    localizedString: 'Vagabond Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic01/Ven_Epic01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic02_Helm',
    localizedString: 'Vandal Heart Mask',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic02/Ven_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic02_Body',
    localizedString: 'Vandal Heart Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_Epic02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic02_Signature',
    localizedString: 'Vandal Heart Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic02/Ven_Epic02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic02_Gear1',
    localizedString: 'Vandal Heart Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic02/Ven_Epic02_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic02_Gear2',
    localizedString: 'Vandal Heart Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic02/Ven_Epic02_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic03_Helm',
    localizedString: 'Moonfallen Headpiece',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic03/Ven_Epic03Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic03_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic03_Body',
    localizedString: 'Moonfallen Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_Epic03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic03_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic03_Signature',
    localizedString: 'Moonfallen Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic03/Ven_Epic03_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic03_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic03_Gear1',
    localizedString: 'Moonfallen Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic03/Ven_Epic03_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic03_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Epic03_Gear2',
    localizedString: 'Moonfallen Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Epic03/Ven_Epic03_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Epic03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Epic03_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Legendary01_Helm',
    localizedString: 'Bloodseeker Hat',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Legendary01/Ven_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Legendary01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Legendary01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Legendary01_Body',
    localizedString: 'Bloodseeker Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_Legendary01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Legendary01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Legendary01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Legendary01_Signature',
    localizedString: 'Bloodseeker Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Legendary01/Ven_Legendary01_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Legendary01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Legendary01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Legendary01_Gear1',
    localizedString: 'Bloodseeker Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Legendary01/Ven_Legendary01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Legendary01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Legendary01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Legendary01_Gear2',
    localizedString: 'Bloodseeker Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Legendary01/Ven_Legendary01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Legendary01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Legendary01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Legendary02_Helm',
    localizedString: 'Nightbane Head',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Legendary02/Ven_Legendary02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Legendary02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Legendary02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Legendary02_Body',
    localizedString: 'Nightbane Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Ven_Legendary02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Legendary02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Legendary02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Legendary02_Signature',
    localizedString: 'Nightbane Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Legendary02/Ven_Legendary02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Legendary02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Legendary02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Legendary02_Gear1',
    localizedString: 'Nightbane Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Legendary02/Ven_Legendary02_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Legendary02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Legendary02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Venomess_Legendary02_Gear2',
    localizedString: 'Nightbane Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Legendary02/Ven_Legendary02_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_Venomess_Legendary02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'Venomess_Legendary02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_VenomessHelm01',
    localizedString: 'Alchemist Head',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style01/Ven_head_S1_New',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_VenomessHelm01',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessHelm01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_VenomessBase01',
    localizedString: 'Alchemist Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Persona_Core1_Icon_Venomess',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_VenomessBase01',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_VenomessBackpack01',
    localizedString: 'Alchemist Backpack',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style01/Ven_BackGear_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_VenomessBackpack01',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessBackpack01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_VenomessGear01',
    localizedString: 'Alchemist Garb',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style01/Ven_Waist_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_VenomessGear01',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGear01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_VenomessGloves01',
    localizedString: 'Alchemist Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Style01/Ven_Gloves_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/VenomessArmorItems.VenomessArmorItems'",
      rowName: 'Armor_VenomessGloves01',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/VenomessPersonaItems.VenomessPersonaItems'",
        rowName: 'VenomessGloves01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
