export const WINGRAVE_ARMOR_SET = [
  {
    key: 'Armor_Wingrave_Common_Helm',
    localizedString: 'Seeker Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Shoulder_Helmet_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Common_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterHelmet01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Common_Body',
    localizedString: 'Seeker Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Persona_Core1_Icon_Wingrave',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Common_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WingraveBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Common_Signature',
    localizedString: 'Seeker Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Shoulder_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Common_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterShoulders01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Common_Gear1',
    localizedString: 'Seeker Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Gloves_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Common_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGloves01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Common_Gear2',
    localizedString: 'Seeker Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Belt_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Common_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGear01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_FC_Helm',
    localizedString: 'Knight of the Throne Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Helmet_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_FC_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterHelmet05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_FC_Body',
    localizedString: 'Knight of the Throne Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_FC_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_FC_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WingraveBase05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_FC_Signature',
    localizedString: 'Knight of the Throne Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Shoulder_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_FC_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterShoulders05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_FC_Gear1',
    localizedString: 'Knight of the Throne Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Gloves_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_FC_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGloves05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_FC_Gear2',
    localizedString: 'Knight of the Throne Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Belt_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_FC_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGear05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_UC01_Helm',
    localizedString: 'Imperial Vanguard Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style02/Wingrave_Helmet_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_UC01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterHelmet02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_UC01_Body',
    localizedString: 'Imperial Vanguard Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style02/Wingrave_UC01_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_UC01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WingraveBase02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_UC01_Signature',
    localizedString: 'Imperial Vanguard Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style02/Wingrave_Shoulder_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_UC01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterShoulders02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_UC01_Gear1',
    localizedString: 'Imperial Vanguard Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style02/Wingrave_Gloves_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_UC01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGloves02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_UC01_Gear2',
    localizedString: 'Imperial Vanguard Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style02/Wingrave_Belt_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_UC01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGear02',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_UC02_Helm',
    localizedString: 'Bannerlord Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/UC02/Wingrave_UC02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_UC02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_UC02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_UC02_Body',
    localizedString: 'Bannerlord Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/UC02/Wingrave_UC02_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_UC02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_UC02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_UC02_Signature',
    localizedString: 'Bannerlord Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/UC02/Wingrave_UC02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_UC02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_UC02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_UC02_Gear1',
    localizedString: 'Bannerlord Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/UC02/Wingrave_UC02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_UC02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_UC02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_UC02_Gear2',
    localizedString: 'Bannerlord Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/UC02/Wingrave_UC02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_UC02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_UC02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare01_Helm',
    localizedString: 'Archon Inquisitor Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style03/Wingrave_Helmet_S3',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterHelmet03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare01_Body',
    localizedString: 'Archon Inquisitor Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style03/Wingrave_Rare01_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WingraveBase03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare01_Signature',
    localizedString: 'Archon Inquisitor Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style03/Wingrave_Shoulder_S3',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterShoulders03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare01_Gear1',
    localizedString: 'Archon Inquisitor Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style03/Wingrave_Gloves_S3',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGloves03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare01_Gear2',
    localizedString: 'Archon Inquisitor Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style03/Wingrave_Belt_S3',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGear03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare02_Helm',
    localizedString: 'Legionnaire Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Rare02/Wingrave_Rare02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Rare02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare02_Body',
    localizedString: 'Legionnaire Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Rare02/Wingrave_Rare02_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Rare02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare02_Signature',
    localizedString: 'Legionnaire Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Rare02/Wingrave_Rare02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Rare02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare02_Gear1',
    localizedString: 'Legionnaire Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Rare02/Wingrave_Rare02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Rare02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare02_Gear2',
    localizedString: 'Legionnaire Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Rare02/Wingrave_Rare02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Rare02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare03_Helm',
    localizedString: 'Skylight Warden Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style04/Wingrave_Helmet_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterHelmet04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare03_Body',
    localizedString: 'Skylight Warden Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style04/Wingrave_Rare03_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WingraveBase04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare03_Signature',
    localizedString: 'Skylight Warden Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style04/Wingrave_Shoulder_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterShoulders04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare03_Gear1',
    localizedString: 'Skylight Warden Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style04/Wingrave_Gloves_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGloves04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Rare03_Gear2',
    localizedString: 'Skylight Warden Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style04/Wingrave_Belt_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Rare03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGear04',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic01_Helm',
    localizedString: 'Lightbearer Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic01/Wingrave_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic01_Body',
    localizedString: 'Lightbearer Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic01/Wingrave_Epic01_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic01_Signature',
    localizedString: 'Lightbearer Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic01/Wingrave_Epic01_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic01_Gear1',
    localizedString: 'Lightbearer Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic01/Wingrave_Epic01_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic01_Gear2',
    localizedString: 'Lightbearer Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic01/Wingrave_Epic01_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic02_Helm',
    localizedString: 'Biohazard Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic02/Wingrave_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic02_Body',
    localizedString: 'Biohazard Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic02/Wingrave_Epic02_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic02_Signature',
    localizedString: 'Biohazard Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic02/Wingrave_Epic02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic02_Gear1',
    localizedString: 'Biohazard Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic02/Wingrave_Epic02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic02_Gear2',
    localizedString: 'Biohazard Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic02/Wingrave_Epic02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic03_Helm',
    localizedString: 'Luminary Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic03/Wingrave_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic03_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic03_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic03_Body',
    localizedString: 'Luminary Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic03/Wingrave_Epic03_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic03_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic03_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic03_Signature',
    localizedString: 'Luminary Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic03/Wingrave_Epic03_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic03_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic03_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic03_Gear1',
    localizedString: 'Luminary Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic03/Wingrave_Epic03_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic03_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic03_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Epic03_Gear2',
    localizedString: 'Luminary Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic03/Wingrave_Epic03_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Epic03_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Epic03_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Legendary01_Helm',
    localizedString: "Storm's End Helm",
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary01/Wingrave_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Legendary01_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Lengendary01_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Legendary01_Body',
    localizedString: "Storm's End Base",
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary01/Wingrave_Legendary01_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Legendary01_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Lengendary01_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Legendary01_Signature',
    localizedString: "Storm's End Pauldrons",
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary01/Wingrave_Legendary01_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Legendary01_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Lengendary01_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Legendary01_Gear1',
    localizedString: "Storm's End Gloves",
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary01/Wingrave_Legendary01_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Legendary01_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Lengendary01_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Legendary01_Gear2',
    localizedString: "Storm's End Sash",
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary01/Wingrave_Legendary01_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Legendary01_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Lengendary01_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Legendary02_Helm',
    localizedString: 'Vaelgard Helm',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary02/Wingrave_Legendary02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Legendary02_Helm',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Lengendary02_Helm',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Legendary02_Body',
    localizedString: 'Vaelgard Base',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary02/Wingrave_Legendary02_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Legendary02_Body',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Lengendary02_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Legendary02_Signature',
    localizedString: 'Vaelgard Pauldrons',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary02/Wingrave_Legendary02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Legendary02_Signature',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Lengendary02_Signature',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Legendary02_Gear1',
    localizedString: 'Vaelgard Gloves',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary02/Wingrave_Legendary02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Legendary02_Gear1',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Lengendary02_Gear1',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Armor_Wingrave_Legendary02_Gear2',
    localizedString: 'Vaelgard Sash',
    type: 'Armor',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary02/Wingrave_Legendary02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
      rowName: 'Armor_Wingrave_Legendary02_Gear2',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'Wingrave_Lengendary02_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::ARMOR_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
