import { INVENTORY_ITEM } from '../../structures/structures';

export const BATTLEMAGE_PERSONAL_ITEMS: INVENTORY_ITEM[] = [
  {
    key: 'Kyros_Core01_Style03',
    localizedString: 'Ashfall',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_FC',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Core01_Style03',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosBelt03',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosGloves03',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosHelm03',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosShoulder03',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'Kyros_FC_Body',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosPersonaMasquerade',
    localizedString: 'The Masque',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Masque_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosPersonaMasquerade',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'KyrosBaseMasquerade01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosRevenantPersona',
    localizedString: 'Revenant',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Revenant_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosRevenantPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
        rowName: 'RevenantKyrosBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'HeroicArcanistPersona',
    localizedString: 'Ascendant Warmage',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Persona_HeroicCore1_Icon_Kyros',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'HeroicArcanistPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
        rowName: 'Armor_Kyros_Common_Helm',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
        rowName: 'Armor_Kyros_Common_Body',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
        rowName: 'Armor_Kyros_Common_Signature',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
        rowName: 'Armor_Kyros_Common_Gear1',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
        rowName: 'Armor_Kyros_Common_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ArcanistPersona',
    localizedString: 'The Warmage',
    type: 'Persona',
    icon: 'Icons/Personas/BattleMage/Battlemage_Persona_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'ArcanistPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
        rowName: 'Armor_Kyros_Common_Helm',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
        rowName: 'Armor_Kyros_Common_Body',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
        rowName: 'Armor_Kyros_Common_Signature',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
        rowName: 'Armor_Kyros_Common_Gear1',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/KyrosArmorItems.KyrosArmorItems'",
        rowName: 'Armor_Kyros_Common_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosHelm01',
    localizedString: 'Warmage Hood',
    type: 'Style',
    icon: 'Icons/Personas/BattleMage/BattleMage_Helm_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosHelm01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosHead01',
    localizedString: 'Hairstyle 01',
    type: 'Style',
    icon: 'Icons/Personas/BattleMage/BattleMage_Head_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosHead01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosShoulder01',
    localizedString: 'Warmage Cover',
    type: 'Style',
    icon: 'Icons/Personas/BattleMage/BattleMage_Shoulder_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosShoulder01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosBelt01',
    localizedString: 'Warmage Field Belt',
    type: 'Style',
    icon: 'Icons/Personas/BattleMage/BattleMage_Waist_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosBelt01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosGloves01',
    localizedString: 'Warmage Gloves',
    type: 'Style',
    icon: 'Icons/Personas/BattleMage/BattleMage_Gloves_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosGloves01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'HeroicKyrosBelt01',
    localizedString: 'Ascendant Field Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/HeroicKyros/Kyros_Heroic_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'HeroicKyrosBelt01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'HeroicKyrosShoulder01',
    localizedString: 'Ascendant Scholar Cover',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/HeroicKyros/Kyros_Heroic_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'HeroicKyrosShoulder01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'HeroicKyrosHelm01',
    localizedString: 'Ascendant Mage Hood',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/HeroicKyros/HeroicKyros_Head_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'HeroicKyrosHelm01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'HeroicKyrosGloves01',
    localizedString: 'Ascendant Researcher Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/HeroicKyros/HeroicKyros_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'HeroicKyrosGloves01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosHelm02',
    localizedString: 'Voidscribe Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style02/Kyros02_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosHelm02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosShoulder02',
    localizedString: 'Voidscribe Cover',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style02/Kyros02_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosShoulder02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosBelt02',
    localizedString: 'Voidscribe Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style02/Kyros02_Belt2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosBelt02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosGloves02',
    localizedString: 'Voidscribe Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style02/Kyros02_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosGloves02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosHelm03',
    localizedString: 'Ashfall Wraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style03/Kyros03_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosHelm03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosShoulder03',
    localizedString: 'Ashfall Cowl',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style03/Kyros03_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosShoulder03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosBelt03',
    localizedString: 'Ashfall Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style03/Kyros03_Belt2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosBelt03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosGloves03',
    localizedString: 'Ashfall Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style03/Kyros03_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosGloves03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosHelm04',
    localizedString: 'Stargazer Hood',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosHelm04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosShoulder04',
    localizedString: 'Stargazer Cover',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosShoulder04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosBelt04',
    localizedString: 'Stargazer Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosBelt04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosGloves04',
    localizedString: 'Stargazer Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosGloves04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosHelm05',
    localizedString: 'Cursewrit Stare',
    type: 'Style',
    icon: 'Icons/Personas/BattleMage/BattleMage_Helm_05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosHelm05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosShoulder05',
    localizedString: 'Cursewrit Cowl',
    type: 'Style',
    icon: 'Icons/Personas/BattleMage/BattleMage_Shoulder_05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosShoulder05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosGloves05',
    localizedString: 'Cursewrit Gloves',
    type: 'Style',
    icon: 'Icons/Personas/BattleMage/BattleMage_Gloves_05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosGloves05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosBelt05',
    localizedString: 'Cursewrit Belt',
    type: 'Style',
    icon: 'Icons/Personas/BattleMage/BattleMage_Waist_05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosBelt05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosBase01',
    localizedString: 'Warmage Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Persona_Core1_Icon_Kyros',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'HeroicKyrosBase01',
    localizedString: 'Ascendant Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Persona_HeroicCore1_Icon_Kyros',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'HeroicKyrosBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'RevenantKyrosBase01',
    localizedString: 'Revenant',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Revenant_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'RevenantKyrosBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'KyrosBaseMasquerade01',
    localizedString: 'The Masque',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Persona_Masque_Icon_Kyros',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'KyrosBaseMasquerade01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_UC01_Body',
    localizedString: 'Voidscribe Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_UC01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_UC01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_FC_Body',
    localizedString: 'Ashfall Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_FC',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_FC_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare01_Helm',
    localizedString: 'Stargazer Hood',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare01_Body',
    localizedString: 'Stargazer Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Rare01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare01_Signature',
    localizedString: 'Stargazer Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare01_Gear1',
    localizedString: 'Stargazer Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare01_Gear2',
    localizedString: 'Stargazer Cover',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style04/Kyros_04_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare02_Helm',
    localizedString: 'Cursewrit Stare',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style05/Kyros_05_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare02_Body',
    localizedString: 'Cursewrit Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Rare02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare02_Signature',
    localizedString: 'Cursewrit Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style05/Kyros_05_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare02_Gear1',
    localizedString: 'Cursewrit Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style05/Kyros_05_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare02_Gear2',
    localizedString: 'Cursewrit Cowl',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Style05/Kyros_05_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_UC02_Helm',
    localizedString: 'Enigmata Hood',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/UC02/Kyros_UC02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_UC02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_UC02_Body',
    localizedString: 'Enigmata Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_UC02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_UC02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_UC02_Signature',
    localizedString: 'Enigmata Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/UC02/Kyros_UC02_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_UC02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_UC02_Gear1',
    localizedString: 'Enigmata Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/UC02/Kyros_UC02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_UC02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_UC02_Gear2',
    localizedString: 'Enigmata Cover',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/UC02/Kyros_UC02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_UC02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare03_Helm',
    localizedString: 'Emptiness Hood',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Rare03/Kyros_Rare03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare03_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare03_Body',
    localizedString: 'Emptiness Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Rare03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare03_Signature',
    localizedString: 'Emptiness Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Rare03/Kyros_Rare03_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare03_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare03_Gear1',
    localizedString: 'Emptiness Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Rare03/Kyros_Rare03_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare03_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Rare03_Gear2',
    localizedString: 'Emptiness Cover',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Rare03/Kyros_Rare03_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Rare03_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic01_Helm',
    localizedString: 'Far Traveler Hat',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic01/Kyros_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic01_Body',
    localizedString: 'Far Traveler Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Epic01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic01_Signature',
    localizedString: 'Far Traveler Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic01/Kyros_Epic01_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic01_Gear1',
    localizedString: 'Far Traveler Bands',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic01/Kyros_Epic01_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic01_Gear2',
    localizedString: 'Far Traveler Cover',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic01/Kyros_Epic01_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic02_Helm',
    localizedString: 'Orphic Regalia Hood',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic02/Kyros_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic02_Body',
    localizedString: 'Orphic Regalia Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Epic02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic02_Signature',
    localizedString: 'Orphic Regalia Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic02/Kyros_Epic02_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic02_Gear1',
    localizedString: 'Orphic Regalia Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic02/Kyros_Epic02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic02_Gear2',
    localizedString: 'Orphic Regalia Cover',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic02/Kyros_Epic02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic03_Helm',
    localizedString: 'Anathema Head',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic03/Kyros_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic03_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic03_Body',
    localizedString: 'Anathema Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Epic03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic03_Signature',
    localizedString: 'Anathema Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic03/Kyros_Epic03_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic03_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic03_Gear1',
    localizedString: 'Anathema Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic03/Kyros_Epic03_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic03_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Epic03_Gear2',
    localizedString: 'Anathema Cover',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Epic03/Kyros_Epic03_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Epic03_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Legendary01_Helm',
    localizedString: 'Fathomless Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Legendary01/Kyros_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Legendary01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Legendary01_Body',
    localizedString: 'Fathomless Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Base_Legendary01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Legendary01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Legendary01_Signature',
    localizedString: 'Fathomless Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Legendary01/Kyros_Legendary01_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Legendary01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Legendary01_Gear1',
    localizedString: 'Fathomless Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Legendary01/Kyros_Legendary01_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Legendary01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Legendary01_Gear2',
    localizedString: 'Fathomless Cover',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Legendary01/Kyros_Legendary01_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Legendary01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Legendary02_Helm',
    localizedString: 'Shroudseer Mask',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Legendary02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Legendary02_Body',
    localizedString: 'Shroudseer Base',
    type: 'Persona',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Legendary02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Legendary02_Signature',
    localizedString: 'Shroudseer Belt',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Legendary02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Legendary02_Gear1',
    localizedString: 'Shroudseer Gloves',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Legendary02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Legendary02_Gear2',
    localizedString: 'Shroudseer Cover',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Legendary02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Base_Head02',
    localizedString: 'Hairstyle 02',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Hair_02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Base_Head02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Base_Head03',
    localizedString: 'Hairstyle 03',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Hair_03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Base_Head03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Base_Head04',
    localizedString: 'Hairstyle 04',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Hair_04',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Base_Head04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Kyros_Base_Head05',
    localizedString: 'Hairstyle 05',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Kyros_Hair_05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BattleMagePersonaItems.BattleMagePersonaItems'",
      rowName: 'Kyros_Base_Head05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
