import { INVENTORY_ITEM } from '../../structures/structures';

export const GRENDEL_PERSONAL_ITEMS: INVENTORY_ITEM[] = [
  {
    key: 'Grendel_Persona_02',
    localizedString: 'Primal Colossus',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_PrimalColossus',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Persona_02',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'Grendel_Persona_02_Base',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerPersonaGoldenWolf',
    localizedString: 'Sun Eater',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_GoldenWolf_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerPersonaGoldenWolf',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
        rowName: 'GoldenWolfBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerPersona',
    localizedString: 'The Berserker',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Beserker_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
        rowName: 'Armor_Grendel_Common_Helm',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
        rowName: 'Armor_Grendel_Common_Body',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
        rowName: 'Armor_Grendel_Common_Signature',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
        rowName: 'Armor_Grendel_Common_Gear1',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/GrendelArmorItems.GrendelArmorItems'",
        rowName: 'Armor_Grendel_Common_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerBase01',
    localizedString: 'The Berserker',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Persona_Beserker_Icon_Grendel',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerHelm01',
    localizedString: 'Berserker Head',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Icon-Grendel_Style01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerHelm01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerShoulders01',
    localizedString: 'Berserker Shoulders',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Icon-Grendel_Style01_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerShoulders01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerGear01',
    localizedString: 'Berserker Chest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Icon-Grendel_Style01_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerGear01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerGloves01',
    localizedString: 'Berserker Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Icon-Grendel_Style01_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerGloves01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerHelm02',
    localizedString: 'Bloodshorn Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_02/Icon-Grendel_Style02_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerHelm02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerShoulders02',
    localizedString: 'Bloodshorn Shoulders',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_02/Icon-Grendel_Style02_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerShoulders02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerGear02',
    localizedString: 'Bloodshorn Chest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_02/Icon-Grendel_Style02_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerGear02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerGloves02',
    localizedString: 'Bloodshorn Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_02/Icon-Grendel_Style02_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerGloves02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerHelm03',
    localizedString: 'Winterwar Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_03/Icon-Grendel_Style03_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerHelm03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerShoulders03',
    localizedString: 'Winterwar Shoulders',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_03/Icon-Grendel_Style03_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerShoulders03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerGear03',
    localizedString: 'Winterwar Chest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_03/Icon-Grendel_Style03_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerGear03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerGloves03',
    localizedString: 'Winterwar Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_03/Icon-Grendel_Style03_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerGloves03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerHelm04',
    localizedString: 'Shaelen Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_04/Icon-Grendel_Style04_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerHelm04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerShoulders04',
    localizedString: 'Shaelen Shoulders',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_04/Icon-Grendel_Style04_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerShoulders04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerGear04',
    localizedString: 'Shaelen Chest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_04/Icon-Grendel_Style04_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerGear04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerGloves04',
    localizedString: 'Shaelen Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_04/Icon-Grendel_Style_04_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerGloves04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerHelm05',
    localizedString: "Red Wolf's Helm",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_05/Icon-Grendel_Style05_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerHelm05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerShoulders05',
    localizedString: "Red Wolf's Shoulders",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_05/Icon-Grendel_Style05_Shoulder',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerShoulders05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerGear05',
    localizedString: "Red Wolf's Chest",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_05/Icon-Grendel_Style05_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerGear05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerGloves05',
    localizedString: "Red Wolf's Gloves",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_05/Icon-Grendel_Style05_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerGloves05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'GoldenWolfBase01',
    localizedString: 'Sun Eater',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Persona_GoldenWolf_Icon_Grendel',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'GoldenWolfBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerBase02',
    localizedString: 'Bloodshorn Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Rare02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerBase02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerBase03',
    localizedString: 'Winterwar Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Rare03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerBase03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerBase04',
    localizedString: 'Shaelen Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Rare01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerBase04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerBase05',
    localizedString: "Red Wolf's Base",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_UC02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerBase05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_UC01_Helm',
    localizedString: 'Reckoner Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/UC01/Grendel_UC01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_UC01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_UC01_Body',
    localizedString: 'Reckoner Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_UC01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_UC01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_UC01_Signature',
    localizedString: 'Reckoner Shoulders',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/UC01/Grendel_UC01_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_UC01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_UC01_Gear1',
    localizedString: 'Reckoner Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/UC01/Grendel_UC01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_UC01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_UC01_Gear2',
    localizedString: 'Reckoner Chest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/UC01/Grendel_UC01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_UC01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Persona_02_Base',
    localizedString: 'Primal Colossus',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_PrimalColossus',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Persona_02_Base',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_FC_Helm',
    localizedString: 'Grendel_FC_Helm',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_FC_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_FC_Body',
    localizedString: 'Grendel_FC_Body',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_FC_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_FC_Signature',
    localizedString: 'Grendel_FC_Signature',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_FC_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_FC_Gear1',
    localizedString: 'Grendel_FC_Gear1',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_FC_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_FC_Gear2',
    localizedString: 'Grendel_FC_Gear2',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_FC_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic01_Helm',
    localizedString: 'Dauntless Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic01/Grendel_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic01_Body',
    localizedString: 'Dauntless Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Epic01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic01_Signature',
    localizedString: 'Dauntless Shoulders',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic01/Grendel_Epic01_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic01_Gear1',
    localizedString: 'Dauntless Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic01/Grendel_Epic01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic01_Gear2',
    localizedString: 'Dauntless Chest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic01/Grendel_Epic01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic02_Helm',
    localizedString: 'Mazewar Veteran Patch',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic02/Grendel_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic02_Body',
    localizedString: 'Mazewar Veteran Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Epic02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic02_Signature',
    localizedString: 'Mazewar Veteran Shoulders',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic02/Grendel_Epic02_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic02_Gear1',
    localizedString: 'Mazewar Veteran Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic02/Grendel_Epic02_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic02_Gear2',
    localizedString: 'Mazewar Veteran Chest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic02/Grendel_Epic02_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic03_Helm',
    localizedString: 'Knightwar Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic03/Grendel_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic03_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic03_Body',
    localizedString: 'Knightwar Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Epic03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic03_Signature',
    localizedString: 'Knightwar Shoulders',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic03/Grendel_Epic03_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic03_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic03_Gear1',
    localizedString: 'Knightwar Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic03/Grendel_Epic03_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic03_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Epic03_Gear2',
    localizedString: 'Knightwar Chest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Epic03/Grendel_Epic03_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Epic03_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Legendary01_Helm',
    localizedString: 'Bonesaw Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Legendary01/Grendel_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Legendary01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Legendary01_Body',
    localizedString: 'Bonesaw Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Grendel_Legendary01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Legendary01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Legendary01_Signature',
    localizedString: 'Bonesaw Shoulders',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Legendary01/Grendel_Legendary01_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Legendary01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Legendary01_Gear1',
    localizedString: 'Bonesaw Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Legendary01/Grendel_Legendary01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Legendary01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Legendary01_Gear2',
    localizedString: 'Bonesaw Chest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Legendary01/Grendel_Legendary01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Legendary01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Legendary02_Helm',
    localizedString: 'Grendel_Legendary02_Helm',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Legendary02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Legendary02_Body',
    localizedString: 'Grendel_Legendary02_Body',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Legendary02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Legendary02_Signature',
    localizedString: 'Grendel_Legendary02_Signature',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Legendary02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Legendary02_Gear1',
    localizedString: 'Grendel_Legendary02_Gear1',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Legendary02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Grendel_Legendary02_Gear2',
    localizedString: 'Grendel_Legendary02_Gear2',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'Grendel_Legendary02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerHead01',
    localizedString: 'Hairstyle 01',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Icon-Grendel_Style01_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerHead01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerHead02',
    localizedString: 'Hairstyle 02',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Grendel_Hair02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerHead02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerHead03',
    localizedString: 'Hairstyle 03',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Grendel_Hair03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerHead03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerHead04',
    localizedString: 'Hairstyle 04',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Grendel_Hair04',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerHead04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'BerserkerHead05',
    localizedString: 'Hairstyle 05',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Style_01/Grendel_Hair05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/BerserkerPersonaItems.BerserkerPersonaItems'",
      rowName: 'BerserkerHead05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
