import { INVENTORY_ITEM } from '@/src/renderer/structures/structures';

export const CHARACTER_TRINKETS: INVENTORY_ITEM[] = [
  {
    key: 'Character_Trinket_001',
    localizedString: 'Celestial Stone',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_001',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_002',
    localizedString: 'Silver Singer',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_002',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_003',
    localizedString: 'Hook Blade',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_003',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_004',
    localizedString: 'Labyrinthian Knife',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_04',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_004',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_005',
    localizedString: "Milton's Shoe",
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_005',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_006',
    localizedString: 'Forgotten Voice',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_06',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_006',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_007',
    localizedString: 'Luck of the Sea',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_07',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_007',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_008',
    localizedString: 'Woodwen Eye',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_08',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_008',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_009',
    localizedString: 'Final Shot',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_09',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_009',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_010',
    localizedString: 'Guidance of Sol',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_10',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_010',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_011',
    localizedString: 'Favor of Fire',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_11',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_011',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_012',
    localizedString: "Stormcaller's Charm",
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_12',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_012',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_013',
    localizedString: "Ven's Morning Brew",
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_13',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_013',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_014',
    localizedString: 'Heartshaped Cham',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_14',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_014',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_015',
    localizedString: 'Lost Paw',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_15',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_015',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_016',
    localizedString: 'Foreign Glyph',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_016',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_016',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_017',
    localizedString: 'Rusty Star',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_17',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_017',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_018',
    localizedString: 'Fish Bone',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_18',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_018',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_019',
    localizedString: 'Great Blue',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_19',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_019',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_020',
    localizedString: 'Tiny Tankard',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_20',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_020',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_021',
    localizedString: 'Goblin Buddy',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_021',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_021',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_022',
    localizedString: 'Gourmet Slice',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_22',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_022',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_023',
    localizedString: 'Arcanic Compass',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_23',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_023',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_024',
    localizedString: 'Wayfinder Freshener',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_24',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_024',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_025',
    localizedString: 'Pocket Bomb',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_25',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_025',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_026',
    localizedString: "Avala's Brew",
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_26',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_026',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_027',
    localizedString: 'Eldren Sequencer',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_027',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_027',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_028',
    localizedString: 'Eldren Shadegate',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_028',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_028',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_029',
    localizedString: 'Shadeforge Cog',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_029',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_029',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_030',
    localizedString: 'Shadeforge Hammer',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_030',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_030',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_031',
    localizedString: 'Shadeforge Anvil',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_031',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_031',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_032',
    localizedString: "Gama's Purse",
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_032',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_032',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_033',
    localizedString: 'Patchwork Fool',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_033',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_033',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_034',
    localizedString: 'Three-Eye Teddy',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_034',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_034',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_035',
    localizedString: 'Sleigh Bells',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_035',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_035',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_036',
    localizedString: 'Eventide Bells',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_036',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_036',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_037',
    localizedString: 'Mini Avala',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_037',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_037',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_038',
    localizedString: 'Mini Ruby',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_038',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_038',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_039',
    localizedString: 'Mini Graymourn',
    type: 'Trinket',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_039',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_040',
    localizedString: 'Mini Huntmaster',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_040',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_040',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_041',
    localizedString: 'Mini Kestrel',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_041',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_041',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_042',
    localizedString: 'Mini Omen',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_042',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_042',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_043',
    localizedString: 'Mini Davyn',
    type: 'Trinket',
    icon: 'Icons/Equipment/Trinkets/RenderedOfficial/Trinket_043',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_043',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_044',
    localizedString: 'Mini Venge',
    type: 'Trinket',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_044',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_045',
    localizedString: 'Mini Trickster',
    type: 'Trinket',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_045',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_046',
    localizedString: 'Mini Warden Rust',
    type: 'Trinket',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_046',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_047',
    localizedString: 'Mini Corbin',
    type: 'Trinket',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_047',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Character_Trinket_048',
    localizedString: 'Mini Wolf',
    type: 'Trinket',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Character_Trinkets.Character_Trinkets'",
      rowName: 'Character_Trinket_048',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_10',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
