import { INVENTORY_ITEM } from '../../structures/structures';

export const WINGRAVE_PERSONAL_ITEMS: INVENTORY_ITEM[] = [
  {
    key: 'Wingrave_Core01_Style05',
    localizedString: 'Knight of the Throne',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_FC_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Core01_Style05',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterHelmet05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WingraveBase05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterShoulders05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGloves05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WarmasterGear05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WingravePersona_Samurai',
    localizedString: 'Shaelen Blade',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Wingrave_Samurai_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WingravePersona_Samurai',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'WingraveSamuraiBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WingravePersona_Templar',
    localizedString: 'Arcsworn Templar',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/TemplarPersona/Wingrave_Templar_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WingravePersona_Templar',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
        rowName: 'TemplarWingraveBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterPersona',
    localizedString: 'The Seeker',
    type: 'Persona',
    icon: 'Icons/Personas/Gladiator/Gladiator_Persona_02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
        rowName: 'Armor_Wingrave_Common_Helm',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
        rowName: 'Armor_Wingrave_Common_Body',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
        rowName: 'Armor_Wingrave_Common_Signature',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
        rowName: 'Armor_Wingrave_Common_Gear1',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/WingraveArmorItems.WingraveArmorItems'",
        rowName: 'Armor_Wingrave_Common_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterHead01',
    localizedString: 'Hairstyle 01',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Head_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterHead01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterHelmet01',
    localizedString: 'Seeker Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Shoulder_Helmet_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterHelmet01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterGear01',
    localizedString: 'Seeker Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Belt_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterGear01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterGloves01',
    localizedString: 'Seeker Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Gloves_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterGloves01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterShoulders01',
    localizedString: 'Seeker Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Shoulder_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterShoulders01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterHelmet02',
    localizedString: 'Imperial Vanguard Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style02/Wingrave_Helmet_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterHelmet02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterShoulders02',
    localizedString: 'Imperial Vanguard Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style02/Wingrave_Shoulder_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterShoulders02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterGear02',
    localizedString: 'Imperial Vanguard Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style02/Wingrave_Belt_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterGear02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterGloves02',
    localizedString: 'Imperial Vanguard Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style02/Wingrave_Gloves_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterGloves02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterHelmet03',
    localizedString: 'Archon Inquisitor Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style03/Wingrave_Helmet_S3',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterHelmet03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterShoulders03',
    localizedString: 'Archon Inquisitor Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style03/Wingrave_Shoulder_S3',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterShoulders03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterGear03',
    localizedString: 'Archon Inquisitor Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style03/Wingrave_Belt_S3',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterGear03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterGloves03',
    localizedString: 'Archon Inquisitor Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style03/Wingrave_Gloves_S3',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterGloves03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterHelmet04',
    localizedString: 'Skylight Warden Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style04/Wingrave_Helmet_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterHelmet04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterShoulders04',
    localizedString: 'Skylight Warden Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style04/Wingrave_Shoulder_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterShoulders04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterGear04',
    localizedString: 'Skylight Warden Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style04/Wingrave_Belt_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterGear04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterGloves04',
    localizedString: 'Skylight Warden Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style04/Wingrave_Gloves_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterGloves04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterHelmet05',
    localizedString: 'Knight of the Throne Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Helmet_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterHelmet05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterShoulders05',
    localizedString: 'Knight of the Throne Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Shoulder_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterShoulders05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterGear05',
    localizedString: 'Knight of the Throne Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Belt_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterGear05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WarmasterGloves05',
    localizedString: 'Knight of the Throne Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_Gloves_S5',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WarmasterGloves05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WingraveBase01',
    localizedString: 'Seeker Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Persona_Core1_Icon_Wingrave',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WingraveBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'TemplarWingraveBase01',
    localizedString: 'TemplarWingraveBase01',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/TemplarPersona/Wingrave_Templar_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'TemplarWingraveBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WingraveSamuraiBase01',
    localizedString: 'WingraveSamuraiBase01',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Persona_Samurai_Icon_Wingrave',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WingraveSamuraiBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WingraveBase02',
    localizedString: 'Imperial Vanguard Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style02/Wingrave_UC01_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WingraveBase02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WingraveBase03',
    localizedString: 'Archon Inquisitor Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style03/Wingrave_Rare01_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WingraveBase03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WingraveBase04',
    localizedString: 'Skylight Warden Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style04/Wingrave_Rare03_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WingraveBase04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'WingraveBase05',
    localizedString: 'Knight of the Throne Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style05/Wingrave_FC_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'WingraveBase05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_UC02_Helm',
    localizedString: 'Bannerlord Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/UC02/Wingrave_UC02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_UC02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_UC02_Body',
    localizedString: 'Bannerlord Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/UC02/Wingrave_UC02_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_UC02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_UC02_Signature',
    localizedString: 'Bannerlord Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/UC02/Wingrave_UC02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_UC02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_UC02_Gear1',
    localizedString: 'Bannerlord Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/UC02/Wingrave_UC02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_UC02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_UC02_Gear2',
    localizedString: 'Bannerlord Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/UC02/Wingrave_UC02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_UC02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Base_Head02',
    localizedString: 'Hairstyle 02',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Head_02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Base_Head02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Base_Head03',
    localizedString: 'Hairstyle 03',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Head_03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Base_Head03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Base_Head04',
    localizedString: 'Hairstyle 04',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Head_04',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Base_Head04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Base_Head05',
    localizedString: 'Hairstyle 05',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Style01/Wingrave_Head_05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Base_Head05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Rare02_Helm',
    localizedString: 'Legionnaire Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Rare02/Wingrave_Rare02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Rare02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Rare02_Body',
    localizedString: 'Legionnaire Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Rare02/Wingrave_Rare02_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Rare02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Rare02_Signature',
    localizedString: 'Legionnaire Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Rare02/Wingrave_Rare02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Rare02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Rare02_Gear1',
    localizedString: 'Legionnaire Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Rare02/Wingrave_Rare02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Rare02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Rare02_Gear2',
    localizedString: 'Legionnaire Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Rare02/Wingrave_Rare02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Rare02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic01_Helm',
    localizedString: 'Lightbearer Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic01/Wingrave_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic01_Body',
    localizedString: 'Lightbearer Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic01/Wingrave_Epic01_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic01_Signature',
    localizedString: 'Lightbearer Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic01/Wingrave_Epic01_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic01_Gear1',
    localizedString: 'Lightbearer Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic01/Wingrave_Epic01_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic01_Gear2',
    localizedString: 'Lightbearer Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic01/Wingrave_Epic01_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic02_Helm',
    localizedString: 'Biohazard Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic02/Wingrave_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic02_Body',
    localizedString: 'Biohazard Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic02/Wingrave_Epic02_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic02_Signature',
    localizedString: 'Biohazard Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic02/Wingrave_Epic02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic02_Gear1',
    localizedString: 'Biohazard Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic02/Wingrave_Epic02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic02_Gear2',
    localizedString: 'Biohazard Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic02/Wingrave_Epic02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic03_Helm',
    localizedString: 'Luminary Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic03/Wingrave_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic03_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic03_Body',
    localizedString: 'Luminary Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic03/Wingrave_Epic03_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic03_Signature',
    localizedString: 'Luminary Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic03/Wingrave_Epic03_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic03_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic03_Gear1',
    localizedString: 'Luminary Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic03/Wingrave_Epic03_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic03_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Epic03_Gear2',
    localizedString: 'Luminary Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Epic03/Wingrave_Epic03_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Epic03_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Lengendary01_Helm',
    localizedString: "Storm's End Helm",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary01/Wingrave_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Lengendary01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Lengendary01_Body',
    localizedString: "Storm's End Base",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary01/Wingrave_Legendary01_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Lengendary01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Lengendary01_Signature',
    localizedString: "Storm's End Pauldrons",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary01/Wingrave_Legendary01_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Lengendary01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Lengendary01_Gear1',
    localizedString: "Storm's End Gloves",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary01/Wingrave_Legendary01_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Lengendary01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Lengendary01_Gear2',
    localizedString: "Storm's End Sash",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary01/Wingrave_Legendary01_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Lengendary01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Lengendary02_Helm',
    localizedString: 'Vaelgard Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary02/Wingrave_Legendary02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Lengendary02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Lengendary02_Body',
    localizedString: 'Vaelgard Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary02/Wingrave_Legendary02_Base',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Lengendary02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Lengendary02_Signature',
    localizedString: 'Vaelgard Pauldrons',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary02/Wingrave_Legendary02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Lengendary02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Lengendary02_Gear1',
    localizedString: 'Vaelgard Gloves',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary02/Wingrave_Legendary02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Lengendary02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Wingrave_Lengendary02_Gear2',
    localizedString: 'Vaelgard Sash',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Legendary02/Wingrave_Legendary02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/CrusaderPersonaItems.CrusaderPersonaItems'",
      rowName: 'Wingrave_Lengendary02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
