import { INVENTORY_ITEM } from '../../structures/structures';

export const EVENTIDE_PERSONAL_ITEMS: INVENTORY_ITEM[] = [
  {
    key: 'EventideHatKyros',
    localizedString: 'Eventide Hat Kyros',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Kyros/Seasonal/Kyros_Head_Eventide',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Seasonal/Eventide/EventideCosmetics.EventideCosmetics'",
      rowName: 'EventideHatKyros',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideHatNiss',
    localizedString: 'Eventide Hat Niss',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Seasonal/Niss_Head_Eventide',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Seasonal/Eventide/EventideCosmetics.EventideCosmetics'",
      rowName: 'EventideHatNiss',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideHatSilo',
    localizedString: 'Eventide Hat Silo',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Seasonal/Silo_Head_Eventide',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Seasonal/Eventide/EventideCosmetics.EventideCosmetics'",
      rowName: 'EventideHatSilo',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideHatSenja',
    localizedString: 'Eventide Hat Senja',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Seasonal/Senja_Head_Eventide',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Seasonal/Eventide/EventideCosmetics.EventideCosmetics'",
      rowName: 'EventideHatSenja',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideHatWingrave',
    localizedString: 'Eventide Hat Wingrave',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Wingrave/Seasonal/Wingrave_Head_Eventide',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Seasonal/Eventide/EventideCosmetics.EventideCosmetics'",
      rowName: 'EventideHatWingrave',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideHatVenomess',
    localizedString: 'Eventide Hat Venomess',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Venomess/Seasonal/Venomess_Head_Eventide',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Seasonal/Eventide/EventideCosmetics.EventideCosmetics'",
      rowName: 'EventideHatVenomess',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'EventideHatGrendel',
    localizedString: 'Eventide Hat Grendel',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Grendel/Seasonal/Grendel_Head_Eventide',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Seasonal/Eventide/EventideCosmetics.EventideCosmetics'",
      rowName: 'EventideHatGrendel',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
