import { INVENTORY_ITEM } from '../../structures/structures';

export const SENJA_PERSONAL_ITEMS: INVENTORY_ITEM[] = [
  {
    key: 'Senja_Core01_Style03',
    localizedString: "Mourner's Mask",
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_FC_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Core01_Style03',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
        rowName: 'SenjaHelm03',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
        rowName: 'SenjaArm03',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
        rowName: 'SenjaBase03',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
        rowName: 'SenjaBoots03',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
        rowName: 'SenjaGear03',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaPersonaJester',
    localizedString: 'Masque Enforcer',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_Jester_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaPersonaJester',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
        rowName: 'SenjaJesterBase01',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
        rowName: 'SenjaJesterArm01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaPersonaMonster',
    localizedString: 'The Monster',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_Monster_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaPersonaMonster',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
        rowName: 'MonsterSenjaBase01',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
        rowName: 'MonsterSenjaArm01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'GladiatorPersona',
    localizedString: 'The Champion',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'GladiatorPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/SenjaArmorItems.SenjaArmorItems'",
        rowName: 'Armor_Senja_Common_Helm',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/SenjaArmorItems.SenjaArmorItems'",
        rowName: 'Armor_Senja_Common_Body',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/SenjaArmorItems.SenjaArmorItems'",
        rowName: 'Armor_Senja_Common_Signature',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/SenjaArmorItems.SenjaArmorItems'",
        rowName: 'Armor_Senja_Common_Gear1',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/SenjaArmorItems.SenjaArmorItems'",
        rowName: 'Armor_Senja_Common_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaHelm01',
    localizedString: 'Champion Cut',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style01/Senja01_Head-2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaHelm01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaHelm02',
    localizedString: 'Solstorm Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style02/Senja02_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaHelm02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaHelm04',
    localizedString: 'Hoplomachus Helm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style04/Senja_Helmet_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaHelm04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaGear01',
    localizedString: 'Champion Wraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style01/Senja01_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaGear01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaGear02',
    localizedString: 'Solstorm Wraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style02/Senja02_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaGear02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaGear04',
    localizedString: 'Hoplomachus Wraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style04/Senja_Belt_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaGear04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaArm01',
    localizedString: 'Champion Arm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style01/Senja01_Arm_Hand',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaArm01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaArm02',
    localizedString: 'Solstorm Caliber 8-O Arm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style02/Senja02_Arms_Hand',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaArm02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaArm03',
    localizedString: "Mourner's Mask Arm",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style03/Senja03_Arm_Hand',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaArm03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaArm04',
    localizedString: 'Hoplomachus Arm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style04/Senja_Gloves_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaArm04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaArm05',
    localizedString: 'Iron Sister Arm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style05/Senja05_Arm_Hand',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaArm05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaBoots01',
    localizedString: 'Champion Boots',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style01/Senja01_Boots',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaBoots01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaBoots02',
    localizedString: 'Solstorm Boots',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style02/Senja02_Boots',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaBoots02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaBoots03',
    localizedString: "Mourner's Mask Boots",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style03/Senja03_Boots',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaBoots03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaBoots04',
    localizedString: 'Hoplomachus Boots',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style04/Senja_Boots_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaBoots04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaHelm03',
    localizedString: "Mourner's Mask ",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style03/Senja03_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaHelm03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaGear03',
    localizedString: "Mourner's Mask Wraps",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style03/Senja03_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaGear03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaHelm05',
    localizedString: 'Iron Sister Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style05/Senja05_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaHelm05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaGear05',
    localizedString: 'Iron Sister Wraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style05/Senja05_Gear',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaGear05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaBoots05',
    localizedString: 'Iron Sister Boots',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style05/Senja05_Boots',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaBoots05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaHead01',
    localizedString: 'Hairstyle 01',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style01/Senja01_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaHead01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaBase01',
    localizedString: 'Champion Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Persona_Core1_Icon_Senja',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'MonsterSenjaBase01',
    localizedString: 'MonsterSenjaBase01',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_Monster_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'MonsterSenjaBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaJesterBase01',
    localizedString: 'SenjaJesterBase01',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Persona_Jester_Icon_Senja',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaJesterBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaBase05',
    localizedString: 'Iron Sister Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Persona_Core05_Icon_Senja',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaBase05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaBase03',
    localizedString: "Mourner's Mask Base",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_FC_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaBase03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaHead02',
    localizedString: 'Hairstyle 02',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style01/Senja01_Hair_02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaHead02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaHead03',
    localizedString: 'Hairstyle 03',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style01/Senja01_Hair_03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaHead03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaHead04',
    localizedString: 'Hairstyle 04',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style01/Senja01_Hair_04',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaHead04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SenjaHead05',
    localizedString: 'Hairstyle 05',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Style01/Senja01_Hair_05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'SenjaHead05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Rare01_Body',
    localizedString: 'Solstorm Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_Rare01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Rare01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Rare03_Body',
    localizedString: 'Hoplomachus Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_Rare03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Rare03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_UC02_Helm',
    localizedString: 'Zenith Rider Headpiece',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/UC02/Senja_UC02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_UC02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_UC02_Body',
    localizedString: 'Zenith Rider Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_UC02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_UC02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_UC02_Signature',
    localizedString: 'Zenith Rider Arm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/UC02/Senja_UC02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_UC02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_UC02_Gear1',
    localizedString: 'Zenith Rider Wraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/UC02/Senja_UC02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_UC02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_UC02_Gear2',
    localizedString: 'Zenith Rider Boots',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/UC02/Senja_UC02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_UC02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Rare02_Helm',
    localizedString: 'Stormpunk Goggles',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Rare02/Senja_Rare02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Rare02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Rare02_Body',
    localizedString: 'Stormpunk Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_Rare02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Rare02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Rare02_Signature',
    localizedString: 'Stormpunk Arm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Rare02/Senja_Rare02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Rare02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Rare02_Gear1',
    localizedString: 'Stormpunk Wraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Rare02/Senja_Rare02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Rare02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Rare02_Gear2',
    localizedString: 'Stormpunk Boots',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Rare02/Senja_Rare02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Rare02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic01_Helm',
    localizedString: 'Predator Headpiece',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic01/Senja_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic01_Body',
    localizedString: 'Predator Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_Epic01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic01_Signature',
    localizedString: 'Predator Arm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic01/Senja_Epic01_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic01_Gear1',
    localizedString: 'Predator Wraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic01/Senja_Epic01_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic01_Gear2',
    localizedString: 'Predator Boots',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic01/Senja_Epic01_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic02_Helm',
    localizedString: 'Iron Mother Cowl',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic02/Senja_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic02_Body',
    localizedString: 'Iron Mother Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_Epic02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic02_Signature',
    localizedString: 'Iron Mother Arm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic02/Senja_Epic02_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic02_Gear1',
    localizedString: 'Iron Mother Wraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic02/Senja_Epic02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic02_Gear2',
    localizedString: 'Iron Mother Boots',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic02/Senja_Epic02_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic03_Helm',
    localizedString: 'Deathblossom Headpiece',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic03/Senja_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic03_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic03_Body',
    localizedString: 'Deathblossom Base',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_Epic03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic03_Signature',
    localizedString: 'Deathblossom Arm',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic03/Senja_Epic03_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic03_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic03_Gear1',
    localizedString: 'Deathblossom Wraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic03/Senja_Epic03_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic03_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Epic03_Gear2',
    localizedString: 'Deathblossom Boots',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Epic03/Senja_Epic03_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Epic03_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Legendary01_Helm',
    localizedString: "Val'kyr Headpiece",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Legendary01/Senja_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Legendary01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Legendary01_Body',
    localizedString: "Val'kyr Base",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Senja_Legendary01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Legendary01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Legendary01_Signature',
    localizedString: "Val'kyr Arm",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Legendary01/Senja_Legendary01_Signature',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Legendary01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Legendary01_Gear1',
    localizedString: "Val'kyr Wraps",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Legendary01/Senja_Legendary01_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Legendary01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Legendary01_Gear2',
    localizedString: "Val'kyr Boots",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Senja/Legendary01/Senja_Legendary01_Gear02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Legendary01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Legendary02_Helm',
    localizedString: 'Stormrender Helm',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Legendary02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Legendary02_Body',
    localizedString: 'Stormrender Base',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Legendary02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Legendary02_Signature',
    localizedString: 'Stormrender Arm',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Legendary02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Legendary02_Gear1',
    localizedString: 'Stormrender Wraps',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Legendary02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Senja_Legendary02_Gear2',
    localizedString: 'Stormrender Boots',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/GladiatorPersonaItems.GladiatorPersonaItems'",
      rowName: 'Senja_Legendary02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
