import { INVENTORY_ITEM } from '../../structures/structures';

export const NISS_PERSONAL_ITEMS: INVENTORY_ITEM[] = [
  {
    key: 'Niss_Core01_Style05',
    localizedString: 'Shadow Nation',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_FC_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Core01_Style05',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'NissHelm05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'Niss_FC_Body',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'NissBelt05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'NissGear05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'NissPants05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissPersonaDjinn',
    localizedString: 'The Harmattan',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_Djinn_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissPersonaDjinn',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'NissDjinnBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissGoldenHydraPersona',
    localizedString: 'Astalyn Dancer',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Golden_Hydra/Niss_GoldenHydra_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissGoldenHydraPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
        rowName: 'GoldenHydraNissBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissPersona',
    localizedString: 'The Shadow Dancer',
    type: 'Persona',
    icon: 'Icons/Personas/Niss_Persona01/Niss_Persona01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/NissArmorItems.NissArmorItems'",
        rowName: 'Armor_Niss_Common_Helm',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/NissArmorItems.NissArmorItems'",
        rowName: 'Armor_Niss_Common_Body',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/NissArmorItems.NissArmorItems'",
        rowName: 'Armor_Niss_Common_Signature',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/NissArmorItems.NissArmorItems'",
        rowName: 'Armor_Niss_Common_Gear1',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/NissArmorItems.NissArmorItems'",
        rowName: 'Armor_Niss_Common_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissHead01',
    localizedString: 'Hairstyle 01',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style01/Niss_Head_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissHead01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissHelm01',
    localizedString: 'Shadow Dancer Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style01/Niss_Helmet_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissHelm01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissBelt01',
    localizedString: 'Shadow Dancer Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style01/Niss_Belt_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissBelt01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissGear01',
    localizedString: 'Shadow Dancer Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style01/Niss_Gloves_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissGear01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissPants01',
    localizedString: 'Shadow Dancer Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style01/Niss_Pants_S1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissPants01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissHelm02',
    localizedString: 'Shadeblood Hood',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style02/Niss_Helmet_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissHelm02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissPants02',
    localizedString: 'Shadeblood Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style02/Niss_Pants_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissPants02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissBelt02',
    localizedString: 'Shadeblood Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style02/Niss_Belt_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissBelt02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissGear02',
    localizedString: 'Shadeblood Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style02/Niss_Gloves_S2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissGear02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissHelm03',
    localizedString: 'Mercenary Collar',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style03/Niss_03_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissHelm03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissPants03',
    localizedString: 'Mercenary Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style03/Niss_03_Pa',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissPants03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissGear03',
    localizedString: 'Mercenary Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style03/Niss_03_Gloves',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissGear03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissBelt03',
    localizedString: 'Mercenary Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style03/Niss_03_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissBelt03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissPants04',
    localizedString: 'Matriarch Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style04/Niss_Pants_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissPants04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissBelt04',
    localizedString: 'Matriarch Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style04/Niss_Belt_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissBelt04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissGear04',
    localizedString: 'Matriarch Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style04/Niss_Gloves_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissGear04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissHelm04',
    localizedString: 'Matriarch Head Wrap',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style04/Niss_Helmet_S4',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissHelm04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissHelm05',
    localizedString: 'Shadow Nation Headpiece',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style05/Niss_05_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissHelm05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissPants05',
    localizedString: 'Shadow Nation Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style05/Niss_05_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissPants05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissBelt05',
    localizedString: 'Shadow Nation Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style05/Niss_05_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissBelt05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissGear05',
    localizedString: 'Shadow Nation Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style05/Niss_05_Arms',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissGear05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissBase01',
    localizedString: 'Shadow Dancer Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Persona_Core1_Icon_Niss',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'GoldenHydraNissBase01',
    localizedString: 'GoldenHydraNissBase01',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Golden_Hydra/Niss_GoldenHydra_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'GoldenHydraNissBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'NissDjinnBase01',
    localizedString: 'The Harmattan',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Persona_djinn_Icon_Niss',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'NissDjinnBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_UC02_Body',
    localizedString: 'Mercenary Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_UC02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_UC02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_FC_Body',
    localizedString: 'Shadow Nation Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_FC_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_FC_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Rare01_Body',
    localizedString: 'Matriarch Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_Rare01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Rare01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Rare03_Body',
    localizedString: 'Shadeblood Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_Rare03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Rare03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_UC01_Helm',
    localizedString: "Twilight's Edge Collar",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/UC01/Niss_UC01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_UC01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_UC01_Body',
    localizedString: "Twilight's Edge Base",
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_UC01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_UC01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_UC01_Signature',
    localizedString: "Twilight's Edge Belt",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/UC01/Niss_UC01_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_UC01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_UC01_Gear1',
    localizedString: "Twilight's Edge Gear",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/UC01/Niss_UC01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_UC01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_UC01_Gear2',
    localizedString: "Twilight's Edge Pants",
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/UC01/Niss_UC01_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_UC01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Rare02_Helm',
    localizedString: 'Scarlet Blade Collar',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Rare02/Niss_Rare02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Rare02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Rare02_Body',
    localizedString: 'Scarlet Blade Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_Rare02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Rare02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Rare02_Signature',
    localizedString: 'Scarlet Blade Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Rare02/Niss_Rare02_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Rare02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Rare02_Gear1',
    localizedString: 'Scarlet Blade Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Rare02/Niss_Rare02_Gear01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Rare02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Rare02_Gear2',
    localizedString: 'Scarlet Blade Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Rare02/Niss_Rare02_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Rare02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic01_Helm',
    localizedString: 'Unhallowed Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic01/Niss_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic01_Body',
    localizedString: 'Unhallowed Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_Epic01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic01_Signature',
    localizedString: 'Unhallowed Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic01/Niss_Epic01_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic01_Gear1',
    localizedString: 'Unhallowed Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic01/Niss_Epic01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic01_Gear2',
    localizedString: 'Unhallowed Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic01/Niss_Epic01_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic02_Helm',
    localizedString: 'Forlorn Blade Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic02/Niss_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic02_Body',
    localizedString: 'Forlorn Blade Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_Epic02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic02_Signature',
    localizedString: 'Forlorn Blade Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic02/Niss_Epic02_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic02_Gear1',
    localizedString: 'Forlorn Blade Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic02/Niss_Epic02_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic02_Gear2',
    localizedString: 'Forlorn Blade Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic02/Niss_Epic02_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic03_Helm',
    localizedString: 'Felhunter Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic03/Niss_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic03_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic03_Body',
    localizedString: 'Felhunter Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_Epic03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic03_Signature',
    localizedString: 'Felhunter Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic03/Niss_Epic03_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic03_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic03_Gear1',
    localizedString: 'Felhunter Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic03/Niss_Epic03_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic03_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Epic03_Gear2',
    localizedString: 'Felhunter Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Epic03/Niss_Epic03_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Epic03_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Legendary01_Helm',
    localizedString: 'Scorn Headpiece',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Legendary01/Niss_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Legendary01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Legendary01_Body',
    localizedString: 'Scorn Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_Legendary01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Legendary01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Legendary01_Signature',
    localizedString: 'Scorn Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Legendary01/Niss_Legendary01_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Legendary01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Legendary01_Gear1',
    localizedString: 'Scorn Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Legendary01/Niss_Legendary01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Legendary01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Legendary01_Gear2',
    localizedString: 'Scorn Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Legendary01/Niss_Legendary01_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Legendary01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Legendary02_Helm',
    localizedString: 'Shadesworn Mask',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Legendary02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Legendary02_Body',
    localizedString: 'Shadesworn Base',
    type: 'Persona',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Legendary02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Legendary02_Signature',
    localizedString: 'Shadesworn Belt',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Legendary02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Legendary02_Gear1',
    localizedString: 'Shadesworn Gear',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Legendary02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Legendary02_Gear2',
    localizedString: 'Shadesworn Pants',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Legendary02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Base_Head02',
    localizedString: 'Hairstyle 02',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style01/Niss_Hair_02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Base_Head02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Base_Head03',
    localizedString: 'Hairstyle 03',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style01/Niss_Hair_03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Base_Head03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Base_Head04',
    localizedString: 'Hairstyle 04',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style01/Niss_Hair_04',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Base_Head04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Base_Head05',
    localizedString: 'Hairstyle 05',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Style01/Niss_Hair_05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Base_Head05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Heroic_Helm',
    localizedString: 'Heroic Shadow Head',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Heroic/Niss_Heroic_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Heroic_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Heroic_Body',
    localizedString: 'Heroic Shadow Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Niss_Heroic_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Heroic_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Heroic_Signature',
    localizedString: 'Heroic Shadow Belt',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Heroic/Niss_Heroic_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Heroic_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Heroic_Gear1',
    localizedString: 'Heroic Shadow Gear',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Heroic/Niss_Heroic_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Heroic_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Niss_Heroic_Gear2',
    localizedString: 'Heroic Shadow Pants',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Niss/Heroic/Niss_Heroic_Pants',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/NissPersonaItems.NissPersonaItems'",
      rowName: 'Niss_Heroic_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
