import { INVENTORY_ITEM } from '../../structures/structures';

export const SILO_PERSONAL_ITEMS: INVENTORY_ITEM[] = [
  {
    key: 'Silo_Core01_Style05',
    localizedString: 'Firestarter',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_FC_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Core01_Style05',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloHelm05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'Silo_FC_Body',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloGear05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloChest05',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloBackPack05',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: false,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloPersonaFlame',
    localizedString: 'Firebrand',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Flame_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloPersonaFlame',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'SiloBaseFlame01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloPersonaResearcher',
    localizedString: 'The Machinist',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Researcher/Silo_Researcher_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloPersonaResearcher',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
        rowName: 'ResearcherSiloBase01',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'TacticianPersona',
    localizedString: 'Tactician',
    type: 'Persona',
    icon: 'Icons/Personas/Tactician/Tactician_Persona_00',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'TacticianPersona',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
        rowName: 'Armor_Silo_Common_Helm',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
        rowName: 'Armor_Silo_Common_Body',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
        rowName: 'Armor_Silo_Common_Signature',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
        rowName: 'Armor_Silo_Common_Gear1',
      },
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/ArmorItems/SiloArmorItems.SiloArmorItems'",
        rowName: 'Armor_Silo_Common_Gear2',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::PERSONA',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloHelm01',
    localizedString: 'Tactician Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Style_01_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloHelm01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloBackPack01',
    localizedString: 'Tactician Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Style_01_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloBackPack01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloChest01',
    localizedString: 'Tactician Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Style01_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloChest01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloGear01',
    localizedString: 'Tactician Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Style_01_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloGear01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloHelm02',
    localizedString: 'Smuggler Head',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo02/Silo_Style_02_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloHelm02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloChest02',
    localizedString: 'Smuggler Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo02/Silo_Style02_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloChest02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloBackPack02',
    localizedString: 'Smuggler Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo02/Silo_Style_02_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloBackPack02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloGear02',
    localizedString: 'Smuggler Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo02/Silo_Style_02_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloGear02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloHelm03',
    localizedString: 'Scavenge Runner Monoptics',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo03/Silo_Style_03_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloHelm03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloChest03',
    localizedString: 'Scavenge Runner Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo03/Silo_Style03_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloChest03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloBackPack03',
    localizedString: 'Scavenge Runner Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo03/Silo_Style_03_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloBackPack03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloGear03',
    localizedString: 'Scavenge Runner Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo03/Silo_Style_03_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloGear03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloHelm04',
    localizedString: 'Scoundrel Headwraps',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo04/Silo_Style_04_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloHelm04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloChest04',
    localizedString: 'Scoundrel Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo04/Silo_Style04_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloChest04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloBackPack04',
    localizedString: 'Scoundrel Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo04/Silo_Style_04_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloBackPack04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloGear04',
    localizedString: 'Scoundrel Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo04/Silo_Style_04_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloGear04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloHelm05',
    localizedString: 'Firestarter Hood',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style_05_Head',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloHelm05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloChest05',
    localizedString: 'Firestarter Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style05_Chest',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloChest05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloBackPack05',
    localizedString: 'Firestarter Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style_05_BackPack',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloBackPack05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloGear05',
    localizedString: 'Firestarter Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo05/Silo_Style_05_Belt',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloGear05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloBase01',
    localizedString: 'Tactician Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Persona_Core1_Icon_Silo',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'ResearcherSiloBase01',
    localizedString: 'ResearcherSiloBase01',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Persona_Researcher_Icon_Silo',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'ResearcherSiloBase01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloBaseFlame01',
    localizedString: 'SiloBaseFlame01',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Flame_PersonaIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloBaseFlame01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_UC01_Body',
    localizedString: 'Smuggler Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_UC01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_UC01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_UC02_Body',
    localizedString: 'Scavenge Runner Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_UC02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_UC02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_FC_Body',
    localizedString: 'Firestarter Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_FC_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_FC_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare01_Body',
    localizedString: 'Scoundrel Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Rare01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare02_Helm',
    localizedString: 'Mayhem Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare02/Silo_Rare02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare02_Body',
    localizedString: 'Mayhem Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Rare02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare02_Signature',
    localizedString: 'Mayhem Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare02/Silo_Rare02_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare02_Gear1',
    localizedString: 'Mayhem Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare02/Silo_Rare02_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare02_Gear2',
    localizedString: 'Mayhem Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare02/Silo_Rare02_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare03_Helm',
    localizedString: 'Streetwise Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare03/Silo_Rare03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare03_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare03_Body',
    localizedString: 'Streetwise Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Rare03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare03_Signature',
    localizedString: 'Streetwise Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare03/Silo_Rare03_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare03_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare03_Gear1',
    localizedString: 'Streetwise Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare03/Silo_Rare03_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare03_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Rare03_Gear2',
    localizedString: 'Streetwise Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Rare03/Silo_Rare03_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Rare03_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic01_Helm',
    localizedString: 'Bloodrunner Mask',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic01/Silo_Epic01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic01_Body',
    localizedString: 'Bloodrunner Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Epic01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic01_Signature',
    localizedString: 'Bloodrunner Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic01/Silo_Epic01_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic01_Gear1',
    localizedString: 'Bloodrunner Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic01/Silo_Epic01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic01_Gear2',
    localizedString: 'Bloodrunner Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic01/Silo_Epic01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic02_Helm',
    localizedString: 'Cindershot Headpiece',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic02/Silo_Epic02_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic02_Body',
    localizedString: 'Cindershot Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Epic02_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic02_Signature',
    localizedString: 'Cindershot Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic02/Silo_Epic02_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic02_Gear1',
    localizedString: 'Cindershot Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic02/Silo_Epic02_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic02_Gear2',
    localizedString: 'Cindershot Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic02/Silo_Epic02_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic03_Helm',
    localizedString: 'Hazard Pay Eyepatch',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic03/Silo_Epic03_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic03_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic03_Body',
    localizedString: 'Hazard Pay Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Epic03_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic03_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic03_Signature',
    localizedString: 'Hazard Pay Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic03/Silo_Epic03_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic03_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic03_Gear1',
    localizedString: 'Hazard Pay Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic03/Silo_Epic03_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic03_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Epic03_Gear2',
    localizedString: 'Hazard Pay Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Epic03/Silo_Epic03_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Epic03_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Legendary01_Helm',
    localizedString: 'Malevolence Head',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Legendary01/Silo_Legendary01_Helm',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Legendary01_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Legendary01_Body',
    localizedString: 'Malevolence Base',
    type: 'Persona',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo_Legendary01_Fullbody',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Legendary01_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Legendary01_Signature',
    localizedString: 'Malevolence Pack',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Legendary01/Silo_Legendary01_Sig',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Legendary01_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Legendary01_Gear1',
    localizedString: 'Malevolence Vest',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Legendary01/Silo_Legendary01_Gear1',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Legendary01_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Legendary01_Gear2',
    localizedString: 'Malevolence Bag',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Legendary01/Silo_Legendary01_Gear2',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Legendary01_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Legendary02_Helm',
    localizedString: 'Gloomhacker Mask',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Legendary02_Helm',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Legendary02_Body',
    localizedString: 'Gloomhacker Base',
    type: 'Persona',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Legendary02_Body',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_2',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Legendary02_Signature',
    localizedString: 'Gloomhacker Pack',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Legendary02_Signature',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_3',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Legendary02_Gear1',
    localizedString: 'Gloomhacker Vest',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Legendary02_Gear1',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_4',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Silo_Legendary02_Gear2',
    localizedString: 'Gloomhacker Bag',
    type: 'Style',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'Silo_Legendary02_Gear2',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_5',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloHead01',
    localizedString: 'Hairstyle 01',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Hair_01',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloHead01',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloHead02',
    localizedString: 'Hairstyle 02',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Hair_02',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloHead02',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloHead03',
    localizedString: 'Hairstyle 03',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Hair_03',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloHead03',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloHead04',
    localizedString: 'Hairstyle 04',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Hair_04',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloHead04',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SiloHead05',
    localizedString: 'Hairstyle 05',
    type: 'Style',
    icon: 'Icons/Personas/RenderedOfficial/Silo/Silo01/Silo_Hair_05',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/TacticianPersonaItems.TacticianPersonaItems'",
      rowName: 'SiloHead05',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_1',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
