import { INVENTORY_ITEM } from '../../structures/structures';

export const WEAPON_CHARMS: INVENTORY_ITEM[] = [
  {
    key: 'Weapon_Charm_001',
    localizedString: 'Flail Buddy',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_001',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_001',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_002',
    localizedString: 'Wrecking Ball',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_002',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_002',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_003',
    localizedString: 'Ominous Totem',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_003',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_003',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_004',
    localizedString: 'Token of The Three',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_004',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_004',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_005',
    localizedString: 'Thick Skull',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_005',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_005',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_006',
    localizedString: 'Attachable Bomb',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_006',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_006',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_007',
    localizedString: "Shrike 'Nade",
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_007',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_007',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_008',
    localizedString: 'Miniature Kyros',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_008',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_008',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_009',
    localizedString: 'Little Lantern',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_009',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_009',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_010',
    localizedString: 'Practice Doll',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_010',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_010',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_011',
    localizedString: 'Ouroboros',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_011',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_011',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_012',
    localizedString: 'DreamCatch',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_12',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_012',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_013',
    localizedString: 'Bone Chime',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_013',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_013',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_014',
    localizedString: 'Old Bell',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_014',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_014',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_015',
    localizedString: 'Sharp Tooth',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_015',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_015',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_016',
    localizedString: 'Lil Hammer',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_016',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_016',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_017',
    localizedString: 'Reaper',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_017',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_017',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_019',
    localizedString: 'Drinking Horn',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_019',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_019',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_020',
    localizedString: 'Hardcore Heart',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_020',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_020',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_021',
    localizedString: 'Manic Buddy',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_021',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_021',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_022',
    localizedString: 'Lil Legion',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_022',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_022',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_023',
    localizedString: 'Armored Tendrils',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_023',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_023',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_024',
    localizedString: "Duskhunter's Fang",
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_024',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_024',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_025',
    localizedString: 'Bone Shard',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_025',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_025',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_026',
    localizedString: 'Regal Tassles',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_026',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_026',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_027',
    localizedString: 'Aurelian Atlas',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_027',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_027',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_030',
    localizedString: 'D20',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_030',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_030',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_034',
    localizedString: 'Lunaire',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_034',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_034',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_035',
    localizedString: 'Crystal Abacus',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_035',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_035',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_036',
    localizedString: 'Undercroft Key',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_036',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_036',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_037',
    localizedString: 'Primal Key',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_037',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_037',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_038',
    localizedString: 'Incense Urn',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_038',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_038',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_039',
    localizedString: 'Arclight Atlas',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_039',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_039',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_040',
    localizedString: 'Solstone',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_040',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_040',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_041',
    localizedString: 'Silver Anchor',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_041',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_041',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_042',
    localizedString: 'Pirate Badge',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_042',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_042',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_043',
    localizedString: 'Spectral Lantern',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_043',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_043',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_044',
    localizedString: 'Metal Bell',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_044',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_044',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_045',
    localizedString: 'Arclight Compass',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_045',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_045',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_046',
    localizedString: 'Cog',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_046',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_046',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_047',
    localizedString: 'Airship',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_047',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_047',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_048',
    localizedString: 'Valetouched Bell',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_048',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_048',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Weapon_Charm_049',
    localizedString: 'Emblem of the Cog',
    type: 'Charm',
    icon: 'Icons/Equipment/Charms/RenderedOfficial/Charm_49',
    data: {
      dataTable:
        "DataTable'/Game/Data/Inventory/Cosmetics/Weapon_Charms.Weapon_Charms'",
      rowName: 'Weapon_Charm_049',
    },
    addItemsWhenCreated: [],
    equipmentSlot: 'EEquipmentSlotType::COSMETIC_20',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: false,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
