export const TwoHandedAxe = [
  {
    key: 'Axe_2H_001_Item',
    localizedString: 'Typhoon',
    type: 'TwoHandedAxe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HAxe/ui_icon_rendered_weapon_2HAxe_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/AxeItems.AxeItems'",
      rowName: 'Axe_2H_001_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/AxePersonas.AxePersonas'",
        rowName: 'Axe_2H_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Axe_2H_002_Item',
    localizedString: 'Eclipse',
    type: 'TwoHandedAxe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HAxe/ui_icon_rendered_weapon_2HAxe_002',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/AxeItems.AxeItems'",
      rowName: 'Axe_2H_002_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/AxePersonas.AxePersonas'",
        rowName: 'Axe_2H_002',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Axe_2H_003_Item',
    localizedString: 'Draken Maw',
    type: 'TwoHandedAxe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HAxe/003',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/AxeItems.AxeItems'",
      rowName: 'Axe_2H_003_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/AxePersonas.AxePersonas'",
        rowName: 'Axe_2H_003',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
