export const TwoHandedScythes = [
  {
    key: '2HScythe_001_Item',
    localizedString: 'Epitaph',
    type: 'TwoHandedScythe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Scythe/ui_icon_rendered_weapon_2HScythe_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HScytheItems.2HScytheItems'",
      rowName: '2HScythe_001_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HScythePersonas.2HScythePersonas'",
        rowName: '2HScythe_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HScythe_002_Item',
    localizedString: 'Bloodsong',
    type: 'TwoHandedScythe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Scythe/ui_icon_rendered_weapon_2HScythe_002',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HScytheItems.2HScytheItems'",
      rowName: '2HScythe_002_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HScythePersonas.2HScythePersonas'",
        rowName: '2HScythe_002',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HScythe_003_Item',
    localizedString: 'Blight',
    type: 'TwoHandedScythe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Scythe/ui_icon_rendered_weapon_2HScythe_003',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HScytheItems.2HScytheItems'",
      rowName: '2HScythe_003_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HScythePersonas.2HScythePersonas'",
        rowName: '2HScythe_003',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HScythe_005_Item',
    localizedString: "Queen's Pyre",
    type: 'TwoHandedScythe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Scythe/2hScythe_005',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HScytheItems.2HScytheItems'",
      rowName: '2HScythe_005_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HScythePersonas.2HScythePersonas'",
        rowName: '2HScythe_005',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
