export const TwoHandedSwords = [
  {
    key: '2HSword_001_Item',
    localizedString: 'Colossus',
    type: 'TwoHandedSword',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Sword/ui_icon_rendered_weapon_2HSword_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HSwordItems.2HSwordItems'",
      rowName: '2HSword_001_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HSwordPersonas.2HSwordPersonas'",
        rowName: '2HSword_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HSword_007_Item',
    localizedString: "Titan's Bane",
    type: 'TwoHandedSword',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Sword/007',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HSwordItems.2HSwordItems'",
      rowName: '2HSword_007_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HSwordPersonas.2HSwordPersonas'",
        rowName: '2HSword_007',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HSword_009_Item',
    localizedString: "Windmother's Fang",
    type: 'TwoHandedSword',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Sword/ui_icon_rendered_weapon_2HSword_009',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HSwordItems.2HSwordItems'",
      rowName: '2HSword_009_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HSwordPersonas.2HSwordPersonas'",
        rowName: '2HSword_009',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HSword_013_Item',
    localizedString: 'Portent',
    type: 'TwoHandedSword',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Sword/2hSword_013',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HSwordItems.2HSwordItems'",
      rowName: '2HSword_013_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HSwordPersonas.2HSwordPersonas'",
        rowName: '2HSword_013',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HSword_014_Item',
    localizedString: 'Bloodthirst',
    type: 'TwoHandedSword',
    icon: 'Icons/Equipment/Weapons/WF_Icon_Weapon_Missing',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HSwordItems.2HSwordItems'",
      rowName: '2HSword_014_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HSwordPersonas.2HSwordPersonas'",
        rowName: '2HSword_014',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
