export const DualWieldDaggers = [
  {
    key: 'DW_Starter_Item',
    localizedString: 'Slicer & Dicer',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_004',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_Starter_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'A traditional weapon of the Shrike smugglers, as sharp as the talons of their namesake ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_Daggers_Starter',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_005_Item',
    localizedString: 'Venom',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_005',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_005_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Once wielded by Renvi the Rotted, the poisoned blades known as Venom were feared by any who dared cross the Eldren of the Viridescent Woods A single prick might spell your end',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_005',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_008_Item',
    localizedString: 'Rose & Thorn',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_008',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_008_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'As deadly as they are beautiful, these weapons were once wielded by the legendary Blade Dancer of the Golden Aerie Blood sustains the flowering petals',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_008',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_012_Item',
    localizedString: "Maiden's Rime",
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_012',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_012_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Carved from the heart of a Frost Vassal, these blades seem little more than brittle icicles to the uninitiated The Handmaidens of Frostmarch once kept these blades as deterrants, scarring any foolish enough to harm their charge with cuts of hoarfrost ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_012',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_013_Item',
    localizedString: 'Harvest Moon',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_013',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_013_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The Silver Codexs earliest excavations in Aurelien uncovered peculiar structures dedicated to the study of the night sky Buried within those ruins was the artifact now known as Harvest Moon',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_013',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_014_Item',
    localizedString: 'Umbros',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_014',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_014_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The Vault of Ascension held many gifts bestowed upon the Kingdoms denizens Though its creators fell, the blades of Umbros empowered the greatest champions of the Kingdom Until, of course, the great empire crumbled to ash',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_014',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_015_Item',
    localizedString: "Night's Edge",
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_015',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_015_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The ancestral blades of the Deep Eldren The spirits of the fallen are bound to these daggers, and strike out at the enemies of a worthy wielder ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_015',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_019_Item',
    localizedString: 'God Bleeder',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/DW_019',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_019_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'In his final days of captivity, the Rook engineered a menagerie of deadly weapons for the Raven and her Shrikes They were not enough to earn his life',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_019',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_021_Item',
    localizedString: 'DNT (Teryssa Dagger)',
    type: 'DualWieldDaggers',
    icon: 'Icons/T_UI_MissingTextureIcon',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_021_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The echo of a legendary weapon lost to time Use this item to reshape the appearance of your weapon ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_021',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
