export const TwoHandedMace = [
  {
    key: '2H_Mace_003_Item',
    localizedString: 'Doldrum',
    type: 'TwoHandedMace',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HMace/ui_icon_rendered_weapon_2HMace_003',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/MaceItems.MaceItems'",
      rowName: '2H_Mace_003_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Though the name of this weapon was lost to the ages, the Woodwen people never forgot the great Gift of Graal',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/MacePersonas.MacePersonas'",
        rowName: '2H_Mace_003',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2H_Mace_006_Item',
    localizedString: 'Juggernaut',
    type: 'TwoHandedMace',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HMace/ui_icon_rendered_weapon_2HMace_006',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/MaceItems.MaceItems'",
      rowName: '2H_Mace_006_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Forged for the Balgrim Shaarakuul in the Halls Below, the Juggernaut was claimed as spoils of war by the Archon Halavant Few can withstand its crushing blows ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/MacePersonas.MacePersonas'",
        rowName: '2H_Mace_006',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
