export const TwoHandedRifle = [
  {
    key: '2HR_Starter_Item',
    localizedString: 'Ransom',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/008',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_Starter_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The infamous highwayman Duskyn Dodge was the first to carry Ransom Its had many wielders since thenscoundrels, every one ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_Starter',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_003_Item',
    localizedString: 'Arcstorm',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/ui_icon_rendered_weapon_2HRifle_003',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_003_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'At the height of the Twilight Heresy, the Archon Astalis ordered the Spellforge to create an arcanic plasma projector of unparalleled power Arcstorm cost more than entire legion, but it served Astalis well in his final battle against the Shadowbringers   ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_003',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_004_Item',
    localizedString: 'Hellswarm',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/ui_icon_rendered_weapon_2HRifle_004',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_004_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The champions of the Maze prefer close range brutality to finesse The Hellswarm unleashes devastating blasts that rip through enemy squads  ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_004',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_006_Item',
    localizedString: 'Longshot',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/ui_icon_rendered_weapon_2HRifle_006',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_006_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Longshot was built by Salan Vex, the first Shrike He won a fortune from the Avar Reeve in a highstakes shooting contest, and used this gold to found his network of smugglers ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_006',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_007_Item',
    localizedString: 'Nightshade',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/007',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_007_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The Venomess designed many weapons for the Maze, but Nightshade she made for herself Its needles are infused with the venom of the Orlake Wyvern, ensuring a swift and painful demise  ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_007',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_009_Item',
    localizedString: 'Tempest',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/009',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_009_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Tempests origins are a mystery, but its power is undeniable  ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_009',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_012_Item',
    localizedString: 'Duskbringer',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/ui_icon_rendered_weapon_2HRifle_012',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_012_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'A terrifying creation of the Deep Eldren, the Duskbringer uses the power of the Gloom to tear reality apart  ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_012',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_013_Item',
    localizedString: 'Voidbinder',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/ui_icon_rendered_weapon_2HRifle_013',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_013_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Scarcely did the Imperial Spellforge call on the expertise of an Arcane Lord, but in a fleeting alliance held between the Avar Throne and the Dominion, House Tarroken instructed the spellsmiths how to bind life itself with Shadow',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_013',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HShotgun_001_Item',
    localizedString: 'Covetous',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/2hShotgun_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HShotgun_001_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description: 'Covetous are those who hold walk the gilded path',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HShotgun_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HRune_001_Item',
    localizedString: 'Vesper-III',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/2hRune_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HRune_001_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'A mechanical marvel malformed within the Gloom The battery of this weapon is sustained by consuming the Architects creation',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HRune_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HRune_002_Item',
    localizedString: 'Requiem',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/2hRune_002',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HRune_002_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Formed in our moment of victory within the Beacon, Omens sacrifice has bound this last shadow to serve the Seekers cause',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HRune_002',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
