export const SwordAndShield = [
  {
    key: 'SnS_Starter_Item',
    localizedString: 'Vanguard',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_015',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_Starter_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Forged by the legendary smith Torlyn Irontongue His smithy was razed in the Mazewars, but his legacy remains in this mighty weapon  ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_Starter',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_002_Item',
    localizedString: 'Dryades',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_002',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_002_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The Grove of Thorns takes the metals of the earth and grows armaments great enough to match those of any forge The Groves works are said to be guided by the spirits of the ancient smiths of the forest Eldren',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_002',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_003_Item',
    localizedString: 'Grim Harvest',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_003',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_003_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Throughout history, every champion whos carried Grim Harvest has died a gruesome deathbut only after vanquishing their enemies Who will be the next to fall prey to this curse ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_003',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_005_Item',
    localizedString: 'Tooth and Claw',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_005',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_005_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'Forged for a champion of the Maze, Tooth and Claw carved a bloody path through the Avar frontier It hungers for battle ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_005',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_006_Item',
    localizedString: 'Gallant Bulwark',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_006',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_006_Item',
    },
    echoData: { type: 'EFogSoulCategory::Invalid', soulBudgetCost: 'None' },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_006',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_007_Item',
    localizedString: 'Legacy',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_007',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_007_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'This ancient weapon was forged in the dawn of the world, before humanity existed It was made for Eldren hands, and it burns with eternal light ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_007',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_009_Item',
    localizedString: 'Bastion',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_009',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_009_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The names of the Celestial Architects are woven into the steel, and a champion with faith can still call on their light ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_009',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_010_Item',
    localizedString: 'DNT Lora Signature',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_010',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_010_Item',
    },
    echoData: { type: 'EFogSoulCategory::Invalid', soulBudgetCost: 'None' },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_010',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_016_Item',
    localizedString: 'Radiant Dawn',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_016',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_016_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The tools of the first Archon Inquisitor The blade was forged to strike down evil, the shield to protect the innocent from harm ',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_016',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_021_Item',
    localizedString: 'Warp & Weft',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_021',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_021_Item',
    },
    echoData: {
      type: 'EFogSoulCategory::Invalid',
      description:
        'The Architects children built them a network of arcanic wonders to weave together the threads of creation When they were betrayed, they vowed to unravel what remained',
      soulBudgetCost: 'None',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_021',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
