import { INVENTORY_ITEM } from '@/src/renderer/structures/structures';

const TwoHScytheItems: INVENTORY_ITEM[] = [
  {
    key: '2HScythe_001_Item',
    localizedString: 'Epitaph',
    type: 'TwoHandedScythe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Scythe/ui_icon_rendered_weapon_2HScythe_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HScytheItems.2HScytheItems'",
      rowName: '2HScythe_001_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HScythePersonas.2HScythePersonas'",
        rowName: '2HScythe_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HScythe_002_Item',
    localizedString: 'Bloodsong',
    type: 'TwoHandedScythe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Scythe/ui_icon_rendered_weapon_2HScythe_002',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HScytheItems.2HScytheItems'",
      rowName: '2HScythe_002_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HScythePersonas.2HScythePersonas'",
        rowName: '2HScythe_002',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HScythe_003_Item',
    localizedString: 'Blight',
    type: 'TwoHandedScythe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Scythe/ui_icon_rendered_weapon_2HScythe_003',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HScytheItems.2HScytheItems'",
      rowName: '2HScythe_003_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HScythePersonas.2HScythePersonas'",
        rowName: '2HScythe_003',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HScythe_005_Item',
    localizedString: "Queen's Pyre",
    type: 'TwoHandedScythe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Scythe/2hScythe_005',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HScytheItems.2HScytheItems'",
      rowName: '2HScythe_005_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HScythePersonas.2HScythePersonas'",
        rowName: '2HScythe_005',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
const TwoHSwordItems: INVENTORY_ITEM[] = [
  {
    key: '2HSword_001_Item',
    localizedString: 'Colossus',
    type: 'TwoHandedSword',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Sword/ui_icon_rendered_weapon_2HSword_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HSwordItems.2HSwordItems'",
      rowName: '2HSword_001_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HSwordPersonas.2HSwordPersonas'",
        rowName: '2HSword_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HSword_007_Item',
    localizedString: "Titan's Bane",
    type: 'TwoHandedSword',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Sword/007',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HSwordItems.2HSwordItems'",
      rowName: '2HSword_007_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HSwordPersonas.2HSwordPersonas'",
        rowName: '2HSword_007',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HSword_009_Item',
    localizedString: "Windmother's Fang",
    type: 'TwoHandedSword',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Sword/ui_icon_rendered_weapon_2HSword_009',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HSwordItems.2HSwordItems'",
      rowName: '2HSword_009_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HSwordPersonas.2HSwordPersonas'",
        rowName: '2HSword_009',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HSword_013_Item',
    localizedString: 'Portent',
    type: 'TwoHandedSword',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Sword/2hSword_013',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HSwordItems.2HSwordItems'",
      rowName: '2HSword_013_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HSwordPersonas.2HSwordPersonas'",
        rowName: '2HSword_013',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HSword_014_Item',
    localizedString: 'Bloodthirst',
    type: 'TwoHandedSword',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2H_Sword/Icon_Weapon_2hSword_014',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/2HSwordItems.2HSwordItems'",
      rowName: '2HSword_014_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/2HSwordPersonas.2HSwordPersonas'",
        rowName: '2HSword_014',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
const AxeItems: INVENTORY_ITEM[] = [
  {
    key: 'Axe_2H_001_Item',
    localizedString: 'Typhoon',
    type: 'TwoHandedAxe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HAxe/ui_icon_rendered_weapon_2HAxe_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/AxeItems.AxeItems'",
      rowName: 'Axe_2H_001_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/AxePersonas.AxePersonas'",
        rowName: 'Axe_2H_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Axe_2H_002_Item',
    localizedString: 'Eclipse',
    type: 'TwoHandedAxe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HAxe/ui_icon_rendered_weapon_2HAxe_002',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/AxeItems.AxeItems'",
      rowName: 'Axe_2H_002_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/AxePersonas.AxePersonas'",
        rowName: 'Axe_2H_002',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'Axe_2H_003_Item',
    localizedString: 'Draken Maw',
    type: 'TwoHandedAxe',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HAxe/003',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/AxeItems.AxeItems'",
      rowName: 'Axe_2H_003_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/AxePersonas.AxePersonas'",
        rowName: 'Axe_2H_003',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
const DWItems: INVENTORY_ITEM[] = [
  {
    key: 'DW_Starter_Item',
    localizedString: 'Slicer & Dicer',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_004',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_Starter_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_Daggers_Starter',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_005_Item',
    localizedString: 'Venom',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_005',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_005_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_005',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_008_Item',
    localizedString: 'Rose & Thorn',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_008',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_008_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_008',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_012_Item',
    localizedString: "Maiden's Rime",
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_012',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_012_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_012',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_013_Item',
    localizedString: 'Harvest Moon',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_013',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_013_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_013',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_014_Item',
    localizedString: 'Umbros',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_014',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_014_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_014',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_015_Item',
    localizedString: "Night's Edge",
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/ui_icon_rendered_weapon_DW_015',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_015_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_015',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_019_Item',
    localizedString: 'God Bleeder',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/DW_019',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_019_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_019',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'DW_021_Item',
    localizedString: 'Hush',
    type: 'DualWieldDaggers',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_DW/Icon_DW_021',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/DWItems.DWItems'",
      rowName: 'DW_021_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/DWPersonas.DWPersonas'",
        rowName: 'DW_021',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
const MaceItems: INVENTORY_ITEM[] = [
  {
    key: '2H_Mace_003_Item',
    localizedString: 'Doldrum',
    type: 'TwoHandedMace',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HMace/ui_icon_rendered_weapon_2HMace_003',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/MaceItems.MaceItems'",
      rowName: '2H_Mace_003_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/MacePersonas.MacePersonas'",
        rowName: '2H_Mace_003',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2H_Mace_006_Item',
    localizedString: 'Juggernaut',
    type: 'TwoHandedMace',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HMace/ui_icon_rendered_weapon_2HMace_006',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/MaceItems.MaceItems'",
      rowName: '2H_Mace_006_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/MacePersonas.MacePersonas'",
        rowName: '2H_Mace_006',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
const RifleItems: INVENTORY_ITEM[] = [
  {
    key: '2HR_Starter_Item',
    localizedString: 'Ransom',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/008',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_Starter_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_Starter',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_003_Item',
    localizedString: 'Arcstorm',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/ui_icon_rendered_weapon_2HRifle_003',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_003_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_003',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_004_Item',
    localizedString: 'Hellswarm',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/ui_icon_rendered_weapon_2HRifle_004',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_004_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_004',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_006_Item',
    localizedString: 'Longshot',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/ui_icon_rendered_weapon_2HRifle_006',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_006_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_006',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_007_Item',
    localizedString: 'Nightshade',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/007',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_007_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_007',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_009_Item',
    localizedString: 'Tempest',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/009',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_009_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_009',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_012_Item',
    localizedString: 'Duskbringer',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/ui_icon_rendered_weapon_2HRifle_012',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_012_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_012',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_013_Item',
    localizedString: 'Voidbinder',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/ui_icon_rendered_weapon_2HRifle_013',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_013_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_013',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HShotgun_001_Item',
    localizedString: 'Covetous',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/2hShotgun_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HShotgun_001_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HShotgun_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HRune_001_Item',
    localizedString: 'Vesper-III',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/2hRune_001',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HRune_001_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HRune_001',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HRune_002_Item',
    localizedString: 'Requiem',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/2hRune_002',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HRune_002_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HRune_002',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: '2HR_017_Item',
    localizedString: 'Last Ditch',
    type: 'TwoHandedRifle',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_2HRifle/Icon_Weapon_2hRifle_017',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/RifleItems.RifleItems'",
      rowName: '2HR_017_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable:
          "DataTable'/Game/Data/Inventory/RiflePersonas.RiflePersonas'",
        rowName: '2HR_017',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];
const SnSItems: INVENTORY_ITEM[] = [
  {
    key: 'SnS_Starter_Item',
    localizedString: 'Vanguard',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_015',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_Starter_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_Starter',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_002_Item',
    localizedString: 'Dryades',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_002',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_002_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_002',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_003_Item',
    localizedString: 'Grim Harvest',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_003',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_003_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_003',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_005_Item',
    localizedString: 'Tooth and Claw',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_005',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_005_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_005',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_006_Item',
    localizedString: 'Gallant Bulwark',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_006',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_006_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_006',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_007_Item',
    localizedString: 'Legacy',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_007',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_007_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_007',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_009_Item',
    localizedString: 'Bastion',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_009',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_009_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_009',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_010_Item',
    localizedString: 'Unity',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_010',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_010_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_010',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_016_Item',
    localizedString: 'Radiant Dawn',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_016',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_016_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_016',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
  {
    key: 'SnS_021_Item',
    localizedString: 'Warp & Weft',
    type: 'SwordAndShield',
    icon: 'Icons/Equipment/Weapons/RenderedOfficial/render_SnS/ui_icon_rendered_weapon_SnS_021',
    data: {
      dataTable: "DataTable'/Game/Data/Inventory/SnSItems.SnSItems'",
      rowName: 'SnS_021_Item',
    },
    addItemsWhenCreated: [
      {
        dataTable: "DataTable'/Game/Data/Inventory/SnSPersonas.SnSPersonas'",
        rowName: 'SnS_021',
      },
    ],
    equipmentSlot: 'EEquipmentSlotType::WEAPON',
    bIsArchetype: false,
    bIsCharacter: false,
    bIsCraftingMaterial: false,
    bIsCraftable: true,
    bIsEquipable: true,
    bIsFogSoul: false,
    bIsTalent: false,
    bIsHousingItem: false,
    bIsPlayerSpray: false,
    bIsConsumable: false,
    bIsFlask: false,
    bIsNone: false,
    bIsFungible: false,
    bIsQuestRestricted: false,
    bIsEventItem: false,
    bIsImbuementVessel: false,
    bIsImbuement: false,
    bIsPseudoItem: false,
    bIsIOUItem: false,
    bIsFungibleMultiplierItem: false,
    bIsDye: false,
    bIsPlayerAction: false,
    bIsPlayerBadgeCustomization: false,
  },
];

const WEAPONS = [
  ...TwoHScytheItems,
  ...TwoHSwordItems,
  ...AxeItems,
  ...DWItems,
  ...MaceItems,
  ...RifleItems,
  ...SnSItems,
];

export { WEAPONS };
