import { ArchetypeTreeEntry } from '../../saveFileTypes';

const Defensive: ArchetypeTreeEntry[] = [
  {
    id: '0',
    type: 'All',
    bIsNetworked: false,
    connectedNodes: [
      { id: '1', type: 'Offensive', index: 2 },
      { id: '37', type: 'Support', index: 1 },
      { id: '73', type: 'Defensive', index: 1 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 0 },
    color: 'F9C140',
  },
  {
    id: '73',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '74', type: 'Defensive', index: 2 },
      { id: '104', type: 'Defensive', index: 33 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 3 },
    color: '963DED',
  },
  {
    id: '74',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '73', type: 'Defensive', index: 1 },
      { id: '75', type: 'Defensive', index: 3 },
    ],
    connectedNodeNetwork: [],
    position: { X: -4, Y: 5 },
    color: '963DED',
  },
  {
    id: '75',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '74', type: 'Defensive', index: 2 },
      { id: '76', type: 'Defensive', index: 4 },
      { id: '106', type: 'Defensive', index: 35 },
    ],
    connectedNodeNetwork: [],
    position: { X: -8, Y: 7 },
    color: '963DED',
  },
  {
    id: '76',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '75', type: 'Defensive', index: 3 },
      { id: '77', type: 'Defensive', index: 5 },
    ],
    connectedNodeNetwork: [],
    position: { X: -12, Y: 9 },
    color: '963DED',
  },
  {
    id: '77',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '76', type: 'Defensive', index: 4 },
      { id: '78', type: 'Defensive', index: 6 },
    ],
    connectedNodeNetwork: [],
    position: { X: -16, Y: 11 },
    color: '963DED',
  },
  {
    id: '78',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '77', type: 'Defensive', index: 5 },
      { id: '79', type: 'Defensive', index: 7 },
    ],
    connectedNodeNetwork: [],
    position: { X: -20, Y: 13 },
    color: 'FFAD00',
  },
  {
    id: '79',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '78', type: 'Defensive', index: 6 },
      { id: '80', type: 'Defensive', index: 8 },
    ],
    connectedNodeNetwork: [],
    position: { X: -17, Y: 16 },
    color: '963DED',
  },
  {
    id: '80',
    type: 'Defensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '79', type: 'Defensive', index: 7 },
      { id: '81', type: 'Defensive', index: 9 },
      { id: '82', type: 'Defensive', index: 10 },
    ],
    connectedNodeNetwork: [
      { id: '81', type: 'Defensive', index: 9 },
      { id: '82', type: 'Defensive', index: 10 },
    ],
    position: { X: -13, Y: 17 },
    color: '963DED',
  },
  {
    id: '81',
    type: 'Defensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '80', type: 'Defensive', index: 8 },
      { id: '82', type: 'Defensive', index: 10 },
      { id: '89', type: 'Defensive', index: 17 },
    ],
    connectedNodeNetwork: [
      { id: '80', type: 'Defensive', index: 8 },
      { id: '82', type: 'Defensive', index: 10 },
    ],
    position: { X: -10, Y: 18.5 },
    color: '963DED',
  },
  {
    id: '82',
    type: 'Defensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '80', type: 'Defensive', index: 8 },
      { id: '81', type: 'Defensive', index: 9 },
      { id: '83', type: 'Defensive', index: 11 },
    ],
    connectedNodeNetwork: [
      { id: '80', type: 'Defensive', index: 8 },
      { id: '81', type: 'Defensive', index: 9 },
    ],
    position: { X: -10.5, Y: 15 },
    color: '963DED',
  },
  {
    id: '83',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '82', type: 'Defensive', index: 10 },
      { id: '84', type: 'Defensive', index: 12 },
      { id: '98', type: 'Defensive', index: 26 },
    ],
    connectedNodeNetwork: [],
    position: { X: -7, Y: 12 },
    color: '963DED',
  },
  {
    id: '84',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '83', type: 'Defensive', index: 11 },
      { id: '85', type: 'Defensive', index: 13 },
    ],
    connectedNodeNetwork: [],
    position: { X: -6, Y: 15 },
    color: '963DED',
  },
  {
    id: '85',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '84', type: 'Defensive', index: 12 },
      { id: '86', type: 'Defensive', index: 14 },
    ],
    connectedNodeNetwork: [],
    position: { X: -3.5, Y: 17 },
    color: '963DED',
  },
  {
    id: '86',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '85', type: 'Defensive', index: 13 },
      { id: '87', type: 'Defensive', index: 15 },
      { id: '107', type: 'Defensive', index: 36 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 18 },
    color: '963DED',
  },
  {
    id: '87',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '86', type: 'Defensive', index: 14 },
      { id: '88', type: 'Defensive', index: 16 },
    ],
    connectedNodeNetwork: [],
    position: { X: 3.5, Y: 17 },
    color: '963DED',
  },
  {
    id: '88',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '87', type: 'Defensive', index: 15 },
      { id: '97', type: 'Defensive', index: 25 },
    ],
    connectedNodeNetwork: [],
    position: { X: 6, Y: 15 },
    color: '963DED',
  },
  {
    id: '89',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '81', type: 'Defensive', index: 9 },
      { id: '90', type: 'Defensive', index: 18 },
    ],
    connectedNodeNetwork: [],
    position: { X: -9, Y: 22 },
    color: '7B78FF',
  },
  {
    id: '90',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '89', type: 'Defensive', index: 17 },
      { id: '91', type: 'Defensive', index: 19 },
    ],
    connectedNodeNetwork: [],
    position: { X: -5, Y: 26 },
    color: '963DED',
  },
  {
    id: '91',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '90', type: 'Defensive', index: 18 },
      { id: '92', type: 'Defensive', index: 20 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 28 },
    color: '7B78FF',
  },
  {
    id: '92',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '91', type: 'Defensive', index: 19 },
      { id: '93', type: 'Defensive', index: 21 },
    ],
    connectedNodeNetwork: [],
    position: { X: 5, Y: 26 },
    color: '963DED',
  },
  {
    id: '93',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '92', type: 'Defensive', index: 20 },
      { id: '94', type: 'Defensive', index: 22 },
    ],
    connectedNodeNetwork: [],
    position: { X: 9, Y: 22 },
    color: '7B78FF',
  },
  {
    id: '94',
    type: 'Defensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '93', type: 'Defensive', index: 21 },
      { id: '95', type: 'Defensive', index: 23 },
      { id: '96', type: 'Defensive', index: 24 },
    ],
    connectedNodeNetwork: [
      { id: '95', type: 'Defensive', index: 23 },
      { id: '96', type: 'Defensive', index: 24 },
    ],
    position: { X: 10, Y: 18.5 },
    color: '963DED',
  },
  {
    id: '95',
    type: 'Defensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '94', type: 'Defensive', index: 22 },
      { id: '96', type: 'Defensive', index: 24 },
      { id: '99', type: 'Defensive', index: 27 },
    ],
    connectedNodeNetwork: [
      { id: '94', type: 'Defensive', index: 22 },
      { id: '96', type: 'Defensive', index: 24 },
    ],
    position: { X: 13, Y: 17 },
    color: '963DED',
  },
  {
    id: '96',
    type: 'Defensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '94', type: 'Defensive', index: 22 },
      { id: '95', type: 'Defensive', index: 23 },
      { id: '97', type: 'Defensive', index: 25 },
    ],
    connectedNodeNetwork: [
      { id: '94', type: 'Defensive', index: 22 },
      { id: '95', type: 'Defensive', index: 23 },
    ],
    position: { X: 10.5, Y: 15 },
    color: '963DED',
  },
  {
    id: '97',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '88', type: 'Defensive', index: 16 },
      { id: '96', type: 'Defensive', index: 24 },
      { id: '98', type: 'Defensive', index: 26 },
    ],
    connectedNodeNetwork: [],
    position: { X: 7, Y: 12 },
    color: '963DED',
  },
  {
    id: '98',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '83', type: 'Defensive', index: 11 },
      { id: '97', type: 'Defensive', index: 25 },
      { id: '105', type: 'Defensive', index: 34 },
      { id: '106', type: 'Defensive', index: 35 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 12 },
    color: '7B78FF',
  },
  {
    id: '99',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '95', type: 'Defensive', index: 23 },
      { id: '100', type: 'Defensive', index: 29 },
    ],
    connectedNodeNetwork: [],
    position: { X: 17, Y: 16 },
    color: '963DED',
  },
  {
    id: '111',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '29', type: 'Offensive', index: 30 },
      { id: '76', type: 'Defensive', index: 4 },
    ],
    connectedNodeNetwork: [],
    position: { X: -13.7, Y: 6.3 },
    color: '67FFC8',
  },
  {
    id: '100',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '99', type: 'Defensive', index: 27 },
      { id: '101', type: 'Defensive', index: 30 },
    ],
    connectedNodeNetwork: [],
    position: { X: 20, Y: 13 },
    color: 'FFAD00',
  },
  {
    id: '101',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '100', type: 'Defensive', index: 29 },
      { id: '102', type: 'Defensive', index: 31 },
    ],
    connectedNodeNetwork: [],
    position: { X: 16, Y: 11 },
    color: '963DED',
  },
  {
    id: '102',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '103', type: 'Defensive', index: 32 },
      { id: '101', type: 'Defensive', index: 30 },
    ],
    connectedNodeNetwork: [],
    position: { X: 12, Y: 9 },
    color: '963DED',
  },
  {
    id: '103',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '102', type: 'Defensive', index: 31 },
      { id: '104', type: 'Defensive', index: 33 },
      { id: '105', type: 'Defensive', index: 34 },
    ],
    connectedNodeNetwork: [],
    position: { X: 8, Y: 7 },
    color: '963DED',
  },
  {
    id: '104',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '73', type: 'Defensive', index: 1 },
      { id: '103', type: 'Defensive', index: 32 },
    ],
    connectedNodeNetwork: [],
    position: { X: 4, Y: 5 },
    color: '963DED',
  },
  {
    id: '105',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '98', type: 'Defensive', index: 26 },
      { id: '103', type: 'Defensive', index: 32 },
    ],
    connectedNodeNetwork: [],
    position: { X: 4, Y: 9.5 },
    color: '963DED',
  },
  {
    id: '106',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '75', type: 'Defensive', index: 3 },
      { id: '98', type: 'Defensive', index: 26 },
    ],
    connectedNodeNetwork: [],
    position: { X: -4, Y: 9.5 },
    color: '963DED',
  },
  {
    id: '107',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '86', type: 'Defensive', index: 14 },
      { id: '108', type: 'Defensive', index: 37 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 20.5 },
    color: '963DED',
  },
  {
    id: '108',
    type: 'Defensive',
    bIsNetworked: false,
    connectedNodes: [],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 24 },
    color: 'FFAD00',
  },
];
const Offensive: ArchetypeTreeEntry[] = [
  {
    id: '110',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '4', type: 'Offensive', index: 5 },
      { id: '62', type: 'Support', index: 26 },
    ],
    connectedNodeNetwork: [],
    position: { X: -13.7, Y: 6.3 },
    color: '67FFC8',
  },
  {
    id: '1',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '2', type: 'Offensive', index: 3 },
      { id: '31', type: 'Offensive', index: 32 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 3 },
    color: '963DED',
  },
  {
    id: '2',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '1', type: 'Offensive', index: 2 },
      { id: '3', type: 'Offensive', index: 4 },
    ],
    connectedNodeNetwork: [],
    position: { X: -4, Y: 5 },
    color: '963DED',
  },
  {
    id: '3',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '2', type: 'Offensive', index: 3 },
      { id: '4', type: 'Offensive', index: 5 },
      { id: '12', type: 'Offensive', index: 13 },
    ],
    connectedNodeNetwork: [],
    position: { X: -8, Y: 7 },
    color: '963DED',
  },
  {
    id: '4',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '3', type: 'Offensive', index: 4 },
      { id: '5', type: 'Offensive', index: 6 },
    ],
    connectedNodeNetwork: [],
    position: { X: -12, Y: 9 },
    color: '963DED',
  },
  {
    id: '5',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '4', type: 'Offensive', index: 5 },
      { id: '6', type: 'Offensive', index: 7 },
    ],
    connectedNodeNetwork: [],
    position: { X: -16, Y: 11 },
    color: '963DED',
  },
  {
    id: '6',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '5', type: 'Offensive', index: 6 },
      { id: '7', type: 'Offensive', index: 8 },
    ],
    connectedNodeNetwork: [],
    position: { X: -20, Y: 13 },
    color: 'FFAD00',
  },
  {
    id: '7',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '6', type: 'Offensive', index: 7 },
      { id: '8', type: 'Offensive', index: 9 },
    ],
    connectedNodeNetwork: [],
    position: { X: -17, Y: 16 },
    color: '963DED',
  },
  {
    id: '8',
    type: 'Offensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '7', type: 'Offensive', index: 8 },
      { id: '9', type: 'Offensive', index: 10 },
      { id: '10', type: 'Offensive', index: 11 },
    ],
    connectedNodeNetwork: [
      { id: '9', type: 'Offensive', index: 10 },
      { id: '10', type: 'Offensive', index: 11 },
    ],
    position: { X: -13, Y: 17 },
    color: '963DED',
  },
  {
    id: '9',
    type: 'Offensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '8', type: 'Offensive', index: 9 },
      { id: '10', type: 'Offensive', index: 11 },
      { id: '11', type: 'Offensive', index: 12 },
    ],
    connectedNodeNetwork: [
      { id: '8', type: 'Offensive', index: 9 },
      { id: '10', type: 'Offensive', index: 11 },
    ],
    position: { X: -10.5, Y: 15 },
    color: '963DED',
  },
  {
    id: '10',
    type: 'Offensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '8', type: 'Offensive', index: 9 },
      { id: '9', type: 'Offensive', index: 10 },
      { id: '25', type: 'Offensive', index: 26 },
    ],
    connectedNodeNetwork: [
      { id: '8', type: 'Offensive', index: 9 },
      { id: '9', type: 'Offensive', index: 10 },
    ],
    position: { X: -10, Y: 18.5 },
    color: '963DED',
  },
  {
    id: '11',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '9', type: 'Offensive', index: 10 },
      { id: '13', type: 'Offensive', index: 14 },
      { id: '14', type: 'Offensive', index: 15 },
    ],
    connectedNodeNetwork: [],
    position: { X: -7, Y: 12 },
    color: '963DED',
  },
  {
    id: '12',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '3', type: 'Offensive', index: 4 },
      { id: '13', type: 'Offensive', index: 14 },
    ],
    connectedNodeNetwork: [],
    position: { X: -4, Y: 9.5 },
    color: '963DED',
  },
  {
    id: '13',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '11', type: 'Offensive', index: 12 },
      { id: '12', type: 'Offensive', index: 13 },
      { id: '17', type: 'Offensive', index: 18 },
      { id: '32', type: 'Offensive', index: 33 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 12 },
    color: '7B78FF',
  },
  {
    id: '14',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '11', type: 'Offensive', index: 12 },
      { id: '15', type: 'Offensive', index: 16 },
    ],
    connectedNodeNetwork: [],
    position: { X: -6, Y: 15 },
    color: '963DED',
  },
  {
    id: '15',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '14', type: 'Offensive', index: 15 },
      { id: '34', type: 'Offensive', index: 35 },
    ],
    connectedNodeNetwork: [],
    position: { X: -3.5, Y: 17 },
    color: '963DED',
  },
  {
    id: '16',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '17', type: 'Offensive', index: 18 },
      { id: '33', type: 'Offensive', index: 34 },
    ],
    connectedNodeNetwork: [],
    position: { X: 6, Y: 15 },
    color: '963DED',
  },
  {
    id: '17',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '13', type: 'Offensive', index: 14 },
      { id: '16', type: 'Offensive', index: 17 },
      { id: '18', type: 'Offensive', index: 19 },
    ],
    connectedNodeNetwork: [],
    position: { X: 7, Y: 12 },
    color: '963DED',
  },
  {
    id: '18',
    type: 'Offensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '17', type: 'Offensive', index: 18 },
      { id: '19', type: 'Offensive', index: 20 },
      { id: '20', type: 'Offensive', index: 21 },
    ],
    connectedNodeNetwork: [
      { id: '19', type: 'Offensive', index: 20 },
      { id: '20', type: 'Offensive', index: 21 },
    ],
    position: { X: 10.5, Y: 15 },
    color: '963DED',
  },
  {
    id: '19',
    type: 'Offensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '18', type: 'Offensive', index: 19 },
      { id: '20', type: 'Offensive', index: 21 },
      { id: '26', type: 'Offensive', index: 27 },
    ],
    connectedNodeNetwork: [
      { id: '18', type: 'Offensive', index: 19 },
      { id: '20', type: 'Offensive', index: 21 },
    ],
    position: { X: 13, Y: 17 },
    color: '963DED',
  },
  {
    id: '20',
    type: 'Offensive',
    bIsNetworked: true,
    connectedNodes: [
      { id: '18', type: 'Offensive', index: 19 },
      { id: '19', type: 'Offensive', index: 20 },
      { id: '21', type: 'Offensive', index: 22 },
    ],
    connectedNodeNetwork: [
      { id: '18', type: 'Offensive', index: 19 },
      { id: '19', type: 'Offensive', index: 20 },
    ],
    position: { X: 10, Y: 18.5 },
    color: '963DED',
  },
  {
    id: '21',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '20', type: 'Offensive', index: 21 },
      { id: '22', type: 'Offensive', index: 23 },
    ],
    connectedNodeNetwork: [],
    position: { X: 9, Y: 22 },
    color: '7B78FF',
  },
  {
    id: '22',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '21', type: 'Offensive', index: 22 },
      { id: '23', type: 'Offensive', index: 24 },
    ],
    connectedNodeNetwork: [],
    position: { X: 5, Y: 26 },
    color: '963DED',
  },
  {
    id: '23',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '22', type: 'Offensive', index: 23 },
      { id: '24', type: 'Offensive', index: 25 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 28 },
    color: '7B78FF',
  },
  {
    id: '24',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '23', type: 'Offensive', index: 24 },
      { id: '25', type: 'Offensive', index: 26 },
    ],
    connectedNodeNetwork: [],
    position: { X: -5, Y: 26 },
    color: '963DED',
  },
  {
    id: '25',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '10', type: 'Offensive', index: 11 },
      { id: '24', type: 'Offensive', index: 25 },
    ],
    connectedNodeNetwork: [],
    position: { X: -9, Y: 22 },
    color: '7B78FF',
  },
  {
    id: '26',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '19', type: 'Offensive', index: 20 },
      { id: '27', type: 'Offensive', index: 28 },
    ],
    connectedNodeNetwork: [],
    position: { X: 17, Y: 16 },
    color: '963DED',
  },
  {
    id: '27',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '26', type: 'Offensive', index: 27 },
      { id: '28', type: 'Offensive', index: 29 },
    ],
    connectedNodeNetwork: [],
    position: { X: 20, Y: 13 },
    color: 'FFAD00',
  },
  {
    id: '28',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '27', type: 'Offensive', index: 28 },
      { id: '29', type: 'Offensive', index: 30 },
    ],
    connectedNodeNetwork: [],
    position: { X: 16, Y: 11 },
    color: '963DED',
  },
  {
    id: '29',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '28', type: 'Offensive', index: 29 },
      { id: '30', type: 'Offensive', index: 31 },
    ],
    connectedNodeNetwork: [],
    position: { X: 12, Y: 9 },
    color: '963DED',
  },
  {
    id: '30',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '29', type: 'Offensive', index: 30 },
      { id: '31', type: 'Offensive', index: 32 },
      { id: '32', type: 'Offensive', index: 33 },
    ],
    connectedNodeNetwork: [],
    position: { X: 8, Y: 7 },
    color: '963DED',
  },
  {
    id: '31',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '1', type: 'Offensive', index: 2 },
      { id: '30', type: 'Offensive', index: 31 },
    ],
    connectedNodeNetwork: [],
    position: { X: 4, Y: 5 },
    color: '963DED',
  },
  {
    id: '32',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '13', type: 'Offensive', index: 14 },
      { id: '30', type: 'Offensive', index: 31 },
    ],
    connectedNodeNetwork: [],
    position: { X: 4, Y: 9.5 },
    color: '963DED',
  },
  {
    id: '33',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '16', type: 'Offensive', index: 17 },
      { id: '34', type: 'Offensive', index: 35 },
    ],
    connectedNodeNetwork: [],
    position: { X: 3.5, Y: 17 },
    color: '963DED',
  },
  {
    id: '34',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '15', type: 'Offensive', index: 16 },
      { id: '33', type: 'Offensive', index: 34 },
      { id: '35', type: 'Offensive', index: 36 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 18 },
    color: '963DED',
  },
  {
    id: '35',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [
      { id: '34', type: 'Offensive', index: 35 },
      { id: '36', type: 'Offensive', index: 37 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 20.5 },
    color: '963DED',
  },
  {
    id: '36',
    type: 'Offensive',
    bIsNetworked: false,
    connectedNodes: [],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 24 },
    color: 'FFAD00',
  },
];
const Support: ArchetypeTreeEntry[] = [
  {
    id: '37',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '38', type: 'Support', index: 2 },
      { id: '64', type: 'Support', index: 28 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 3 },
    color: '963DED',
  },
  {
    id: '38',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '37', type: 'Support', index: 1 },
      { id: '39', type: 'Support', index: 3 },
    ],
    connectedNodeNetwork: [],
    position: { X: -4, Y: 5 },
    color: '963DED',
  },
  {
    id: '39',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '38', type: 'Support', index: 2 },
      { id: '40', type: 'Support', index: 4 },
      { id: '48', type: 'Support', index: 12 },
    ],
    connectedNodeNetwork: [],
    position: { X: -8, Y: 7 },
    color: '963DED',
  },
  {
    id: '40',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '39', type: 'Support', index: 3 },
      { id: '41', type: 'Support', index: 5 },
    ],
    connectedNodeNetwork: [],
    position: { X: -12, Y: 9 },
    color: '963DED',
  },
  {
    id: '41',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '40', type: 'Support', index: 4 },
      { id: '42', type: 'Support', index: 6 },
    ],
    connectedNodeNetwork: [],
    position: { X: -16, Y: 11 },
    color: '963DED',
  },
  {
    id: '42',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '41', type: 'Support', index: 5 },
      { id: '43', type: 'Support', index: 7 },
    ],
    connectedNodeNetwork: [],
    position: { X: -20, Y: 13 },
    color: 'FFAD00',
  },
  {
    id: '43',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '42', type: 'Support', index: 6 },
      { id: '44', type: 'Support', index: 8 },
    ],
    connectedNodeNetwork: [],
    position: { X: -17, Y: 16 },
    color: '963DED',
  },
  {
    id: '44',
    type: 'Support',
    bIsNetworked: true,
    connectedNodes: [
      { id: '43', type: 'Support', index: 7 },
      { id: '45', type: 'Support', index: 9 },
      { id: '46', type: 'Support', index: 10 },
    ],
    connectedNodeNetwork: [
      { id: '45', type: 'Support', index: 9 },
      { id: '46', type: 'Support', index: 10 },
    ],
    position: { X: -13, Y: 17 },
    color: '963DED',
  },
  {
    id: '45',
    type: 'Support',
    bIsNetworked: true,
    connectedNodes: [
      { id: '44', type: 'Support', index: 8 },
      { id: '46', type: 'Support', index: 10 },
      { id: '66', type: 'Support', index: 30 },
    ],
    connectedNodeNetwork: [
      { id: '44', type: 'Support', index: 8 },
      { id: '46', type: 'Support', index: 10 },
    ],
    position: { X: -10, Y: 18.5 },
    color: '963DED',
  },
  {
    id: '46',
    type: 'Support',
    bIsNetworked: true,
    connectedNodes: [
      { id: '44', type: 'Support', index: 8 },
      { id: '45', type: 'Support', index: 9 },
      { id: '47', type: 'Support', index: 11 },
    ],
    connectedNodeNetwork: [
      { id: '44', type: 'Support', index: 8 },
      { id: '45', type: 'Support', index: 9 },
    ],
    position: { X: -10.5, Y: 15 },
    color: '963DED',
  },
  {
    id: '47',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '46', type: 'Support', index: 10 },
      { id: '49', type: 'Support', index: 13 },
      { id: '51', type: 'Support', index: 15 },
    ],
    connectedNodeNetwork: [],
    position: { X: -7, Y: 12 },
    color: '963DED',
  },
  {
    id: '48',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '39', type: 'Support', index: 3 },
      { id: '49', type: 'Support', index: 13 },
    ],
    connectedNodeNetwork: [],
    position: { X: -4, Y: 9 },
    color: '963DED',
  },
  {
    id: '49',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '47', type: 'Support', index: 11 },
      { id: '48', type: 'Support', index: 12 },
      { id: '50', type: 'Support', index: 14 },
      { id: '65', type: 'Support', index: 29 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 11 },
    color: '7B78FF',
  },
  {
    id: '50',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '49', type: 'Support', index: 13 },
      { id: '55', type: 'Support', index: 19 },
      { id: '58', type: 'Support', index: 22 },
    ],
    connectedNodeNetwork: [],
    position: { X: 7, Y: 12 },
    color: '963DED',
  },
  {
    id: '51',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '47', type: 'Support', index: 11 },
      { id: '52', type: 'Support', index: 16 },
    ],
    connectedNodeNetwork: [],
    position: { X: -6, Y: 15 },
    color: '963DED',
  },
  {
    id: '52',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '51', type: 'Support', index: 15 },
      { id: '53', type: 'Support', index: 17 },
    ],
    connectedNodeNetwork: [],
    position: { X: -3.5, Y: 17 },
    color: '963DED',
  },
  {
    id: '53',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '52', type: 'Support', index: 16 },
      { id: '54', type: 'Support', index: 18 },
      { id: '71', type: 'Support', index: 36 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 18 },
    color: '963DED',
  },
  {
    id: '54',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '53', type: 'Support', index: 17 },
      { id: '55', type: 'Support', index: 19 },
    ],
    connectedNodeNetwork: [],
    position: { X: 3.5, Y: 17 },
    color: '963DED',
  },
  {
    id: '55',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '50', type: 'Support', index: 14 },
      { id: '54', type: 'Support', index: 18 },
    ],
    connectedNodeNetwork: [],
    position: { X: 6, Y: 15 },
    color: '963DED',
  },
  {
    id: '56',
    type: 'Support',
    bIsNetworked: true,
    connectedNodes: [
      { id: '57', type: 'Support', index: 21 },
      { id: '58', type: 'Support', index: 22 },
      { id: '70', type: 'Support', index: 35 },
    ],
    connectedNodeNetwork: [
      { id: '57', type: 'Support', index: 21 },
      { id: '58', type: 'Support', index: 22 },
    ],
    position: { X: 10, Y: 18.5 },
    color: '963DED',
  },
  {
    id: '57',
    type: 'Support',
    bIsNetworked: true,
    connectedNodes: [
      { id: '56', type: 'Support', index: 20 },
      { id: '58', type: 'Support', index: 22 },
      { id: '59', type: 'Support', index: 23 },
    ],
    connectedNodeNetwork: [
      { id: '56', type: 'Support', index: 20 },
      { id: '58', type: 'Support', index: 22 },
    ],
    position: { X: 13, Y: 17 },
    color: '963DED',
  },
  {
    id: '58',
    type: 'Support',
    bIsNetworked: true,
    connectedNodes: [
      { id: '50', type: 'Support', index: 14 },
      { id: '56', type: 'Support', index: 20 },
      { id: '57', type: 'Support', index: 21 },
    ],
    connectedNodeNetwork: [
      { id: '56', type: 'Support', index: 20 },
      { id: '57', type: 'Support', index: 21 },
    ],
    position: { X: 10.5, Y: 15 },
    color: '963DED',
  },
  {
    id: '59',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '57', type: 'Support', index: 21 },
      { id: '60', type: 'Support', index: 24 },
    ],
    connectedNodeNetwork: [],
    position: { X: 17, Y: 16 },
    color: '963DED',
  },
  {
    id: '60',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '59', type: 'Support', index: 23 },
      { id: '61', type: 'Support', index: 25 },
    ],
    connectedNodeNetwork: [],
    position: { X: 20, Y: 13 },
    color: 'FFAD00',
  },
  {
    id: '61',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '60', type: 'Support', index: 24 },
      { id: '62', type: 'Support', index: 26 },
    ],
    connectedNodeNetwork: [],
    position: { X: 16, Y: 11 },
    color: '963DED',
  },
  {
    id: '62',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '61', type: 'Support', index: 25 },
      { id: '63', type: 'Support', index: 27 },
    ],
    connectedNodeNetwork: [],
    position: { X: 12, Y: 9 },
    color: '963DED',
  },
  {
    id: '63',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '62', type: 'Support', index: 26 },
      { id: '64', type: 'Support', index: 28 },
      { id: '65', type: 'Support', index: 29 },
    ],
    connectedNodeNetwork: [],
    position: { X: 8, Y: 7 },
    color: '963DED',
  },
  {
    id: '64',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '37', type: 'Support', index: 1 },
      { id: '63', type: 'Support', index: 27 },
    ],
    connectedNodeNetwork: [],
    position: { X: 4, Y: 5 },
    color: '963DED',
  },
  {
    id: '65',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '49', type: 'Support', index: 13 },
      { id: '63', type: 'Support', index: 27 },
    ],
    connectedNodeNetwork: [],
    position: { X: 4, Y: 9 },
    color: '963DED',
  },
  {
    id: '66',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '45', type: 'Support', index: 9 },
      { id: '67', type: 'Support', index: 32 },
    ],
    connectedNodeNetwork: [],
    position: { X: -9, Y: 22 },
    color: '7B78FF',
  },
  {
    id: '109',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '102', type: 'Defensive', index: 31 },
      { id: '40', type: 'Support', index: 4 },
    ],
    connectedNodeNetwork: [],
    position: { X: -13.7, Y: 6.3 },
    color: '67FFC8',
  },
  {
    id: '67',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '66', type: 'Support', index: 30 },
      { id: '68', type: 'Support', index: 33 },
    ],
    connectedNodeNetwork: [],
    position: { X: -5, Y: 26 },
    color: '963DED',
  },
  {
    id: '68',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '67', type: 'Support', index: 32 },
      { id: '69', type: 'Support', index: 34 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 28 },
    color: '7B78FF',
  },
  {
    id: '69',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '68', type: 'Support', index: 33 },
      { id: '70', type: 'Support', index: 35 },
    ],
    connectedNodeNetwork: [],
    position: { X: 5, Y: 26 },
    color: '963DED',
  },
  {
    id: '70',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '56', type: 'Support', index: 20 },
      { id: '69', type: 'Support', index: 34 },
    ],
    connectedNodeNetwork: [],
    position: { X: 9, Y: 22 },
    color: '7B78FF',
  },
  {
    id: '71',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [
      { id: '53', type: 'Support', index: 17 },
      { id: '72', type: 'Support', index: 37 },
    ],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 20.5 },
    color: '963DED',
  },
  {
    id: '72',
    type: 'Support',
    bIsNetworked: false,
    connectedNodes: [],
    connectedNodeNetwork: [],
    position: { X: 0, Y: 24 },
    color: 'FFAD00',
  },
];

export default [...Defensive, ...Offensive, ...Support];
